//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v17/errors/ad_group_criterion_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use adGroupCriterionErrorEnumDescriptor instead')
const AdGroupCriterionErrorEnum$json = {
  '1': 'AdGroupCriterionErrorEnum',
  '4': [AdGroupCriterionErrorEnum_AdGroupCriterionError$json],
};

@$core.Deprecated('Use adGroupCriterionErrorEnumDescriptor instead')
const AdGroupCriterionErrorEnum_AdGroupCriterionError$json = {
  '1': 'AdGroupCriterionError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'AD_GROUP_CRITERION_LABEL_DOES_NOT_EXIST', '2': 2},
    {'1': 'AD_GROUP_CRITERION_LABEL_ALREADY_EXISTS', '2': 3},
    {'1': 'CANNOT_ADD_LABEL_TO_NEGATIVE_CRITERION', '2': 4},
    {'1': 'TOO_MANY_OPERATIONS', '2': 5},
    {'1': 'CANT_UPDATE_NEGATIVE', '2': 6},
    {'1': 'CONCRETE_TYPE_REQUIRED', '2': 7},
    {'1': 'BID_INCOMPATIBLE_WITH_ADGROUP', '2': 8},
    {'1': 'CANNOT_TARGET_AND_EXCLUDE', '2': 9},
    {'1': 'ILLEGAL_URL', '2': 10},
    {'1': 'INVALID_KEYWORD_TEXT', '2': 11},
    {'1': 'INVALID_DESTINATION_URL', '2': 12},
    {'1': 'MISSING_DESTINATION_URL_TAG', '2': 13},
    {'1': 'KEYWORD_LEVEL_BID_NOT_SUPPORTED_FOR_MANUALCPM', '2': 14},
    {'1': 'INVALID_USER_STATUS', '2': 15},
    {'1': 'CANNOT_ADD_CRITERIA_TYPE', '2': 16},
    {'1': 'CANNOT_EXCLUDE_CRITERIA_TYPE', '2': 17},
    {'1': 'CAMPAIGN_TYPE_NOT_COMPATIBLE_WITH_PARTIAL_FAILURE', '2': 27},
    {'1': 'OPERATIONS_FOR_TOO_MANY_SHOPPING_ADGROUPS', '2': 28},
    {'1': 'CANNOT_MODIFY_URL_FIELDS_WITH_DUPLICATE_ELEMENTS', '2': 29},
    {'1': 'CANNOT_SET_WITHOUT_FINAL_URLS', '2': 30},
    {'1': 'CANNOT_CLEAR_FINAL_URLS_IF_FINAL_MOBILE_URLS_EXIST', '2': 31},
    {'1': 'CANNOT_CLEAR_FINAL_URLS_IF_FINAL_APP_URLS_EXIST', '2': 32},
    {'1': 'CANNOT_CLEAR_FINAL_URLS_IF_TRACKING_URL_TEMPLATE_EXISTS', '2': 33},
    {'1': 'CANNOT_CLEAR_FINAL_URLS_IF_URL_CUSTOM_PARAMETERS_EXIST', '2': 34},
    {'1': 'CANNOT_SET_BOTH_DESTINATION_URL_AND_FINAL_URLS', '2': 35},
    {'1': 'CANNOT_SET_BOTH_DESTINATION_URL_AND_TRACKING_URL_TEMPLATE', '2': 36},
    {'1': 'FINAL_URLS_NOT_SUPPORTED_FOR_CRITERION_TYPE', '2': 37},
    {'1': 'FINAL_MOBILE_URLS_NOT_SUPPORTED_FOR_CRITERION_TYPE', '2': 38},
  ],
};

/// Descriptor for `AdGroupCriterionErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List adGroupCriterionErrorEnumDescriptor = $convert.base64Decode(
    'ChlBZEdyb3VwQ3JpdGVyaW9uRXJyb3JFbnVtIsIJChVBZEdyb3VwQ3JpdGVyaW9uRXJyb3ISDw'
    'oLVU5TUEVDSUZJRUQQABILCgdVTktOT1dOEAESKwonQURfR1JPVVBfQ1JJVEVSSU9OX0xBQkVM'
    'X0RPRVNfTk9UX0VYSVNUEAISKwonQURfR1JPVVBfQ1JJVEVSSU9OX0xBQkVMX0FMUkVBRFlfRV'
    'hJU1RTEAMSKgomQ0FOTk9UX0FERF9MQUJFTF9UT19ORUdBVElWRV9DUklURVJJT04QBBIXChNU'
    'T09fTUFOWV9PUEVSQVRJT05TEAUSGAoUQ0FOVF9VUERBVEVfTkVHQVRJVkUQBhIaChZDT05DUk'
    'VURV9UWVBFX1JFUVVJUkVEEAcSIQodQklEX0lOQ09NUEFUSUJMRV9XSVRIX0FER1JPVVAQCBId'
    'ChlDQU5OT1RfVEFSR0VUX0FORF9FWENMVURFEAkSDwoLSUxMRUdBTF9VUkwQChIYChRJTlZBTE'
    'lEX0tFWVdPUkRfVEVYVBALEhsKF0lOVkFMSURfREVTVElOQVRJT05fVVJMEAwSHwobTUlTU0lO'
    'R19ERVNUSU5BVElPTl9VUkxfVEFHEA0SMQotS0VZV09SRF9MRVZFTF9CSURfTk9UX1NVUFBPUl'
    'RFRF9GT1JfTUFOVUFMQ1BNEA4SFwoTSU5WQUxJRF9VU0VSX1NUQVRVUxAPEhwKGENBTk5PVF9B'
    'RERfQ1JJVEVSSUFfVFlQRRAQEiAKHENBTk5PVF9FWENMVURFX0NSSVRFUklBX1RZUEUQERI1Cj'
    'FDQU1QQUlHTl9UWVBFX05PVF9DT01QQVRJQkxFX1dJVEhfUEFSVElBTF9GQUlMVVJFEBsSLQop'
    'T1BFUkFUSU9OU19GT1JfVE9PX01BTllfU0hPUFBJTkdfQURHUk9VUFMQHBI0CjBDQU5OT1RfTU'
    '9ESUZZX1VSTF9GSUVMRFNfV0lUSF9EVVBMSUNBVEVfRUxFTUVOVFMQHRIhCh1DQU5OT1RfU0VU'
    'X1dJVEhPVVRfRklOQUxfVVJMUxAeEjYKMkNBTk5PVF9DTEVBUl9GSU5BTF9VUkxTX0lGX0ZJTk'
    'FMX01PQklMRV9VUkxTX0VYSVNUEB8SMwovQ0FOTk9UX0NMRUFSX0ZJTkFMX1VSTFNfSUZfRklO'
    'QUxfQVBQX1VSTFNfRVhJU1QQIBI7CjdDQU5OT1RfQ0xFQVJfRklOQUxfVVJMU19JRl9UUkFDS0'
    'lOR19VUkxfVEVNUExBVEVfRVhJU1RTECESOgo2Q0FOTk9UX0NMRUFSX0ZJTkFMX1VSTFNfSUZf'
    'VVJMX0NVU1RPTV9QQVJBTUVURVJTX0VYSVNUECISMgouQ0FOTk9UX1NFVF9CT1RIX0RFU1RJTk'
    'FUSU9OX1VSTF9BTkRfRklOQUxfVVJMUxAjEj0KOUNBTk5PVF9TRVRfQk9USF9ERVNUSU5BVElP'
    'Tl9VUkxfQU5EX1RSQUNLSU5HX1VSTF9URU1QTEFURRAkEi8KK0ZJTkFMX1VSTFNfTk9UX1NVUF'
    'BPUlRFRF9GT1JfQ1JJVEVSSU9OX1RZUEUQJRI2CjJGSU5BTF9NT0JJTEVfVVJMU19OT1RfU1VQ'
    'UE9SVEVEX0ZPUl9DUklURVJJT05fVFlQRRAm');

