//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v17/errors/bidding_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use biddingErrorEnumDescriptor instead')
const BiddingErrorEnum$json = {
  '1': 'BiddingErrorEnum',
  '4': [BiddingErrorEnum_BiddingError$json],
};

@$core.Deprecated('Use biddingErrorEnumDescriptor instead')
const BiddingErrorEnum_BiddingError$json = {
  '1': 'BiddingError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'BIDDING_STRATEGY_TRANSITION_NOT_ALLOWED', '2': 2},
    {'1': 'CANNOT_ATTACH_BIDDING_STRATEGY_TO_CAMPAIGN', '2': 7},
    {'1': 'INVALID_ANONYMOUS_BIDDING_STRATEGY_TYPE', '2': 10},
    {'1': 'INVALID_BIDDING_STRATEGY_TYPE', '2': 14},
    {'1': 'INVALID_BID', '2': 17},
    {'1': 'BIDDING_STRATEGY_NOT_AVAILABLE_FOR_ACCOUNT_TYPE', '2': 18},
    {'1': 'CANNOT_CREATE_CAMPAIGN_WITH_BIDDING_STRATEGY', '2': 21},
    {'1': 'CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_CAMPAIGN_LEVEL_POP_BIDDING_STRATEGY', '2': 23},
    {'1': 'BIDDING_STRATEGY_NOT_SUPPORTED_WITH_AD_SCHEDULE', '2': 24},
    {'1': 'PAY_PER_CONVERSION_NOT_AVAILABLE_FOR_CUSTOMER', '2': 25},
    {'1': 'PAY_PER_CONVERSION_NOT_ALLOWED_WITH_TARGET_CPA', '2': 26},
    {'1': 'BIDDING_STRATEGY_NOT_ALLOWED_FOR_SEARCH_ONLY_CAMPAIGNS', '2': 27},
    {'1': 'BIDDING_STRATEGY_NOT_SUPPORTED_IN_DRAFTS_OR_EXPERIMENTS', '2': 28},
    {'1': 'BIDDING_STRATEGY_TYPE_DOES_NOT_SUPPORT_PRODUCT_TYPE_ADGROUP_CRITERION', '2': 29},
    {'1': 'BID_TOO_SMALL', '2': 30},
    {'1': 'BID_TOO_BIG', '2': 31},
    {'1': 'BID_TOO_MANY_FRACTIONAL_DIGITS', '2': 32},
    {'1': 'INVALID_DOMAIN_NAME', '2': 33},
    {'1': 'NOT_COMPATIBLE_WITH_PAYMENT_MODE', '2': 34},
    {'1': 'BIDDING_STRATEGY_TYPE_INCOMPATIBLE_WITH_SHARED_BUDGET', '2': 37},
    {'1': 'BIDDING_STRATEGY_AND_BUDGET_MUST_BE_ALIGNED', '2': 38},
    {'1': 'BIDDING_STRATEGY_AND_BUDGET_MUST_BE_ATTACHED_TO_THE_SAME_CAMPAIGNS_TO_ALIGN', '2': 39},
    {'1': 'BIDDING_STRATEGY_AND_BUDGET_MUST_BE_REMOVED_TOGETHER', '2': 40},
    {'1': 'CPC_BID_FLOOR_MICROS_GREATER_THAN_CPC_BID_CEILING_MICROS', '2': 41},
  ],
};

/// Descriptor for `BiddingErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List biddingErrorEnumDescriptor = $convert.base64Decode(
    'ChBCaWRkaW5nRXJyb3JFbnVtIr4JCgxCaWRkaW5nRXJyb3ISDwoLVU5TUEVDSUZJRUQQABILCg'
    'dVTktOT1dOEAESKwonQklERElOR19TVFJBVEVHWV9UUkFOU0lUSU9OX05PVF9BTExPV0VEEAIS'
    'LgoqQ0FOTk9UX0FUVEFDSF9CSURESU5HX1NUUkFURUdZX1RPX0NBTVBBSUdOEAcSKwonSU5WQU'
    'xJRF9BTk9OWU1PVVNfQklERElOR19TVFJBVEVHWV9UWVBFEAoSIQodSU5WQUxJRF9CSURESU5H'
    'X1NUUkFURUdZX1RZUEUQDhIPCgtJTlZBTElEX0JJRBAREjMKL0JJRERJTkdfU1RSQVRFR1lfTk'
    '9UX0FWQUlMQUJMRV9GT1JfQUNDT1VOVF9UWVBFEBISMAosQ0FOTk9UX0NSRUFURV9DQU1QQUlH'
    'Tl9XSVRIX0JJRERJTkdfU1RSQVRFR1kQFRJPCktDQU5OT1RfVEFSR0VUX0NPTlRFTlRfTkVUV0'
    '9SS19PTkxZX1dJVEhfQ0FNUEFJR05fTEVWRUxfUE9QX0JJRERJTkdfU1RSQVRFR1kQFxIzCi9C'
    'SURESU5HX1NUUkFURUdZX05PVF9TVVBQT1JURURfV0lUSF9BRF9TQ0hFRFVMRRAYEjEKLVBBWV'
    '9QRVJfQ09OVkVSU0lPTl9OT1RfQVZBSUxBQkxFX0ZPUl9DVVNUT01FUhAZEjIKLlBBWV9QRVJf'
    'Q09OVkVSU0lPTl9OT1RfQUxMT1dFRF9XSVRIX1RBUkdFVF9DUEEQGhI6CjZCSURESU5HX1NUUk'
    'FURUdZX05PVF9BTExPV0VEX0ZPUl9TRUFSQ0hfT05MWV9DQU1QQUlHTlMQGxI7CjdCSURESU5H'
    'X1NUUkFURUdZX05PVF9TVVBQT1JURURfSU5fRFJBRlRTX09SX0VYUEVSSU1FTlRTEBwSSQpFQk'
    'lERElOR19TVFJBVEVHWV9UWVBFX0RPRVNfTk9UX1NVUFBPUlRfUFJPRFVDVF9UWVBFX0FER1JP'
    'VVBfQ1JJVEVSSU9OEB0SEQoNQklEX1RPT19TTUFMTBAeEg8KC0JJRF9UT09fQklHEB8SIgoeQk'
    'lEX1RPT19NQU5ZX0ZSQUNUSU9OQUxfRElHSVRTECASFwoTSU5WQUxJRF9ET01BSU5fTkFNRRAh'
    'EiQKIE5PVF9DT01QQVRJQkxFX1dJVEhfUEFZTUVOVF9NT0RFECISOQo1QklERElOR19TVFJBVE'
    'VHWV9UWVBFX0lOQ09NUEFUSUJMRV9XSVRIX1NIQVJFRF9CVURHRVQQJRIvCitCSURESU5HX1NU'
    'UkFURUdZX0FORF9CVURHRVRfTVVTVF9CRV9BTElHTkVEECYSTwpLQklERElOR19TVFJBVEVHWV'
    '9BTkRfQlVER0VUX01VU1RfQkVfQVRUQUNIRURfVE9fVEhFX1NBTUVfQ0FNUEFJR05TX1RPX0FM'
    'SUdOECcSOAo0QklERElOR19TVFJBVEVHWV9BTkRfQlVER0VUX01VU1RfQkVfUkVNT1ZFRF9UT0'
    'dFVEhFUhAoEjwKOENQQ19CSURfRkxPT1JfTUlDUk9TX0dSRUFURVJfVEhBTl9DUENfQklEX0NF'
    'SUxJTkdfTUlDUk9TECk=');

