//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v17/errors/conversion_upload_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use conversionUploadErrorEnumDescriptor instead')
const ConversionUploadErrorEnum$json = {
  '1': 'ConversionUploadErrorEnum',
  '4': [ConversionUploadErrorEnum_ConversionUploadError$json],
};

@$core.Deprecated('Use conversionUploadErrorEnumDescriptor instead')
const ConversionUploadErrorEnum_ConversionUploadError$json = {
  '1': 'ConversionUploadError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'TOO_MANY_CONVERSIONS_IN_REQUEST', '2': 2},
    {'1': 'UNPARSEABLE_GCLID', '2': 3},
    {'1': 'CONVERSION_PRECEDES_EVENT', '2': 42},
    {'1': 'EXPIRED_EVENT', '2': 43},
    {'1': 'TOO_RECENT_EVENT', '2': 44},
    {'1': 'EVENT_NOT_FOUND', '2': 45},
    {'1': 'UNAUTHORIZED_CUSTOMER', '2': 8},
    {'1': 'TOO_RECENT_CONVERSION_ACTION', '2': 10},
    {'1': 'CONVERSION_TRACKING_NOT_ENABLED_AT_IMPRESSION_TIME', '2': 11},
    {'1': 'EXTERNAL_ATTRIBUTION_DATA_SET_FOR_NON_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION', '2': 12},
    {'1': 'EXTERNAL_ATTRIBUTION_DATA_NOT_SET_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION', '2': 13},
    {'1': 'ORDER_ID_NOT_PERMITTED_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION', '2': 14},
    {'1': 'ORDER_ID_ALREADY_IN_USE', '2': 15},
    {'1': 'DUPLICATE_ORDER_ID', '2': 16},
    {'1': 'TOO_RECENT_CALL', '2': 17},
    {'1': 'EXPIRED_CALL', '2': 18},
    {'1': 'CALL_NOT_FOUND', '2': 19},
    {'1': 'CONVERSION_PRECEDES_CALL', '2': 20},
    {'1': 'CONVERSION_TRACKING_NOT_ENABLED_AT_CALL_TIME', '2': 21},
    {'1': 'UNPARSEABLE_CALLERS_PHONE_NUMBER', '2': 22},
    {'1': 'CLICK_CONVERSION_ALREADY_EXISTS', '2': 23},
    {'1': 'CALL_CONVERSION_ALREADY_EXISTS', '2': 24},
    {'1': 'DUPLICATE_CLICK_CONVERSION_IN_REQUEST', '2': 25},
    {'1': 'DUPLICATE_CALL_CONVERSION_IN_REQUEST', '2': 26},
    {'1': 'CUSTOM_VARIABLE_NOT_ENABLED', '2': 28},
    {'1': 'CUSTOM_VARIABLE_VALUE_CONTAINS_PII', '2': 29},
    {'1': 'INVALID_CUSTOMER_FOR_CLICK', '2': 30},
    {'1': 'INVALID_CUSTOMER_FOR_CALL', '2': 31},
    {'1': 'CONVERSION_NOT_COMPLIANT_WITH_ATT_POLICY', '2': 32},
    {'1': 'CLICK_NOT_FOUND', '2': 33},
    {'1': 'INVALID_USER_IDENTIFIER', '2': 34},
    {'1': 'EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION_NOT_PERMITTED_WITH_USER_IDENTIFIER', '2': 35},
    {'1': 'UNSUPPORTED_USER_IDENTIFIER', '2': 36},
    {'1': 'GBRAID_WBRAID_BOTH_SET', '2': 38},
    {'1': 'UNPARSEABLE_WBRAID', '2': 39},
    {'1': 'UNPARSEABLE_GBRAID', '2': 40},
    {'1': 'ONE_PER_CLICK_CONVERSION_ACTION_NOT_PERMITTED_WITH_BRAID', '2': 46},
    {'1': 'CUSTOMER_DATA_POLICY_PROHIBITS_ENHANCED_CONVERSIONS', '2': 47},
    {'1': 'CUSTOMER_NOT_ACCEPTED_CUSTOMER_DATA_TERMS', '2': 48},
    {'1': 'ORDER_ID_CONTAINS_PII', '2': 49},
    {'1': 'CUSTOMER_NOT_ENABLED_ENHANCED_CONVERSIONS_FOR_LEADS', '2': 50},
    {'1': 'INVALID_JOB_ID', '2': 52},
    {'1': 'NO_CONVERSION_ACTION_FOUND', '2': 53},
    {'1': 'INVALID_CONVERSION_ACTION_TYPE', '2': 54},
  ],
};

/// Descriptor for `ConversionUploadErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List conversionUploadErrorEnumDescriptor = $convert.base64Decode(
    'ChlDb252ZXJzaW9uVXBsb2FkRXJyb3JFbnVtIqwNChVDb252ZXJzaW9uVXBsb2FkRXJyb3ISDw'
    'oLVU5TUEVDSUZJRUQQABILCgdVTktOT1dOEAESIwofVE9PX01BTllfQ09OVkVSU0lPTlNfSU5f'
    'UkVRVUVTVBACEhUKEVVOUEFSU0VBQkxFX0dDTElEEAMSHQoZQ09OVkVSU0lPTl9QUkVDRURFU1'
    '9FVkVOVBAqEhEKDUVYUElSRURfRVZFTlQQKxIUChBUT09fUkVDRU5UX0VWRU5UECwSEwoPRVZF'
    'TlRfTk9UX0ZPVU5EEC0SGQoVVU5BVVRIT1JJWkVEX0NVU1RPTUVSEAgSIAocVE9PX1JFQ0VOVF'
    '9DT05WRVJTSU9OX0FDVElPThAKEjYKMkNPTlZFUlNJT05fVFJBQ0tJTkdfTk9UX0VOQUJMRURf'
    'QVRfSU1QUkVTU0lPTl9USU1FEAsSUQpNRVhURVJOQUxfQVRUUklCVVRJT05fREFUQV9TRVRfRk'
    '9SX05PTl9FWFRFUk5BTExZX0FUVFJJQlVURURfQ09OVkVSU0lPTl9BQ1RJT04QDBJRCk1FWFRF'
    'Uk5BTF9BVFRSSUJVVElPTl9EQVRBX05PVF9TRVRfRk9SX0VYVEVSTkFMTFlfQVRUUklCVVRFRF'
    '9DT05WRVJTSU9OX0FDVElPThANEkYKQk9SREVSX0lEX05PVF9QRVJNSVRURURfRk9SX0VYVEVS'
    'TkFMTFlfQVRUUklCVVRFRF9DT05WRVJTSU9OX0FDVElPThAOEhsKF09SREVSX0lEX0FMUkVBRF'
    'lfSU5fVVNFEA8SFgoSRFVQTElDQVRFX09SREVSX0lEEBASEwoPVE9PX1JFQ0VOVF9DQUxMEBES'
    'EAoMRVhQSVJFRF9DQUxMEBISEgoOQ0FMTF9OT1RfRk9VTkQQExIcChhDT05WRVJTSU9OX1BSRU'
    'NFREVTX0NBTEwQFBIwCixDT05WRVJTSU9OX1RSQUNLSU5HX05PVF9FTkFCTEVEX0FUX0NBTExf'
    'VElNRRAVEiQKIFVOUEFSU0VBQkxFX0NBTExFUlNfUEhPTkVfTlVNQkVSEBYSIwofQ0xJQ0tfQ0'
    '9OVkVSU0lPTl9BTFJFQURZX0VYSVNUUxAXEiIKHkNBTExfQ09OVkVSU0lPTl9BTFJFQURZX0VY'
    'SVNUUxAYEikKJURVUExJQ0FURV9DTElDS19DT05WRVJTSU9OX0lOX1JFUVVFU1QQGRIoCiREVV'
    'BMSUNBVEVfQ0FMTF9DT05WRVJTSU9OX0lOX1JFUVVFU1QQGhIfChtDVVNUT01fVkFSSUFCTEVf'
    'Tk9UX0VOQUJMRUQQHBImCiJDVVNUT01fVkFSSUFCTEVfVkFMVUVfQ09OVEFJTlNfUElJEB0SHg'
    'oaSU5WQUxJRF9DVVNUT01FUl9GT1JfQ0xJQ0sQHhIdChlJTlZBTElEX0NVU1RPTUVSX0ZPUl9D'
    'QUxMEB8SLAooQ09OVkVSU0lPTl9OT1RfQ09NUExJQU5UX1dJVEhfQVRUX1BPTElDWRAgEhMKD0'
    'NMSUNLX05PVF9GT1VORBAhEhsKF0lOVkFMSURfVVNFUl9JREVOVElGSUVSECISTgpKRVhURVJO'
    'QUxMWV9BVFRSSUJVVEVEX0NPTlZFUlNJT05fQUNUSU9OX05PVF9QRVJNSVRURURfV0lUSF9VU0'
    'VSX0lERU5USUZJRVIQIxIfChtVTlNVUFBPUlRFRF9VU0VSX0lERU5USUZJRVIQJBIaChZHQlJB'
    'SURfV0JSQUlEX0JPVEhfU0VUECYSFgoSVU5QQVJTRUFCTEVfV0JSQUlEECcSFgoSVU5QQVJTRU'
    'FCTEVfR0JSQUlEECgSPAo4T05FX1BFUl9DTElDS19DT05WRVJTSU9OX0FDVElPTl9OT1RfUEVS'
    'TUlUVEVEX1dJVEhfQlJBSUQQLhI3CjNDVVNUT01FUl9EQVRBX1BPTElDWV9QUk9ISUJJVFNfRU'
    '5IQU5DRURfQ09OVkVSU0lPTlMQLxItCilDVVNUT01FUl9OT1RfQUNDRVBURURfQ1VTVE9NRVJf'
    'REFUQV9URVJNUxAwEhkKFU9SREVSX0lEX0NPTlRBSU5TX1BJSRAxEjcKM0NVU1RPTUVSX05PVF'
    '9FTkFCTEVEX0VOSEFOQ0VEX0NPTlZFUlNJT05TX0ZPUl9MRUFEUxAyEhIKDklOVkFMSURfSk9C'
    'X0lEEDQSHgoaTk9fQ09OVkVSU0lPTl9BQ1RJT05fRk9VTkQQNRIiCh5JTlZBTElEX0NPTlZFUl'
    'NJT05fQUNUSU9OX1RZUEUQNg==');

