//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v17/errors/query_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use queryErrorEnumDescriptor instead')
const QueryErrorEnum$json = {
  '1': 'QueryErrorEnum',
  '4': [QueryErrorEnum_QueryError$json],
};

@$core.Deprecated('Use queryErrorEnumDescriptor instead')
const QueryErrorEnum_QueryError$json = {
  '1': 'QueryError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'QUERY_ERROR', '2': 50},
    {'1': 'BAD_ENUM_CONSTANT', '2': 18},
    {'1': 'BAD_ESCAPE_SEQUENCE', '2': 7},
    {'1': 'BAD_FIELD_NAME', '2': 12},
    {'1': 'BAD_LIMIT_VALUE', '2': 15},
    {'1': 'BAD_NUMBER', '2': 5},
    {'1': 'BAD_OPERATOR', '2': 3},
    {'1': 'BAD_PARAMETER_NAME', '2': 61},
    {'1': 'BAD_PARAMETER_VALUE', '2': 62},
    {'1': 'BAD_RESOURCE_TYPE_IN_FROM_CLAUSE', '2': 45},
    {'1': 'BAD_SYMBOL', '2': 2},
    {'1': 'BAD_VALUE', '2': 4},
    {'1': 'DATE_RANGE_TOO_WIDE', '2': 36},
    {'1': 'DATE_RANGE_TOO_NARROW', '2': 60},
    {'1': 'EXPECTED_AND', '2': 30},
    {'1': 'EXPECTED_BY', '2': 14},
    {'1': 'EXPECTED_DIMENSION_FIELD_IN_SELECT_CLAUSE', '2': 37},
    {'1': 'EXPECTED_FILTERS_ON_DATE_RANGE', '2': 55},
    {'1': 'EXPECTED_FROM', '2': 44},
    {'1': 'EXPECTED_LIST', '2': 41},
    {'1': 'EXPECTED_REFERENCED_FIELD_IN_SELECT_CLAUSE', '2': 16},
    {'1': 'EXPECTED_SELECT', '2': 13},
    {'1': 'EXPECTED_SINGLE_VALUE', '2': 42},
    {'1': 'EXPECTED_VALUE_WITH_BETWEEN_OPERATOR', '2': 29},
    {'1': 'INVALID_DATE_FORMAT', '2': 38},
    {'1': 'MISALIGNED_DATE_FOR_FILTER', '2': 64},
    {'1': 'INVALID_STRING_VALUE', '2': 57},
    {'1': 'INVALID_VALUE_WITH_BETWEEN_OPERATOR', '2': 26},
    {'1': 'INVALID_VALUE_WITH_DURING_OPERATOR', '2': 22},
    {'1': 'INVALID_VALUE_WITH_LIKE_OPERATOR', '2': 56},
    {'1': 'OPERATOR_FIELD_MISMATCH', '2': 35},
    {'1': 'PROHIBITED_EMPTY_LIST_IN_CONDITION', '2': 28},
    {'1': 'PROHIBITED_ENUM_CONSTANT', '2': 54},
    {'1': 'PROHIBITED_FIELD_COMBINATION_IN_SELECT_CLAUSE', '2': 31},
    {'1': 'PROHIBITED_FIELD_IN_ORDER_BY_CLAUSE', '2': 40},
    {'1': 'PROHIBITED_FIELD_IN_SELECT_CLAUSE', '2': 23},
    {'1': 'PROHIBITED_FIELD_IN_WHERE_CLAUSE', '2': 24},
    {'1': 'PROHIBITED_RESOURCE_TYPE_IN_FROM_CLAUSE', '2': 43},
    {'1': 'PROHIBITED_RESOURCE_TYPE_IN_SELECT_CLAUSE', '2': 48},
    {'1': 'PROHIBITED_RESOURCE_TYPE_IN_WHERE_CLAUSE', '2': 58},
    {'1': 'PROHIBITED_METRIC_IN_SELECT_OR_WHERE_CLAUSE', '2': 49},
    {'1': 'PROHIBITED_SEGMENT_IN_SELECT_OR_WHERE_CLAUSE', '2': 51},
    {'1': 'PROHIBITED_SEGMENT_WITH_METRIC_IN_SELECT_OR_WHERE_CLAUSE', '2': 53},
    {'1': 'LIMIT_VALUE_TOO_LOW', '2': 25},
    {'1': 'PROHIBITED_NEWLINE_IN_STRING', '2': 8},
    {'1': 'PROHIBITED_VALUE_COMBINATION_IN_LIST', '2': 10},
    {'1': 'PROHIBITED_VALUE_COMBINATION_WITH_BETWEEN_OPERATOR', '2': 21},
    {'1': 'STRING_NOT_TERMINATED', '2': 6},
    {'1': 'TOO_MANY_SEGMENTS', '2': 34},
    {'1': 'UNEXPECTED_END_OF_QUERY', '2': 9},
    {'1': 'UNEXPECTED_FROM_CLAUSE', '2': 47},
    {'1': 'UNRECOGNIZED_FIELD', '2': 32},
    {'1': 'UNEXPECTED_INPUT', '2': 11},
    {'1': 'REQUESTED_METRICS_FOR_MANAGER', '2': 59},
    {'1': 'FILTER_HAS_TOO_MANY_VALUES', '2': 63},
  ],
};

/// Descriptor for `QueryErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List queryErrorEnumDescriptor = $convert.base64Decode(
    'Cg5RdWVyeUVycm9yRW51bSKADgoKUXVlcnlFcnJvchIPCgtVTlNQRUNJRklFRBAAEgsKB1VOS0'
    '5PV04QARIPCgtRVUVSWV9FUlJPUhAyEhUKEUJBRF9FTlVNX0NPTlNUQU5UEBISFwoTQkFEX0VT'
    'Q0FQRV9TRVFVRU5DRRAHEhIKDkJBRF9GSUVMRF9OQU1FEAwSEwoPQkFEX0xJTUlUX1ZBTFVFEA'
    '8SDgoKQkFEX05VTUJFUhAFEhAKDEJBRF9PUEVSQVRPUhADEhYKEkJBRF9QQVJBTUVURVJfTkFN'
    'RRA9EhcKE0JBRF9QQVJBTUVURVJfVkFMVUUQPhIkCiBCQURfUkVTT1VSQ0VfVFlQRV9JTl9GUk'
    '9NX0NMQVVTRRAtEg4KCkJBRF9TWU1CT0wQAhINCglCQURfVkFMVUUQBBIXChNEQVRFX1JBTkdF'
    'X1RPT19XSURFECQSGQoVREFURV9SQU5HRV9UT09fTkFSUk9XEDwSEAoMRVhQRUNURURfQU5EEB'
    '4SDwoLRVhQRUNURURfQlkQDhItCilFWFBFQ1RFRF9ESU1FTlNJT05fRklFTERfSU5fU0VMRUNU'
    'X0NMQVVTRRAlEiIKHkVYUEVDVEVEX0ZJTFRFUlNfT05fREFURV9SQU5HRRA3EhEKDUVYUEVDVE'
    'VEX0ZST00QLBIRCg1FWFBFQ1RFRF9MSVNUECkSLgoqRVhQRUNURURfUkVGRVJFTkNFRF9GSUVM'
    'RF9JTl9TRUxFQ1RfQ0xBVVNFEBASEwoPRVhQRUNURURfU0VMRUNUEA0SGQoVRVhQRUNURURfU0'
    'lOR0xFX1ZBTFVFECoSKAokRVhQRUNURURfVkFMVUVfV0lUSF9CRVRXRUVOX09QRVJBVE9SEB0S'
    'FwoTSU5WQUxJRF9EQVRFX0ZPUk1BVBAmEh4KGk1JU0FMSUdORURfREFURV9GT1JfRklMVEVSEE'
    'ASGAoUSU5WQUxJRF9TVFJJTkdfVkFMVUUQORInCiNJTlZBTElEX1ZBTFVFX1dJVEhfQkVUV0VF'
    'Tl9PUEVSQVRPUhAaEiYKIklOVkFMSURfVkFMVUVfV0lUSF9EVVJJTkdfT1BFUkFUT1IQFhIkCi'
    'BJTlZBTElEX1ZBTFVFX1dJVEhfTElLRV9PUEVSQVRPUhA4EhsKF09QRVJBVE9SX0ZJRUxEX01J'
    'U01BVENIECMSJgoiUFJPSElCSVRFRF9FTVBUWV9MSVNUX0lOX0NPTkRJVElPThAcEhwKGFBST0'
    'hJQklURURfRU5VTV9DT05TVEFOVBA2EjEKLVBST0hJQklURURfRklFTERfQ09NQklOQVRJT05f'
    'SU5fU0VMRUNUX0NMQVVTRRAfEicKI1BST0hJQklURURfRklFTERfSU5fT1JERVJfQllfQ0xBVV'
    'NFECgSJQohUFJPSElCSVRFRF9GSUVMRF9JTl9TRUxFQ1RfQ0xBVVNFEBcSJAogUFJPSElCSVRF'
    'RF9GSUVMRF9JTl9XSEVSRV9DTEFVU0UQGBIrCidQUk9ISUJJVEVEX1JFU09VUkNFX1RZUEVfSU'
    '5fRlJPTV9DTEFVU0UQKxItCilQUk9ISUJJVEVEX1JFU09VUkNFX1RZUEVfSU5fU0VMRUNUX0NM'
    'QVVTRRAwEiwKKFBST0hJQklURURfUkVTT1VSQ0VfVFlQRV9JTl9XSEVSRV9DTEFVU0UQOhIvCi'
    'tQUk9ISUJJVEVEX01FVFJJQ19JTl9TRUxFQ1RfT1JfV0hFUkVfQ0xBVVNFEDESMAosUFJPSElC'
    'SVRFRF9TRUdNRU5UX0lOX1NFTEVDVF9PUl9XSEVSRV9DTEFVU0UQMxI8CjhQUk9ISUJJVEVEX1'
    'NFR01FTlRfV0lUSF9NRVRSSUNfSU5fU0VMRUNUX09SX1dIRVJFX0NMQVVTRRA1EhcKE0xJTUlU'
    'X1ZBTFVFX1RPT19MT1cQGRIgChxQUk9ISUJJVEVEX05FV0xJTkVfSU5fU1RSSU5HEAgSKAokUF'
    'JPSElCSVRFRF9WQUxVRV9DT01CSU5BVElPTl9JTl9MSVNUEAoSNgoyUFJPSElCSVRFRF9WQUxV'
    'RV9DT01CSU5BVElPTl9XSVRIX0JFVFdFRU5fT1BFUkFUT1IQFRIZChVTVFJJTkdfTk9UX1RFUk'
    '1JTkFURUQQBhIVChFUT09fTUFOWV9TRUdNRU5UUxAiEhsKF1VORVhQRUNURURfRU5EX09GX1FV'
    'RVJZEAkSGgoWVU5FWFBFQ1RFRF9GUk9NX0NMQVVTRRAvEhYKElVOUkVDT0dOSVpFRF9GSUVMRB'
    'AgEhQKEFVORVhQRUNURURfSU5QVVQQCxIhCh1SRVFVRVNURURfTUVUUklDU19GT1JfTUFOQUdF'
    'UhA7Eh4KGkZJTFRFUl9IQVNfVE9PX01BTllfVkFMVUVTED8=');

