//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v17/errors/user_list_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use userListErrorEnumDescriptor instead')
const UserListErrorEnum$json = {
  '1': 'UserListErrorEnum',
  '4': [UserListErrorEnum_UserListError$json],
};

@$core.Deprecated('Use userListErrorEnumDescriptor instead')
const UserListErrorEnum_UserListError$json = {
  '1': 'UserListError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'EXTERNAL_REMARKETING_USER_LIST_MUTATE_NOT_SUPPORTED', '2': 2},
    {'1': 'CONCRETE_TYPE_REQUIRED', '2': 3},
    {'1': 'CONVERSION_TYPE_ID_REQUIRED', '2': 4},
    {'1': 'DUPLICATE_CONVERSION_TYPES', '2': 5},
    {'1': 'INVALID_CONVERSION_TYPE', '2': 6},
    {'1': 'INVALID_DESCRIPTION', '2': 7},
    {'1': 'INVALID_NAME', '2': 8},
    {'1': 'INVALID_TYPE', '2': 9},
    {'1': 'CAN_NOT_ADD_LOGICAL_LIST_AS_LOGICAL_LIST_OPERAND', '2': 10},
    {'1': 'INVALID_USER_LIST_LOGICAL_RULE_OPERAND', '2': 11},
    {'1': 'NAME_ALREADY_USED', '2': 12},
    {'1': 'NEW_CONVERSION_TYPE_NAME_REQUIRED', '2': 13},
    {'1': 'CONVERSION_TYPE_NAME_ALREADY_USED', '2': 14},
    {'1': 'OWNERSHIP_REQUIRED_FOR_SET', '2': 15},
    {'1': 'USER_LIST_MUTATE_NOT_SUPPORTED', '2': 16},
    {'1': 'INVALID_RULE', '2': 17},
    {'1': 'INVALID_DATE_RANGE', '2': 27},
    {'1': 'CAN_NOT_MUTATE_SENSITIVE_USERLIST', '2': 28},
    {'1': 'MAX_NUM_RULEBASED_USERLISTS', '2': 29},
    {'1': 'CANNOT_MODIFY_BILLABLE_RECORD_COUNT', '2': 30},
    {'1': 'APP_ID_NOT_SET', '2': 31},
    {'1': 'USERLIST_NAME_IS_RESERVED_FOR_SYSTEM_LIST', '2': 32},
    {'1': 'ADVERTISER_NOT_ON_ALLOWLIST_FOR_USING_UPLOADED_DATA', '2': 37},
    {'1': 'RULE_TYPE_IS_NOT_SUPPORTED', '2': 34},
    {'1': 'CAN_NOT_ADD_A_SIMILAR_USERLIST_AS_LOGICAL_LIST_OPERAND', '2': 35},
    {'1': 'CAN_NOT_MIX_CRM_BASED_IN_LOGICAL_LIST_WITH_OTHER_LISTS', '2': 36},
    {'1': 'APP_ID_NOT_ALLOWED', '2': 39},
    {'1': 'CANNOT_MUTATE_SYSTEM_LIST', '2': 40},
    {'1': 'MOBILE_APP_IS_SENSITIVE', '2': 41},
    {'1': 'SEED_LIST_DOES_NOT_EXIST', '2': 42},
    {'1': 'INVALID_SEED_LIST_ACCESS_REASON', '2': 43},
    {'1': 'INVALID_SEED_LIST_TYPE', '2': 44},
    {'1': 'INVALID_COUNTRY_CODES', '2': 45},
  ],
};

/// Descriptor for `UserListErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List userListErrorEnumDescriptor = $convert.base64Decode(
    'ChFVc2VyTGlzdEVycm9yRW51bSKlCQoNVXNlckxpc3RFcnJvchIPCgtVTlNQRUNJRklFRBAAEg'
    'sKB1VOS05PV04QARI3CjNFWFRFUk5BTF9SRU1BUktFVElOR19VU0VSX0xJU1RfTVVUQVRFX05P'
    'VF9TVVBQT1JURUQQAhIaChZDT05DUkVURV9UWVBFX1JFUVVJUkVEEAMSHwobQ09OVkVSU0lPTl'
    '9UWVBFX0lEX1JFUVVJUkVEEAQSHgoaRFVQTElDQVRFX0NPTlZFUlNJT05fVFlQRVMQBRIbChdJ'
    'TlZBTElEX0NPTlZFUlNJT05fVFlQRRAGEhcKE0lOVkFMSURfREVTQ1JJUFRJT04QBxIQCgxJTl'
    'ZBTElEX05BTUUQCBIQCgxJTlZBTElEX1RZUEUQCRI0CjBDQU5fTk9UX0FERF9MT0dJQ0FMX0xJ'
    'U1RfQVNfTE9HSUNBTF9MSVNUX09QRVJBTkQQChIqCiZJTlZBTElEX1VTRVJfTElTVF9MT0dJQ0'
    'FMX1JVTEVfT1BFUkFORBALEhUKEU5BTUVfQUxSRUFEWV9VU0VEEAwSJQohTkVXX0NPTlZFUlNJ'
    'T05fVFlQRV9OQU1FX1JFUVVJUkVEEA0SJQohQ09OVkVSU0lPTl9UWVBFX05BTUVfQUxSRUFEWV'
    '9VU0VEEA4SHgoaT1dORVJTSElQX1JFUVVJUkVEX0ZPUl9TRVQQDxIiCh5VU0VSX0xJU1RfTVVU'
    'QVRFX05PVF9TVVBQT1JURUQQEBIQCgxJTlZBTElEX1JVTEUQERIWChJJTlZBTElEX0RBVEVfUk'
    'FOR0UQGxIlCiFDQU5fTk9UX01VVEFURV9TRU5TSVRJVkVfVVNFUkxJU1QQHBIfChtNQVhfTlVN'
    'X1JVTEVCQVNFRF9VU0VSTElTVFMQHRInCiNDQU5OT1RfTU9ESUZZX0JJTExBQkxFX1JFQ09SRF'
    '9DT1VOVBAeEhIKDkFQUF9JRF9OT1RfU0VUEB8SLQopVVNFUkxJU1RfTkFNRV9JU19SRVNFUlZF'
    'RF9GT1JfU1lTVEVNX0xJU1QQIBI3CjNBRFZFUlRJU0VSX05PVF9PTl9BTExPV0xJU1RfRk9SX1'
    'VTSU5HX1VQTE9BREVEX0RBVEEQJRIeChpSVUxFX1RZUEVfSVNfTk9UX1NVUFBPUlRFRBAiEjoK'
    'NkNBTl9OT1RfQUREX0FfU0lNSUxBUl9VU0VSTElTVF9BU19MT0dJQ0FMX0xJU1RfT1BFUkFORB'
    'AjEjoKNkNBTl9OT1RfTUlYX0NSTV9CQVNFRF9JTl9MT0dJQ0FMX0xJU1RfV0lUSF9PVEhFUl9M'
    'SVNUUxAkEhYKEkFQUF9JRF9OT1RfQUxMT1dFRBAnEh0KGUNBTk5PVF9NVVRBVEVfU1lTVEVNX0'
    'xJU1QQKBIbChdNT0JJTEVfQVBQX0lTX1NFTlNJVElWRRApEhwKGFNFRURfTElTVF9ET0VTX05P'
    'VF9FWElTVBAqEiMKH0lOVkFMSURfU0VFRF9MSVNUX0FDQ0VTU19SRUFTT04QKxIaChZJTlZBTE'
    'lEX1NFRURfTElTVF9UWVBFECwSGQoVSU5WQUxJRF9DT1VOVFJZX0NPREVTEC0=');

