//
//  Generated code. Do not modify.
//  source: google/cloud/talent/v4/event.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:core' as $core;

import 'package:protobuf/protobuf.dart' as $pb;

import '../../../protobuf/timestamp.pb.dart' as $1776;
import 'event.pbenum.dart';

export 'event.pbenum.dart';

enum ClientEvent_Event {
  jobEvent, 
  notSet
}

/// An event issued when an end user interacts with the application that
/// implements Cloud Talent Solution. Providing this information improves the
/// quality of results for the API clients, enabling the
/// service to perform optimally. The number of events sent must be consistent
/// with other calls, such as job searches, issued to the service by the client.
class ClientEvent extends $pb.GeneratedMessage {
  factory ClientEvent({
    $core.String? requestId,
    $core.String? eventId,
    $1776.Timestamp? createTime,
    JobEvent? jobEvent,
    $core.String? eventNotes,
  }) {
    final $result = create();
    if (requestId != null) {
      $result.requestId = requestId;
    }
    if (eventId != null) {
      $result.eventId = eventId;
    }
    if (createTime != null) {
      $result.createTime = createTime;
    }
    if (jobEvent != null) {
      $result.jobEvent = jobEvent;
    }
    if (eventNotes != null) {
      $result.eventNotes = eventNotes;
    }
    return $result;
  }
  ClientEvent._() : super();
  factory ClientEvent.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory ClientEvent.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static const $core.Map<$core.int, ClientEvent_Event> _ClientEvent_EventByTag = {
    5 : ClientEvent_Event.jobEvent,
    0 : ClientEvent_Event.notSet
  };
  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'ClientEvent', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.talent.v4'), createEmptyInstance: create)
    ..oo(0, [5])
    ..aOS(1, _omitFieldNames ? '' : 'requestId')
    ..aOS(2, _omitFieldNames ? '' : 'eventId')
    ..aOM<$1776.Timestamp>(4, _omitFieldNames ? '' : 'createTime', subBuilder: $1776.Timestamp.create)
    ..aOM<JobEvent>(5, _omitFieldNames ? '' : 'jobEvent', subBuilder: JobEvent.create)
    ..aOS(9, _omitFieldNames ? '' : 'eventNotes')
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  ClientEvent clone() => ClientEvent()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  ClientEvent copyWith(void Function(ClientEvent) updates) => super.copyWith((message) => updates(message as ClientEvent)) as ClientEvent;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static ClientEvent create() => ClientEvent._();
  ClientEvent createEmptyInstance() => create();
  static $pb.PbList<ClientEvent> createRepeated() => $pb.PbList<ClientEvent>();
  @$core.pragma('dart2js:noInline')
  static ClientEvent getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<ClientEvent>(create);
  static ClientEvent? _defaultInstance;

  ClientEvent_Event whichEvent() => _ClientEvent_EventByTag[$_whichOneof(0)]!;
  void clearEvent() => clearField($_whichOneof(0));

  ///  Strongly recommended for the best service experience.
  ///
  ///  A unique ID generated in the API responses. It can be found in
  ///  [ResponseMetadata.request_id][google.cloud.talent.v4.ResponseMetadata.request_id].
  @$pb.TagNumber(1)
  $core.String get requestId => $_getSZ(0);
  @$pb.TagNumber(1)
  set requestId($core.String v) { $_setString(0, v); }
  @$pb.TagNumber(1)
  $core.bool hasRequestId() => $_has(0);
  @$pb.TagNumber(1)
  void clearRequestId() => clearField(1);

  /// Required. A unique identifier, generated by the client application.
  @$pb.TagNumber(2)
  $core.String get eventId => $_getSZ(1);
  @$pb.TagNumber(2)
  set eventId($core.String v) { $_setString(1, v); }
  @$pb.TagNumber(2)
  $core.bool hasEventId() => $_has(1);
  @$pb.TagNumber(2)
  void clearEventId() => clearField(2);

  /// Required. The timestamp of the event.
  @$pb.TagNumber(4)
  $1776.Timestamp get createTime => $_getN(2);
  @$pb.TagNumber(4)
  set createTime($1776.Timestamp v) { setField(4, v); }
  @$pb.TagNumber(4)
  $core.bool hasCreateTime() => $_has(2);
  @$pb.TagNumber(4)
  void clearCreateTime() => clearField(4);
  @$pb.TagNumber(4)
  $1776.Timestamp ensureCreateTime() => $_ensure(2);

  /// An event issued when a job seeker interacts with the application that
  /// implements Cloud Talent Solution.
  @$pb.TagNumber(5)
  JobEvent get jobEvent => $_getN(3);
  @$pb.TagNumber(5)
  set jobEvent(JobEvent v) { setField(5, v); }
  @$pb.TagNumber(5)
  $core.bool hasJobEvent() => $_has(3);
  @$pb.TagNumber(5)
  void clearJobEvent() => clearField(5);
  @$pb.TagNumber(5)
  JobEvent ensureJobEvent() => $_ensure(3);

  /// Notes about the event provided by recruiters or other users, for example,
  /// feedback on why a job was bookmarked.
  @$pb.TagNumber(9)
  $core.String get eventNotes => $_getSZ(4);
  @$pb.TagNumber(9)
  set eventNotes($core.String v) { $_setString(4, v); }
  @$pb.TagNumber(9)
  $core.bool hasEventNotes() => $_has(4);
  @$pb.TagNumber(9)
  void clearEventNotes() => clearField(9);
}

/// An event issued when a job seeker interacts with the application that
/// implements Cloud Talent Solution.
class JobEvent extends $pb.GeneratedMessage {
  factory JobEvent({
    JobEvent_JobEventType? type,
    $core.Iterable<$core.String>? jobs,
  }) {
    final $result = create();
    if (type != null) {
      $result.type = type;
    }
    if (jobs != null) {
      $result.jobs.addAll(jobs);
    }
    return $result;
  }
  JobEvent._() : super();
  factory JobEvent.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory JobEvent.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'JobEvent', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.talent.v4'), createEmptyInstance: create)
    ..e<JobEvent_JobEventType>(1, _omitFieldNames ? '' : 'type', $pb.PbFieldType.OE, defaultOrMaker: JobEvent_JobEventType.JOB_EVENT_TYPE_UNSPECIFIED, valueOf: JobEvent_JobEventType.valueOf, enumValues: JobEvent_JobEventType.values)
    ..pPS(2, _omitFieldNames ? '' : 'jobs')
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  JobEvent clone() => JobEvent()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  JobEvent copyWith(void Function(JobEvent) updates) => super.copyWith((message) => updates(message as JobEvent)) as JobEvent;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static JobEvent create() => JobEvent._();
  JobEvent createEmptyInstance() => create();
  static $pb.PbList<JobEvent> createRepeated() => $pb.PbList<JobEvent>();
  @$core.pragma('dart2js:noInline')
  static JobEvent getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<JobEvent>(create);
  static JobEvent? _defaultInstance;

  /// Required. The type of the event (see
  /// [JobEventType][google.cloud.talent.v4.JobEvent.JobEventType]).
  @$pb.TagNumber(1)
  JobEvent_JobEventType get type => $_getN(0);
  @$pb.TagNumber(1)
  set type(JobEvent_JobEventType v) { setField(1, v); }
  @$pb.TagNumber(1)
  $core.bool hasType() => $_has(0);
  @$pb.TagNumber(1)
  void clearType() => clearField(1);

  ///  Required. The [job name(s)][google.cloud.talent.v4.Job.name] associated
  ///  with this event. For example, if this is an
  ///  [impression][google.cloud.talent.v4.JobEvent.JobEventType.IMPRESSION]
  ///  event, this field contains the identifiers of all jobs shown to the job
  ///  seeker. If this was a
  ///  [view][google.cloud.talent.v4.JobEvent.JobEventType.VIEW] event, this field
  ///  contains the identifier of the viewed job.
  ///
  ///  The format is
  ///  "projects/{project_id}/tenants/{tenant_id}/jobs/{job_id}", for
  ///  example, "projects/foo/tenants/bar/jobs/baz".
  @$pb.TagNumber(2)
  $core.List<$core.String> get jobs => $_getList(1);
}


const _omitFieldNames = $core.bool.fromEnvironment('protobuf.omit_field_names');
const _omitMessageNames = $core.bool.fromEnvironment('protobuf.omit_message_names');
