//
//  Generated code. Do not modify.
//  source: google/cloud/pubsublite/v1/publisher.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:core' as $core;

import 'package:fixnum/fixnum.dart' as $fixnum;
import 'package:protobuf/protobuf.dart' as $pb;

import 'common.pb.dart' as $1214;

/// The first request that must be sent on a newly-opened stream.
class InitialPublishRequest extends $pb.GeneratedMessage {
  factory InitialPublishRequest({
    $core.String? topic,
    $fixnum.Int64? partition,
    $core.List<$core.int>? clientId,
  }) {
    final $result = create();
    if (topic != null) {
      $result.topic = topic;
    }
    if (partition != null) {
      $result.partition = partition;
    }
    if (clientId != null) {
      $result.clientId = clientId;
    }
    return $result;
  }
  InitialPublishRequest._() : super();
  factory InitialPublishRequest.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory InitialPublishRequest.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'InitialPublishRequest', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.pubsublite.v1'), createEmptyInstance: create)
    ..aOS(1, _omitFieldNames ? '' : 'topic')
    ..aInt64(2, _omitFieldNames ? '' : 'partition')
    ..a<$core.List<$core.int>>(3, _omitFieldNames ? '' : 'clientId', $pb.PbFieldType.OY)
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  InitialPublishRequest clone() => InitialPublishRequest()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  InitialPublishRequest copyWith(void Function(InitialPublishRequest) updates) => super.copyWith((message) => updates(message as InitialPublishRequest)) as InitialPublishRequest;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static InitialPublishRequest create() => InitialPublishRequest._();
  InitialPublishRequest createEmptyInstance() => create();
  static $pb.PbList<InitialPublishRequest> createRepeated() => $pb.PbList<InitialPublishRequest>();
  @$core.pragma('dart2js:noInline')
  static InitialPublishRequest getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<InitialPublishRequest>(create);
  static InitialPublishRequest? _defaultInstance;

  /// The topic to which messages will be written.
  @$pb.TagNumber(1)
  $core.String get topic => $_getSZ(0);
  @$pb.TagNumber(1)
  set topic($core.String v) { $_setString(0, v); }
  @$pb.TagNumber(1)
  $core.bool hasTopic() => $_has(0);
  @$pb.TagNumber(1)
  void clearTopic() => clearField(1);

  /// The partition within the topic to which messages will be written.
  /// Partitions are zero indexed, so `partition` must be in the range [0,
  /// topic.num_partitions).
  @$pb.TagNumber(2)
  $fixnum.Int64 get partition => $_getI64(1);
  @$pb.TagNumber(2)
  set partition($fixnum.Int64 v) { $_setInt64(1, v); }
  @$pb.TagNumber(2)
  $core.bool hasPartition() => $_has(1);
  @$pb.TagNumber(2)
  void clearPartition() => clearField(2);

  ///  Unique identifier for a publisher client. If set, enables publish
  ///  idempotency within a publisher client session.
  ///
  ///  The length of this field must be exactly 16 bytes long and should be
  ///  populated with a 128 bit uuid, generated by standard uuid algorithms like
  ///  uuid1 or uuid4. The same identifier should be reused following
  ///  disconnections with retryable stream errors.
  @$pb.TagNumber(3)
  $core.List<$core.int> get clientId => $_getN(2);
  @$pb.TagNumber(3)
  set clientId($core.List<$core.int> v) { $_setBytes(2, v); }
  @$pb.TagNumber(3)
  $core.bool hasClientId() => $_has(2);
  @$pb.TagNumber(3)
  void clearClientId() => clearField(3);
}

/// Response to an InitialPublishRequest.
class InitialPublishResponse extends $pb.GeneratedMessage {
  factory InitialPublishResponse() => create();
  InitialPublishResponse._() : super();
  factory InitialPublishResponse.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory InitialPublishResponse.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'InitialPublishResponse', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.pubsublite.v1'), createEmptyInstance: create)
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  InitialPublishResponse clone() => InitialPublishResponse()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  InitialPublishResponse copyWith(void Function(InitialPublishResponse) updates) => super.copyWith((message) => updates(message as InitialPublishResponse)) as InitialPublishResponse;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static InitialPublishResponse create() => InitialPublishResponse._();
  InitialPublishResponse createEmptyInstance() => create();
  static $pb.PbList<InitialPublishResponse> createRepeated() => $pb.PbList<InitialPublishResponse>();
  @$core.pragma('dart2js:noInline')
  static InitialPublishResponse getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<InitialPublishResponse>(create);
  static InitialPublishResponse? _defaultInstance;
}

/// Request to publish messages to the topic.
class MessagePublishRequest extends $pb.GeneratedMessage {
  factory MessagePublishRequest({
    $core.Iterable<$1214.PubSubMessage>? messages,
    $fixnum.Int64? firstSequenceNumber,
  }) {
    final $result = create();
    if (messages != null) {
      $result.messages.addAll(messages);
    }
    if (firstSequenceNumber != null) {
      $result.firstSequenceNumber = firstSequenceNumber;
    }
    return $result;
  }
  MessagePublishRequest._() : super();
  factory MessagePublishRequest.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory MessagePublishRequest.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'MessagePublishRequest', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.pubsublite.v1'), createEmptyInstance: create)
    ..pc<$1214.PubSubMessage>(1, _omitFieldNames ? '' : 'messages', $pb.PbFieldType.PM, subBuilder: $1214.PubSubMessage.create)
    ..aInt64(2, _omitFieldNames ? '' : 'firstSequenceNumber')
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  MessagePublishRequest clone() => MessagePublishRequest()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  MessagePublishRequest copyWith(void Function(MessagePublishRequest) updates) => super.copyWith((message) => updates(message as MessagePublishRequest)) as MessagePublishRequest;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static MessagePublishRequest create() => MessagePublishRequest._();
  MessagePublishRequest createEmptyInstance() => create();
  static $pb.PbList<MessagePublishRequest> createRepeated() => $pb.PbList<MessagePublishRequest>();
  @$core.pragma('dart2js:noInline')
  static MessagePublishRequest getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<MessagePublishRequest>(create);
  static MessagePublishRequest? _defaultInstance;

  /// The messages to publish.
  @$pb.TagNumber(1)
  $core.List<$1214.PubSubMessage> get messages => $_getList(0);

  ///  The sequence number corresponding to the first message in `messages`.
  ///  Messages within a batch are ordered and the sequence numbers of all
  ///  subsequent messages in the batch are assumed to be incremental.
  ///
  ///  Sequence numbers are assigned at the message level and the first message
  ///  published in a publisher client session must have a sequence number of 0.
  ///  All messages must have contiguous sequence numbers, which uniquely identify
  ///  the messages accepted by the publisher client. Since messages are ordered,
  ///  the client only needs to specify the sequence number of the first message
  ///  in a published batch. The server deduplicates messages with the same
  ///  sequence number from the same publisher `client_id`.
  @$pb.TagNumber(2)
  $fixnum.Int64 get firstSequenceNumber => $_getI64(1);
  @$pb.TagNumber(2)
  set firstSequenceNumber($fixnum.Int64 v) { $_setInt64(1, v); }
  @$pb.TagNumber(2)
  $core.bool hasFirstSequenceNumber() => $_has(1);
  @$pb.TagNumber(2)
  void clearFirstSequenceNumber() => clearField(2);
}

/// Cursors for a subrange of published messages.
class MessagePublishResponse_CursorRange extends $pb.GeneratedMessage {
  factory MessagePublishResponse_CursorRange({
    $1214.Cursor? startCursor,
    $core.int? startIndex,
    $core.int? endIndex,
  }) {
    final $result = create();
    if (startCursor != null) {
      $result.startCursor = startCursor;
    }
    if (startIndex != null) {
      $result.startIndex = startIndex;
    }
    if (endIndex != null) {
      $result.endIndex = endIndex;
    }
    return $result;
  }
  MessagePublishResponse_CursorRange._() : super();
  factory MessagePublishResponse_CursorRange.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory MessagePublishResponse_CursorRange.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'MessagePublishResponse.CursorRange', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.pubsublite.v1'), createEmptyInstance: create)
    ..aOM<$1214.Cursor>(1, _omitFieldNames ? '' : 'startCursor', subBuilder: $1214.Cursor.create)
    ..a<$core.int>(2, _omitFieldNames ? '' : 'startIndex', $pb.PbFieldType.O3)
    ..a<$core.int>(3, _omitFieldNames ? '' : 'endIndex', $pb.PbFieldType.O3)
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  MessagePublishResponse_CursorRange clone() => MessagePublishResponse_CursorRange()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  MessagePublishResponse_CursorRange copyWith(void Function(MessagePublishResponse_CursorRange) updates) => super.copyWith((message) => updates(message as MessagePublishResponse_CursorRange)) as MessagePublishResponse_CursorRange;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static MessagePublishResponse_CursorRange create() => MessagePublishResponse_CursorRange._();
  MessagePublishResponse_CursorRange createEmptyInstance() => create();
  static $pb.PbList<MessagePublishResponse_CursorRange> createRepeated() => $pb.PbList<MessagePublishResponse_CursorRange>();
  @$core.pragma('dart2js:noInline')
  static MessagePublishResponse_CursorRange getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<MessagePublishResponse_CursorRange>(create);
  static MessagePublishResponse_CursorRange? _defaultInstance;

  /// The cursor of the message at the start index. The cursors for remaining
  /// messages up to the end index (exclusive) are sequential.
  @$pb.TagNumber(1)
  $1214.Cursor get startCursor => $_getN(0);
  @$pb.TagNumber(1)
  set startCursor($1214.Cursor v) { setField(1, v); }
  @$pb.TagNumber(1)
  $core.bool hasStartCursor() => $_has(0);
  @$pb.TagNumber(1)
  void clearStartCursor() => clearField(1);
  @$pb.TagNumber(1)
  $1214.Cursor ensureStartCursor() => $_ensure(0);

  /// Index of the message in the published batch that corresponds to the
  /// start cursor. Inclusive.
  @$pb.TagNumber(2)
  $core.int get startIndex => $_getIZ(1);
  @$pb.TagNumber(2)
  set startIndex($core.int v) { $_setSignedInt32(1, v); }
  @$pb.TagNumber(2)
  $core.bool hasStartIndex() => $_has(1);
  @$pb.TagNumber(2)
  void clearStartIndex() => clearField(2);

  /// Index of the last message in this range. Exclusive.
  @$pb.TagNumber(3)
  $core.int get endIndex => $_getIZ(2);
  @$pb.TagNumber(3)
  set endIndex($core.int v) { $_setSignedInt32(2, v); }
  @$pb.TagNumber(3)
  $core.bool hasEndIndex() => $_has(2);
  @$pb.TagNumber(3)
  void clearEndIndex() => clearField(3);
}

/// Response to a MessagePublishRequest.
class MessagePublishResponse extends $pb.GeneratedMessage {
  factory MessagePublishResponse({
    $1214.Cursor? startCursor,
    $core.Iterable<MessagePublishResponse_CursorRange>? cursorRanges,
  }) {
    final $result = create();
    if (startCursor != null) {
      $result.startCursor = startCursor;
    }
    if (cursorRanges != null) {
      $result.cursorRanges.addAll(cursorRanges);
    }
    return $result;
  }
  MessagePublishResponse._() : super();
  factory MessagePublishResponse.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory MessagePublishResponse.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'MessagePublishResponse', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.pubsublite.v1'), createEmptyInstance: create)
    ..aOM<$1214.Cursor>(1, _omitFieldNames ? '' : 'startCursor', subBuilder: $1214.Cursor.create)
    ..pc<MessagePublishResponse_CursorRange>(2, _omitFieldNames ? '' : 'cursorRanges', $pb.PbFieldType.PM, subBuilder: MessagePublishResponse_CursorRange.create)
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  MessagePublishResponse clone() => MessagePublishResponse()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  MessagePublishResponse copyWith(void Function(MessagePublishResponse) updates) => super.copyWith((message) => updates(message as MessagePublishResponse)) as MessagePublishResponse;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static MessagePublishResponse create() => MessagePublishResponse._();
  MessagePublishResponse createEmptyInstance() => create();
  static $pb.PbList<MessagePublishResponse> createRepeated() => $pb.PbList<MessagePublishResponse>();
  @$core.pragma('dart2js:noInline')
  static MessagePublishResponse getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<MessagePublishResponse>(create);
  static MessagePublishResponse? _defaultInstance;

  /// The cursor of the first published message in the batch. The cursors for any
  /// remaining messages in the batch are guaranteed to be sequential.
  @$pb.TagNumber(1)
  $1214.Cursor get startCursor => $_getN(0);
  @$pb.TagNumber(1)
  set startCursor($1214.Cursor v) { setField(1, v); }
  @$pb.TagNumber(1)
  $core.bool hasStartCursor() => $_has(0);
  @$pb.TagNumber(1)
  void clearStartCursor() => clearField(1);
  @$pb.TagNumber(1)
  $1214.Cursor ensureStartCursor() => $_ensure(0);

  ///  Cursors for messages published in the batch. There will exist multiple
  ///  ranges when cursors are not contiguous within the batch.
  ///
  ///  The cursor ranges may not account for all messages in the batch when
  ///  publish idempotency is enabled. A missing range indicates that cursors
  ///  could not be determined for messages within the range, as they were
  ///  deduplicated and the necessary data was not available at publish time.
  ///  These messages will have offsets when received by a subscriber.
  @$pb.TagNumber(2)
  $core.List<MessagePublishResponse_CursorRange> get cursorRanges => $_getList(1);
}

enum PublishRequest_RequestType {
  initialRequest, 
  messagePublishRequest, 
  notSet
}

/// Request sent from the client to the server on a stream.
class PublishRequest extends $pb.GeneratedMessage {
  factory PublishRequest({
    InitialPublishRequest? initialRequest,
    MessagePublishRequest? messagePublishRequest,
  }) {
    final $result = create();
    if (initialRequest != null) {
      $result.initialRequest = initialRequest;
    }
    if (messagePublishRequest != null) {
      $result.messagePublishRequest = messagePublishRequest;
    }
    return $result;
  }
  PublishRequest._() : super();
  factory PublishRequest.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory PublishRequest.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static const $core.Map<$core.int, PublishRequest_RequestType> _PublishRequest_RequestTypeByTag = {
    1 : PublishRequest_RequestType.initialRequest,
    2 : PublishRequest_RequestType.messagePublishRequest,
    0 : PublishRequest_RequestType.notSet
  };
  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'PublishRequest', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.pubsublite.v1'), createEmptyInstance: create)
    ..oo(0, [1, 2])
    ..aOM<InitialPublishRequest>(1, _omitFieldNames ? '' : 'initialRequest', subBuilder: InitialPublishRequest.create)
    ..aOM<MessagePublishRequest>(2, _omitFieldNames ? '' : 'messagePublishRequest', subBuilder: MessagePublishRequest.create)
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  PublishRequest clone() => PublishRequest()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  PublishRequest copyWith(void Function(PublishRequest) updates) => super.copyWith((message) => updates(message as PublishRequest)) as PublishRequest;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static PublishRequest create() => PublishRequest._();
  PublishRequest createEmptyInstance() => create();
  static $pb.PbList<PublishRequest> createRepeated() => $pb.PbList<PublishRequest>();
  @$core.pragma('dart2js:noInline')
  static PublishRequest getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<PublishRequest>(create);
  static PublishRequest? _defaultInstance;

  PublishRequest_RequestType whichRequestType() => _PublishRequest_RequestTypeByTag[$_whichOneof(0)]!;
  void clearRequestType() => clearField($_whichOneof(0));

  /// Initial request on the stream.
  @$pb.TagNumber(1)
  InitialPublishRequest get initialRequest => $_getN(0);
  @$pb.TagNumber(1)
  set initialRequest(InitialPublishRequest v) { setField(1, v); }
  @$pb.TagNumber(1)
  $core.bool hasInitialRequest() => $_has(0);
  @$pb.TagNumber(1)
  void clearInitialRequest() => clearField(1);
  @$pb.TagNumber(1)
  InitialPublishRequest ensureInitialRequest() => $_ensure(0);

  /// Request to publish messages.
  @$pb.TagNumber(2)
  MessagePublishRequest get messagePublishRequest => $_getN(1);
  @$pb.TagNumber(2)
  set messagePublishRequest(MessagePublishRequest v) { setField(2, v); }
  @$pb.TagNumber(2)
  $core.bool hasMessagePublishRequest() => $_has(1);
  @$pb.TagNumber(2)
  void clearMessagePublishRequest() => clearField(2);
  @$pb.TagNumber(2)
  MessagePublishRequest ensureMessagePublishRequest() => $_ensure(1);
}

enum PublishResponse_ResponseType {
  initialResponse, 
  messageResponse, 
  notSet
}

/// Response to a PublishRequest.
class PublishResponse extends $pb.GeneratedMessage {
  factory PublishResponse({
    InitialPublishResponse? initialResponse,
    MessagePublishResponse? messageResponse,
  }) {
    final $result = create();
    if (initialResponse != null) {
      $result.initialResponse = initialResponse;
    }
    if (messageResponse != null) {
      $result.messageResponse = messageResponse;
    }
    return $result;
  }
  PublishResponse._() : super();
  factory PublishResponse.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory PublishResponse.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static const $core.Map<$core.int, PublishResponse_ResponseType> _PublishResponse_ResponseTypeByTag = {
    1 : PublishResponse_ResponseType.initialResponse,
    2 : PublishResponse_ResponseType.messageResponse,
    0 : PublishResponse_ResponseType.notSet
  };
  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'PublishResponse', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.pubsublite.v1'), createEmptyInstance: create)
    ..oo(0, [1, 2])
    ..aOM<InitialPublishResponse>(1, _omitFieldNames ? '' : 'initialResponse', subBuilder: InitialPublishResponse.create)
    ..aOM<MessagePublishResponse>(2, _omitFieldNames ? '' : 'messageResponse', subBuilder: MessagePublishResponse.create)
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  PublishResponse clone() => PublishResponse()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  PublishResponse copyWith(void Function(PublishResponse) updates) => super.copyWith((message) => updates(message as PublishResponse)) as PublishResponse;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static PublishResponse create() => PublishResponse._();
  PublishResponse createEmptyInstance() => create();
  static $pb.PbList<PublishResponse> createRepeated() => $pb.PbList<PublishResponse>();
  @$core.pragma('dart2js:noInline')
  static PublishResponse getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<PublishResponse>(create);
  static PublishResponse? _defaultInstance;

  PublishResponse_ResponseType whichResponseType() => _PublishResponse_ResponseTypeByTag[$_whichOneof(0)]!;
  void clearResponseType() => clearField($_whichOneof(0));

  /// Initial response on the stream.
  @$pb.TagNumber(1)
  InitialPublishResponse get initialResponse => $_getN(0);
  @$pb.TagNumber(1)
  set initialResponse(InitialPublishResponse v) { setField(1, v); }
  @$pb.TagNumber(1)
  $core.bool hasInitialResponse() => $_has(0);
  @$pb.TagNumber(1)
  void clearInitialResponse() => clearField(1);
  @$pb.TagNumber(1)
  InitialPublishResponse ensureInitialResponse() => $_ensure(0);

  /// Response to publishing messages.
  @$pb.TagNumber(2)
  MessagePublishResponse get messageResponse => $_getN(1);
  @$pb.TagNumber(2)
  set messageResponse(MessagePublishResponse v) { setField(2, v); }
  @$pb.TagNumber(2)
  $core.bool hasMessageResponse() => $_has(1);
  @$pb.TagNumber(2)
  void clearMessageResponse() => clearField(2);
  @$pb.TagNumber(2)
  MessagePublishResponse ensureMessageResponse() => $_ensure(1);
}


const _omitFieldNames = $core.bool.fromEnvironment('protobuf.omit_field_names');
const _omitMessageNames = $core.bool.fromEnvironment('protobuf.omit_message_names');
