//
//  Generated code. Do not modify.
//  source: google/cloud/resourcemanager/v3/tag_holds.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:core' as $core;

import 'package:protobuf/protobuf.dart' as $pb;

import '../../../protobuf/timestamp.pb.dart' as $1776;

/// A TagHold represents the use of a TagValue that is not captured by
/// TagBindings. If a TagValue has any TagHolds, deletion will be blocked.
/// This resource is intended to be created in the same cloud location as the
/// `holder`.
class TagHold extends $pb.GeneratedMessage {
  factory TagHold({
    $core.String? name,
    $core.String? holder,
    $core.String? origin,
    $core.String? helpLink,
    $1776.Timestamp? createTime,
  }) {
    final $result = create();
    if (name != null) {
      $result.name = name;
    }
    if (holder != null) {
      $result.holder = holder;
    }
    if (origin != null) {
      $result.origin = origin;
    }
    if (helpLink != null) {
      $result.helpLink = helpLink;
    }
    if (createTime != null) {
      $result.createTime = createTime;
    }
    return $result;
  }
  TagHold._() : super();
  factory TagHold.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory TagHold.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'TagHold', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.resourcemanager.v3'), createEmptyInstance: create)
    ..aOS(1, _omitFieldNames ? '' : 'name')
    ..aOS(2, _omitFieldNames ? '' : 'holder')
    ..aOS(3, _omitFieldNames ? '' : 'origin')
    ..aOS(4, _omitFieldNames ? '' : 'helpLink')
    ..aOM<$1776.Timestamp>(5, _omitFieldNames ? '' : 'createTime', subBuilder: $1776.Timestamp.create)
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  TagHold clone() => TagHold()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  TagHold copyWith(void Function(TagHold) updates) => super.copyWith((message) => updates(message as TagHold)) as TagHold;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static TagHold create() => TagHold._();
  TagHold createEmptyInstance() => create();
  static $pb.PbList<TagHold> createRepeated() => $pb.PbList<TagHold>();
  @$core.pragma('dart2js:noInline')
  static TagHold getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<TagHold>(create);
  static TagHold? _defaultInstance;

  /// Output only. The resource name of a TagHold. This is a String of the form:
  /// `tagValues/{tag-value-id}/tagHolds/{tag-hold-id}`
  /// (e.g. `tagValues/123/tagHolds/456`). This resource name is generated by
  /// the server.
  @$pb.TagNumber(1)
  $core.String get name => $_getSZ(0);
  @$pb.TagNumber(1)
  set name($core.String v) { $_setString(0, v); }
  @$pb.TagNumber(1)
  $core.bool hasName() => $_has(0);
  @$pb.TagNumber(1)
  void clearName() => clearField(1);

  /// Required. The name of the resource where the TagValue is being used. Must
  /// be less than 200 characters. E.g.
  /// `//compute.googleapis.com/compute/projects/myproject/regions/us-east-1/instanceGroupManagers/instance-group`
  @$pb.TagNumber(2)
  $core.String get holder => $_getSZ(1);
  @$pb.TagNumber(2)
  set holder($core.String v) { $_setString(1, v); }
  @$pb.TagNumber(2)
  $core.bool hasHolder() => $_has(1);
  @$pb.TagNumber(2)
  void clearHolder() => clearField(2);

  /// Optional. An optional string representing the origin of this request. This
  /// field should include human-understandable information to distinguish
  /// origins from each other. Must be less than 200 characters. E.g.
  /// `migs-35678234`
  @$pb.TagNumber(3)
  $core.String get origin => $_getSZ(2);
  @$pb.TagNumber(3)
  set origin($core.String v) { $_setString(2, v); }
  @$pb.TagNumber(3)
  $core.bool hasOrigin() => $_has(2);
  @$pb.TagNumber(3)
  void clearOrigin() => clearField(3);

  /// Optional. A URL where an end user can learn more about removing this hold.
  /// E.g.
  /// `https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing`
  @$pb.TagNumber(4)
  $core.String get helpLink => $_getSZ(3);
  @$pb.TagNumber(4)
  set helpLink($core.String v) { $_setString(3, v); }
  @$pb.TagNumber(4)
  $core.bool hasHelpLink() => $_has(3);
  @$pb.TagNumber(4)
  void clearHelpLink() => clearField(4);

  /// Output only. The time this TagHold was created.
  @$pb.TagNumber(5)
  $1776.Timestamp get createTime => $_getN(4);
  @$pb.TagNumber(5)
  set createTime($1776.Timestamp v) { setField(5, v); }
  @$pb.TagNumber(5)
  $core.bool hasCreateTime() => $_has(4);
  @$pb.TagNumber(5)
  void clearCreateTime() => clearField(5);
  @$pb.TagNumber(5)
  $1776.Timestamp ensureCreateTime() => $_ensure(4);
}

/// The request message to create a TagHold.
class CreateTagHoldRequest extends $pb.GeneratedMessage {
  factory CreateTagHoldRequest({
    $core.String? parent,
    TagHold? tagHold,
    $core.bool? validateOnly,
  }) {
    final $result = create();
    if (parent != null) {
      $result.parent = parent;
    }
    if (tagHold != null) {
      $result.tagHold = tagHold;
    }
    if (validateOnly != null) {
      $result.validateOnly = validateOnly;
    }
    return $result;
  }
  CreateTagHoldRequest._() : super();
  factory CreateTagHoldRequest.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory CreateTagHoldRequest.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'CreateTagHoldRequest', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.resourcemanager.v3'), createEmptyInstance: create)
    ..aOS(1, _omitFieldNames ? '' : 'parent')
    ..aOM<TagHold>(2, _omitFieldNames ? '' : 'tagHold', subBuilder: TagHold.create)
    ..aOB(3, _omitFieldNames ? '' : 'validateOnly')
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  CreateTagHoldRequest clone() => CreateTagHoldRequest()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  CreateTagHoldRequest copyWith(void Function(CreateTagHoldRequest) updates) => super.copyWith((message) => updates(message as CreateTagHoldRequest)) as CreateTagHoldRequest;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static CreateTagHoldRequest create() => CreateTagHoldRequest._();
  CreateTagHoldRequest createEmptyInstance() => create();
  static $pb.PbList<CreateTagHoldRequest> createRepeated() => $pb.PbList<CreateTagHoldRequest>();
  @$core.pragma('dart2js:noInline')
  static CreateTagHoldRequest getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<CreateTagHoldRequest>(create);
  static CreateTagHoldRequest? _defaultInstance;

  /// Required. The resource name of the TagHold's parent TagValue. Must be of
  /// the form: `tagValues/{tag-value-id}`.
  @$pb.TagNumber(1)
  $core.String get parent => $_getSZ(0);
  @$pb.TagNumber(1)
  set parent($core.String v) { $_setString(0, v); }
  @$pb.TagNumber(1)
  $core.bool hasParent() => $_has(0);
  @$pb.TagNumber(1)
  void clearParent() => clearField(1);

  /// Required. The TagHold to be created.
  @$pb.TagNumber(2)
  TagHold get tagHold => $_getN(1);
  @$pb.TagNumber(2)
  set tagHold(TagHold v) { setField(2, v); }
  @$pb.TagNumber(2)
  $core.bool hasTagHold() => $_has(1);
  @$pb.TagNumber(2)
  void clearTagHold() => clearField(2);
  @$pb.TagNumber(2)
  TagHold ensureTagHold() => $_ensure(1);

  /// Optional. Set to true to perform the validations necessary for creating the
  /// resource, but not actually perform the action.
  @$pb.TagNumber(3)
  $core.bool get validateOnly => $_getBF(2);
  @$pb.TagNumber(3)
  set validateOnly($core.bool v) { $_setBool(2, v); }
  @$pb.TagNumber(3)
  $core.bool hasValidateOnly() => $_has(2);
  @$pb.TagNumber(3)
  void clearValidateOnly() => clearField(3);
}

/// Runtime operation information for creating a TagHold.
/// (-- The metadata is currently empty, but may include information in the
/// future. --)
class CreateTagHoldMetadata extends $pb.GeneratedMessage {
  factory CreateTagHoldMetadata() => create();
  CreateTagHoldMetadata._() : super();
  factory CreateTagHoldMetadata.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory CreateTagHoldMetadata.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'CreateTagHoldMetadata', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.resourcemanager.v3'), createEmptyInstance: create)
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  CreateTagHoldMetadata clone() => CreateTagHoldMetadata()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  CreateTagHoldMetadata copyWith(void Function(CreateTagHoldMetadata) updates) => super.copyWith((message) => updates(message as CreateTagHoldMetadata)) as CreateTagHoldMetadata;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static CreateTagHoldMetadata create() => CreateTagHoldMetadata._();
  CreateTagHoldMetadata createEmptyInstance() => create();
  static $pb.PbList<CreateTagHoldMetadata> createRepeated() => $pb.PbList<CreateTagHoldMetadata>();
  @$core.pragma('dart2js:noInline')
  static CreateTagHoldMetadata getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<CreateTagHoldMetadata>(create);
  static CreateTagHoldMetadata? _defaultInstance;
}

/// The request message to delete a TagHold.
class DeleteTagHoldRequest extends $pb.GeneratedMessage {
  factory DeleteTagHoldRequest({
    $core.String? name,
    $core.bool? validateOnly,
  }) {
    final $result = create();
    if (name != null) {
      $result.name = name;
    }
    if (validateOnly != null) {
      $result.validateOnly = validateOnly;
    }
    return $result;
  }
  DeleteTagHoldRequest._() : super();
  factory DeleteTagHoldRequest.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory DeleteTagHoldRequest.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'DeleteTagHoldRequest', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.resourcemanager.v3'), createEmptyInstance: create)
    ..aOS(1, _omitFieldNames ? '' : 'name')
    ..aOB(2, _omitFieldNames ? '' : 'validateOnly')
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  DeleteTagHoldRequest clone() => DeleteTagHoldRequest()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  DeleteTagHoldRequest copyWith(void Function(DeleteTagHoldRequest) updates) => super.copyWith((message) => updates(message as DeleteTagHoldRequest)) as DeleteTagHoldRequest;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static DeleteTagHoldRequest create() => DeleteTagHoldRequest._();
  DeleteTagHoldRequest createEmptyInstance() => create();
  static $pb.PbList<DeleteTagHoldRequest> createRepeated() => $pb.PbList<DeleteTagHoldRequest>();
  @$core.pragma('dart2js:noInline')
  static DeleteTagHoldRequest getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<DeleteTagHoldRequest>(create);
  static DeleteTagHoldRequest? _defaultInstance;

  /// Required. The resource name of the TagHold to delete. Must be of the form:
  /// `tagValues/{tag-value-id}/tagHolds/{tag-hold-id}`.
  @$pb.TagNumber(1)
  $core.String get name => $_getSZ(0);
  @$pb.TagNumber(1)
  set name($core.String v) { $_setString(0, v); }
  @$pb.TagNumber(1)
  $core.bool hasName() => $_has(0);
  @$pb.TagNumber(1)
  void clearName() => clearField(1);

  /// Optional. Set to true to perform the validations necessary for deleting the
  /// resource, but not actually perform the action.
  @$pb.TagNumber(2)
  $core.bool get validateOnly => $_getBF(1);
  @$pb.TagNumber(2)
  set validateOnly($core.bool v) { $_setBool(1, v); }
  @$pb.TagNumber(2)
  $core.bool hasValidateOnly() => $_has(1);
  @$pb.TagNumber(2)
  void clearValidateOnly() => clearField(2);
}

/// Runtime operation information for deleting a TagHold.
/// (-- The metadata is currently empty, but may include information in the
/// future. --)
class DeleteTagHoldMetadata extends $pb.GeneratedMessage {
  factory DeleteTagHoldMetadata() => create();
  DeleteTagHoldMetadata._() : super();
  factory DeleteTagHoldMetadata.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory DeleteTagHoldMetadata.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'DeleteTagHoldMetadata', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.resourcemanager.v3'), createEmptyInstance: create)
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  DeleteTagHoldMetadata clone() => DeleteTagHoldMetadata()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  DeleteTagHoldMetadata copyWith(void Function(DeleteTagHoldMetadata) updates) => super.copyWith((message) => updates(message as DeleteTagHoldMetadata)) as DeleteTagHoldMetadata;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static DeleteTagHoldMetadata create() => DeleteTagHoldMetadata._();
  DeleteTagHoldMetadata createEmptyInstance() => create();
  static $pb.PbList<DeleteTagHoldMetadata> createRepeated() => $pb.PbList<DeleteTagHoldMetadata>();
  @$core.pragma('dart2js:noInline')
  static DeleteTagHoldMetadata getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<DeleteTagHoldMetadata>(create);
  static DeleteTagHoldMetadata? _defaultInstance;
}

/// The request message for listing the TagHolds under a TagValue.
class ListTagHoldsRequest extends $pb.GeneratedMessage {
  factory ListTagHoldsRequest({
    $core.String? parent,
    $core.int? pageSize,
    $core.String? pageToken,
    $core.String? filter,
  }) {
    final $result = create();
    if (parent != null) {
      $result.parent = parent;
    }
    if (pageSize != null) {
      $result.pageSize = pageSize;
    }
    if (pageToken != null) {
      $result.pageToken = pageToken;
    }
    if (filter != null) {
      $result.filter = filter;
    }
    return $result;
  }
  ListTagHoldsRequest._() : super();
  factory ListTagHoldsRequest.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory ListTagHoldsRequest.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'ListTagHoldsRequest', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.resourcemanager.v3'), createEmptyInstance: create)
    ..aOS(1, _omitFieldNames ? '' : 'parent')
    ..a<$core.int>(2, _omitFieldNames ? '' : 'pageSize', $pb.PbFieldType.O3)
    ..aOS(3, _omitFieldNames ? '' : 'pageToken')
    ..aOS(4, _omitFieldNames ? '' : 'filter')
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  ListTagHoldsRequest clone() => ListTagHoldsRequest()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  ListTagHoldsRequest copyWith(void Function(ListTagHoldsRequest) updates) => super.copyWith((message) => updates(message as ListTagHoldsRequest)) as ListTagHoldsRequest;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static ListTagHoldsRequest create() => ListTagHoldsRequest._();
  ListTagHoldsRequest createEmptyInstance() => create();
  static $pb.PbList<ListTagHoldsRequest> createRepeated() => $pb.PbList<ListTagHoldsRequest>();
  @$core.pragma('dart2js:noInline')
  static ListTagHoldsRequest getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<ListTagHoldsRequest>(create);
  static ListTagHoldsRequest? _defaultInstance;

  /// Required. The resource name of the parent TagValue. Must be of the form:
  /// `tagValues/{tag-value-id}`.
  @$pb.TagNumber(1)
  $core.String get parent => $_getSZ(0);
  @$pb.TagNumber(1)
  set parent($core.String v) { $_setString(0, v); }
  @$pb.TagNumber(1)
  $core.bool hasParent() => $_has(0);
  @$pb.TagNumber(1)
  void clearParent() => clearField(1);

  /// Optional. The maximum number of TagHolds to return in the response. The
  /// server allows a maximum of 300 TagHolds to return. If unspecified, the
  /// server will use 100 as the default.
  @$pb.TagNumber(2)
  $core.int get pageSize => $_getIZ(1);
  @$pb.TagNumber(2)
  set pageSize($core.int v) { $_setSignedInt32(1, v); }
  @$pb.TagNumber(2)
  $core.bool hasPageSize() => $_has(1);
  @$pb.TagNumber(2)
  void clearPageSize() => clearField(2);

  /// Optional. A pagination token returned from a previous call to
  /// `ListTagHolds` that indicates where this listing should continue from.
  @$pb.TagNumber(3)
  $core.String get pageToken => $_getSZ(2);
  @$pb.TagNumber(3)
  set pageToken($core.String v) { $_setString(2, v); }
  @$pb.TagNumber(3)
  $core.bool hasPageToken() => $_has(2);
  @$pb.TagNumber(3)
  void clearPageToken() => clearField(3);

  ///  Optional. Criteria used to select a subset of TagHolds parented by the
  ///  TagValue to return. This field follows the syntax defined by aip.dev/160;
  ///  the `holder` and `origin` fields are supported for filtering. Currently
  ///  only `AND` syntax is supported. Some example queries are:
  ///
  ///    * `holder =
  ///      //compute.googleapis.com/compute/projects/myproject/regions/us-east-1/instanceGroupManagers/instance-group`
  ///    * `origin = 35678234`
  ///    * `holder =
  ///      //compute.googleapis.com/compute/projects/myproject/regions/us-east-1/instanceGroupManagers/instance-group
  ///      AND origin = 35678234`
  @$pb.TagNumber(4)
  $core.String get filter => $_getSZ(3);
  @$pb.TagNumber(4)
  set filter($core.String v) { $_setString(3, v); }
  @$pb.TagNumber(4)
  $core.bool hasFilter() => $_has(3);
  @$pb.TagNumber(4)
  void clearFilter() => clearField(4);
}

/// The ListTagHolds response.
class ListTagHoldsResponse extends $pb.GeneratedMessage {
  factory ListTagHoldsResponse({
    $core.Iterable<TagHold>? tagHolds,
    $core.String? nextPageToken,
  }) {
    final $result = create();
    if (tagHolds != null) {
      $result.tagHolds.addAll(tagHolds);
    }
    if (nextPageToken != null) {
      $result.nextPageToken = nextPageToken;
    }
    return $result;
  }
  ListTagHoldsResponse._() : super();
  factory ListTagHoldsResponse.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory ListTagHoldsResponse.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(_omitMessageNames ? '' : 'ListTagHoldsResponse', package: const $pb.PackageName(_omitMessageNames ? '' : 'google.cloud.resourcemanager.v3'), createEmptyInstance: create)
    ..pc<TagHold>(1, _omitFieldNames ? '' : 'tagHolds', $pb.PbFieldType.PM, subBuilder: TagHold.create)
    ..aOS(2, _omitFieldNames ? '' : 'nextPageToken')
    ..hasRequiredFields = false
  ;

  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.deepCopy] instead. '
  'Will be removed in next major version')
  ListTagHoldsResponse clone() => ListTagHoldsResponse()..mergeFromMessage(this);
  @$core.Deprecated(
  'Using this can add significant overhead to your binary. '
  'Use [GeneratedMessageGenericExtensions.rebuild] instead. '
  'Will be removed in next major version')
  ListTagHoldsResponse copyWith(void Function(ListTagHoldsResponse) updates) => super.copyWith((message) => updates(message as ListTagHoldsResponse)) as ListTagHoldsResponse;

  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static ListTagHoldsResponse create() => ListTagHoldsResponse._();
  ListTagHoldsResponse createEmptyInstance() => create();
  static $pb.PbList<ListTagHoldsResponse> createRepeated() => $pb.PbList<ListTagHoldsResponse>();
  @$core.pragma('dart2js:noInline')
  static ListTagHoldsResponse getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<ListTagHoldsResponse>(create);
  static ListTagHoldsResponse? _defaultInstance;

  /// A possibly paginated list of TagHolds.
  @$pb.TagNumber(1)
  $core.List<TagHold> get tagHolds => $_getList(0);

  ///  Pagination token.
  ///
  ///  If the result set is too large to fit in a single response, this token
  ///  is returned. It encodes the position of the current result cursor.
  ///  Feeding this value into a new list request with the `page_token` parameter
  ///  gives the next page of the results.
  ///
  ///  When `next_page_token` is not filled in, there is no next page and
  ///  the list returned is the last page in the result set.
  ///
  ///  Pagination tokens have a limited lifetime.
  @$pb.TagNumber(2)
  $core.String get nextPageToken => $_getSZ(1);
  @$pb.TagNumber(2)
  set nextPageToken($core.String v) { $_setString(1, v); }
  @$pb.TagNumber(2)
  $core.bool hasNextPageToken() => $_has(1);
  @$pb.TagNumber(2)
  void clearNextPageToken() => clearField(2);
}


const _omitFieldNames = $core.bool.fromEnvironment('protobuf.omit_field_names');
const _omitMessageNames = $core.bool.fromEnvironment('protobuf.omit_message_names');
