//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v15/enums/click_type.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use clickTypeEnumDescriptor instead')
const ClickTypeEnum$json = {
  '1': 'ClickTypeEnum',
  '4': [ClickTypeEnum_ClickType$json],
};

@$core.Deprecated('Use clickTypeEnumDescriptor instead')
const ClickTypeEnum_ClickType$json = {
  '1': 'ClickType',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'APP_DEEPLINK', '2': 2},
    {'1': 'BREADCRUMBS', '2': 3},
    {'1': 'BROADBAND_PLAN', '2': 4},
    {'1': 'CALL_TRACKING', '2': 5},
    {'1': 'CALLS', '2': 6},
    {'1': 'CLICK_ON_ENGAGEMENT_AD', '2': 7},
    {'1': 'GET_DIRECTIONS', '2': 8},
    {'1': 'LOCATION_EXPANSION', '2': 9},
    {'1': 'LOCATION_FORMAT_CALL', '2': 10},
    {'1': 'LOCATION_FORMAT_DIRECTIONS', '2': 11},
    {'1': 'LOCATION_FORMAT_IMAGE', '2': 12},
    {'1': 'LOCATION_FORMAT_LANDING_PAGE', '2': 13},
    {'1': 'LOCATION_FORMAT_MAP', '2': 14},
    {'1': 'LOCATION_FORMAT_STORE_INFO', '2': 15},
    {'1': 'LOCATION_FORMAT_TEXT', '2': 16},
    {'1': 'MOBILE_CALL_TRACKING', '2': 17},
    {'1': 'OFFER_PRINTS', '2': 18},
    {'1': 'OTHER', '2': 19},
    {'1': 'PRODUCT_EXTENSION_CLICKS', '2': 20},
    {'1': 'PRODUCT_LISTING_AD_CLICKS', '2': 21},
    {'1': 'SITELINKS', '2': 22},
    {'1': 'STORE_LOCATOR', '2': 23},
    {'1': 'URL_CLICKS', '2': 25},
    {'1': 'VIDEO_APP_STORE_CLICKS', '2': 26},
    {'1': 'VIDEO_CALL_TO_ACTION_CLICKS', '2': 27},
    {'1': 'VIDEO_CARD_ACTION_HEADLINE_CLICKS', '2': 28},
    {'1': 'VIDEO_END_CAP_CLICKS', '2': 29},
    {'1': 'VIDEO_WEBSITE_CLICKS', '2': 30},
    {'1': 'VISUAL_SITELINKS', '2': 31},
    {'1': 'WIRELESS_PLAN', '2': 32},
    {'1': 'PRODUCT_LISTING_AD_LOCAL', '2': 33},
    {'1': 'PRODUCT_LISTING_AD_MULTICHANNEL_LOCAL', '2': 34},
    {'1': 'PRODUCT_LISTING_AD_MULTICHANNEL_ONLINE', '2': 35},
    {'1': 'PRODUCT_LISTING_ADS_COUPON', '2': 36},
    {'1': 'PRODUCT_LISTING_AD_TRANSACTABLE', '2': 37},
    {'1': 'PRODUCT_AD_APP_DEEPLINK', '2': 38},
    {'1': 'SHOWCASE_AD_CATEGORY_LINK', '2': 39},
    {'1': 'SHOWCASE_AD_LOCAL_STOREFRONT_LINK', '2': 40},
    {'1': 'SHOWCASE_AD_ONLINE_PRODUCT_LINK', '2': 42},
    {'1': 'SHOWCASE_AD_LOCAL_PRODUCT_LINK', '2': 43},
    {'1': 'PROMOTION_EXTENSION', '2': 44},
    {'1': 'SWIPEABLE_GALLERY_AD_HEADLINE', '2': 45},
    {'1': 'SWIPEABLE_GALLERY_AD_SWIPES', '2': 46},
    {'1': 'SWIPEABLE_GALLERY_AD_SEE_MORE', '2': 47},
    {'1': 'SWIPEABLE_GALLERY_AD_SITELINK_ONE', '2': 48},
    {'1': 'SWIPEABLE_GALLERY_AD_SITELINK_TWO', '2': 49},
    {'1': 'SWIPEABLE_GALLERY_AD_SITELINK_THREE', '2': 50},
    {'1': 'SWIPEABLE_GALLERY_AD_SITELINK_FOUR', '2': 51},
    {'1': 'SWIPEABLE_GALLERY_AD_SITELINK_FIVE', '2': 52},
    {'1': 'HOTEL_PRICE', '2': 53},
    {'1': 'PRICE_EXTENSION', '2': 54},
    {'1': 'HOTEL_BOOK_ON_GOOGLE_ROOM_SELECTION', '2': 55},
    {'1': 'SHOPPING_COMPARISON_LISTING', '2': 56},
    {'1': 'CROSS_NETWORK', '2': 57},
  ],
};

/// Descriptor for `ClickTypeEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List clickTypeEnumDescriptor = $convert.base64Decode(
    'Cg1DbGlja1R5cGVFbnVtIqcMCglDbGlja1R5cGUSDwoLVU5TUEVDSUZJRUQQABILCgdVTktOT1'
    'dOEAESEAoMQVBQX0RFRVBMSU5LEAISDwoLQlJFQURDUlVNQlMQAxISCg5CUk9BREJBTkRfUExB'
    'ThAEEhEKDUNBTExfVFJBQ0tJTkcQBRIJCgVDQUxMUxAGEhoKFkNMSUNLX09OX0VOR0FHRU1FTl'
    'RfQUQQBxISCg5HRVRfRElSRUNUSU9OUxAIEhYKEkxPQ0FUSU9OX0VYUEFOU0lPThAJEhgKFExP'
    'Q0FUSU9OX0ZPUk1BVF9DQUxMEAoSHgoaTE9DQVRJT05fRk9STUFUX0RJUkVDVElPTlMQCxIZCh'
    'VMT0NBVElPTl9GT1JNQVRfSU1BR0UQDBIgChxMT0NBVElPTl9GT1JNQVRfTEFORElOR19QQUdF'
    'EA0SFwoTTE9DQVRJT05fRk9STUFUX01BUBAOEh4KGkxPQ0FUSU9OX0ZPUk1BVF9TVE9SRV9JTk'
    'ZPEA8SGAoUTE9DQVRJT05fRk9STUFUX1RFWFQQEBIYChRNT0JJTEVfQ0FMTF9UUkFDS0lORxAR'
    'EhAKDE9GRkVSX1BSSU5UUxASEgkKBU9USEVSEBMSHAoYUFJPRFVDVF9FWFRFTlNJT05fQ0xJQ0'
    'tTEBQSHQoZUFJPRFVDVF9MSVNUSU5HX0FEX0NMSUNLUxAVEg0KCVNJVEVMSU5LUxAWEhEKDVNU'
    'T1JFX0xPQ0FUT1IQFxIOCgpVUkxfQ0xJQ0tTEBkSGgoWVklERU9fQVBQX1NUT1JFX0NMSUNLUx'
    'AaEh8KG1ZJREVPX0NBTExfVE9fQUNUSU9OX0NMSUNLUxAbEiUKIVZJREVPX0NBUkRfQUNUSU9O'
    'X0hFQURMSU5FX0NMSUNLUxAcEhgKFFZJREVPX0VORF9DQVBfQ0xJQ0tTEB0SGAoUVklERU9fV0'
    'VCU0lURV9DTElDS1MQHhIUChBWSVNVQUxfU0lURUxJTktTEB8SEQoNV0lSRUxFU1NfUExBThAg'
    'EhwKGFBST0RVQ1RfTElTVElOR19BRF9MT0NBTBAhEikKJVBST0RVQ1RfTElTVElOR19BRF9NVU'
    'xUSUNIQU5ORUxfTE9DQUwQIhIqCiZQUk9EVUNUX0xJU1RJTkdfQURfTVVMVElDSEFOTkVMX09O'
    'TElORRAjEh4KGlBST0RVQ1RfTElTVElOR19BRFNfQ09VUE9OECQSIwofUFJPRFVDVF9MSVNUSU'
    '5HX0FEX1RSQU5TQUNUQUJMRRAlEhsKF1BST0RVQ1RfQURfQVBQX0RFRVBMSU5LECYSHQoZU0hP'
    'V0NBU0VfQURfQ0FURUdPUllfTElOSxAnEiUKIVNIT1dDQVNFX0FEX0xPQ0FMX1NUT1JFRlJPTl'
    'RfTElOSxAoEiMKH1NIT1dDQVNFX0FEX09OTElORV9QUk9EVUNUX0xJTksQKhIiCh5TSE9XQ0FT'
    'RV9BRF9MT0NBTF9QUk9EVUNUX0xJTksQKxIXChNQUk9NT1RJT05fRVhURU5TSU9OECwSIQodU1'
    'dJUEVBQkxFX0dBTExFUllfQURfSEVBRExJTkUQLRIfChtTV0lQRUFCTEVfR0FMTEVSWV9BRF9T'
    'V0lQRVMQLhIhCh1TV0lQRUFCTEVfR0FMTEVSWV9BRF9TRUVfTU9SRRAvEiUKIVNXSVBFQUJMRV'
    '9HQUxMRVJZX0FEX1NJVEVMSU5LX09ORRAwEiUKIVNXSVBFQUJMRV9HQUxMRVJZX0FEX1NJVEVM'
    'SU5LX1RXTxAxEicKI1NXSVBFQUJMRV9HQUxMRVJZX0FEX1NJVEVMSU5LX1RIUkVFEDISJgoiU1'
    'dJUEVBQkxFX0dBTExFUllfQURfU0lURUxJTktfRk9VUhAzEiYKIlNXSVBFQUJMRV9HQUxMRVJZ'
    'X0FEX1NJVEVMSU5LX0ZJVkUQNBIPCgtIT1RFTF9QUklDRRA1EhMKD1BSSUNFX0VYVEVOU0lPTh'
    'A2EicKI0hPVEVMX0JPT0tfT05fR09PR0xFX1JPT01fU0VMRUNUSU9OEDcSHwobU0hPUFBJTkdf'
    'Q09NUEFSSVNPTl9MSVNUSU5HEDgSEQoNQ1JPU1NfTkVUV09SSxA5');

