//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v16/enums/recommendation_type.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use recommendationTypeEnumDescriptor instead')
const RecommendationTypeEnum$json = {
  '1': 'RecommendationTypeEnum',
  '4': [RecommendationTypeEnum_RecommendationType$json],
};

@$core.Deprecated('Use recommendationTypeEnumDescriptor instead')
const RecommendationTypeEnum_RecommendationType$json = {
  '1': 'RecommendationType',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'CAMPAIGN_BUDGET', '2': 2},
    {'1': 'KEYWORD', '2': 3},
    {'1': 'TEXT_AD', '2': 4},
    {'1': 'TARGET_CPA_OPT_IN', '2': 5},
    {'1': 'MAXIMIZE_CONVERSIONS_OPT_IN', '2': 6},
    {'1': 'ENHANCED_CPC_OPT_IN', '2': 7},
    {'1': 'SEARCH_PARTNERS_OPT_IN', '2': 8},
    {'1': 'MAXIMIZE_CLICKS_OPT_IN', '2': 9},
    {'1': 'OPTIMIZE_AD_ROTATION', '2': 10},
    {'1': 'KEYWORD_MATCH_TYPE', '2': 14},
    {'1': 'MOVE_UNUSED_BUDGET', '2': 15},
    {'1': 'FORECASTING_CAMPAIGN_BUDGET', '2': 16},
    {'1': 'TARGET_ROAS_OPT_IN', '2': 17},
    {'1': 'RESPONSIVE_SEARCH_AD', '2': 18},
    {'1': 'MARGINAL_ROI_CAMPAIGN_BUDGET', '2': 19},
    {'1': 'USE_BROAD_MATCH_KEYWORD', '2': 20},
    {'1': 'RESPONSIVE_SEARCH_AD_ASSET', '2': 21},
    {'1': 'UPGRADE_SMART_SHOPPING_CAMPAIGN_TO_PERFORMANCE_MAX', '2': 22},
    {'1': 'RESPONSIVE_SEARCH_AD_IMPROVE_AD_STRENGTH', '2': 23},
    {'1': 'DISPLAY_EXPANSION_OPT_IN', '2': 24},
    {'1': 'UPGRADE_LOCAL_CAMPAIGN_TO_PERFORMANCE_MAX', '2': 25},
    {'1': 'RAISE_TARGET_CPA_BID_TOO_LOW', '2': 26},
    {'1': 'FORECASTING_SET_TARGET_ROAS', '2': 27},
    {'1': 'CALLOUT_ASSET', '2': 28},
    {'1': 'SITELINK_ASSET', '2': 29},
    {'1': 'CALL_ASSET', '2': 30},
    {'1': 'SHOPPING_ADD_AGE_GROUP', '2': 31},
    {'1': 'SHOPPING_ADD_COLOR', '2': 32},
    {'1': 'SHOPPING_ADD_GENDER', '2': 33},
    {'1': 'SHOPPING_ADD_GTIN', '2': 34},
    {'1': 'SHOPPING_ADD_MORE_IDENTIFIERS', '2': 35},
    {'1': 'SHOPPING_ADD_SIZE', '2': 36},
    {'1': 'SHOPPING_ADD_PRODUCTS_TO_CAMPAIGN', '2': 37},
    {'1': 'SHOPPING_FIX_DISAPPROVED_PRODUCTS', '2': 38},
    {'1': 'SHOPPING_TARGET_ALL_OFFERS', '2': 39},
    {'1': 'SHOPPING_FIX_SUSPENDED_MERCHANT_CENTER_ACCOUNT', '2': 40},
    {'1': 'SHOPPING_FIX_MERCHANT_CENTER_ACCOUNT_SUSPENSION_WARNING', '2': 41},
    {'1': 'SHOPPING_MIGRATE_REGULAR_SHOPPING_CAMPAIGN_OFFERS_TO_PERFORMANCE_MAX', '2': 42},
    {'1': 'DYNAMIC_IMAGE_EXTENSION_OPT_IN', '2': 43},
    {'1': 'RAISE_TARGET_CPA', '2': 44},
    {'1': 'LOWER_TARGET_ROAS', '2': 45},
    {'1': 'PERFORMANCE_MAX_OPT_IN', '2': 46},
    {'1': 'IMPROVE_PERFORMANCE_MAX_AD_STRENGTH', '2': 47},
    {'1': 'MIGRATE_DYNAMIC_SEARCH_ADS_CAMPAIGN_TO_PERFORMANCE_MAX', '2': 48},
    {'1': 'FORECASTING_SET_TARGET_CPA', '2': 49},
    {'1': 'SET_TARGET_CPA', '2': 50},
    {'1': 'SET_TARGET_ROAS', '2': 51},
    {'1': 'MAXIMIZE_CONVERSION_VALUE_OPT_IN', '2': 52},
    {'1': 'IMPROVE_GOOGLE_TAG_COVERAGE', '2': 53},
    {'1': 'PERFORMANCE_MAX_FINAL_URL_OPT_IN', '2': 54},
    {'1': 'REFRESH_CUSTOMER_MATCH_LIST', '2': 55},
    {'1': 'CUSTOM_AUDIENCE_OPT_IN', '2': 56},
    {'1': 'LEAD_FORM_ASSET', '2': 57},
    {'1': 'IMPROVE_DEMAND_GEN_AD_STRENGTH', '2': 58},
  ],
};

/// Descriptor for `RecommendationTypeEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List recommendationTypeEnumDescriptor = $convert.base64Decode(
    'ChZSZWNvbW1lbmRhdGlvblR5cGVFbnVtItgNChJSZWNvbW1lbmRhdGlvblR5cGUSDwoLVU5TUE'
    'VDSUZJRUQQABILCgdVTktOT1dOEAESEwoPQ0FNUEFJR05fQlVER0VUEAISCwoHS0VZV09SRBAD'
    'EgsKB1RFWFRfQUQQBBIVChFUQVJHRVRfQ1BBX09QVF9JThAFEh8KG01BWElNSVpFX0NPTlZFUl'
    'NJT05TX09QVF9JThAGEhcKE0VOSEFOQ0VEX0NQQ19PUFRfSU4QBxIaChZTRUFSQ0hfUEFSVE5F'
    'UlNfT1BUX0lOEAgSGgoWTUFYSU1JWkVfQ0xJQ0tTX09QVF9JThAJEhgKFE9QVElNSVpFX0FEX1'
    'JPVEFUSU9OEAoSFgoSS0VZV09SRF9NQVRDSF9UWVBFEA4SFgoSTU9WRV9VTlVTRURfQlVER0VU'
    'EA8SHwobRk9SRUNBU1RJTkdfQ0FNUEFJR05fQlVER0VUEBASFgoSVEFSR0VUX1JPQVNfT1BUX0'
    'lOEBESGAoUUkVTUE9OU0lWRV9TRUFSQ0hfQUQQEhIgChxNQVJHSU5BTF9ST0lfQ0FNUEFJR05f'
    'QlVER0VUEBMSGwoXVVNFX0JST0FEX01BVENIX0tFWVdPUkQQFBIeChpSRVNQT05TSVZFX1NFQV'
    'JDSF9BRF9BU1NFVBAVEjYKMlVQR1JBREVfU01BUlRfU0hPUFBJTkdfQ0FNUEFJR05fVE9fUEVS'
    'Rk9STUFOQ0VfTUFYEBYSLAooUkVTUE9OU0lWRV9TRUFSQ0hfQURfSU1QUk9WRV9BRF9TVFJFTk'
    'dUSBAXEhwKGERJU1BMQVlfRVhQQU5TSU9OX09QVF9JThAYEi0KKVVQR1JBREVfTE9DQUxfQ0FN'
    'UEFJR05fVE9fUEVSRk9STUFOQ0VfTUFYEBkSIAocUkFJU0VfVEFSR0VUX0NQQV9CSURfVE9PX0'
    'xPVxAaEh8KG0ZPUkVDQVNUSU5HX1NFVF9UQVJHRVRfUk9BUxAbEhEKDUNBTExPVVRfQVNTRVQQ'
    'HBISCg5TSVRFTElOS19BU1NFVBAdEg4KCkNBTExfQVNTRVQQHhIaChZTSE9QUElOR19BRERfQU'
    'dFX0dST1VQEB8SFgoSU0hPUFBJTkdfQUREX0NPTE9SECASFwoTU0hPUFBJTkdfQUREX0dFTkRF'
    'UhAhEhUKEVNIT1BQSU5HX0FERF9HVElOECISIQodU0hPUFBJTkdfQUREX01PUkVfSURFTlRJRk'
    'lFUlMQIxIVChFTSE9QUElOR19BRERfU0laRRAkEiUKIVNIT1BQSU5HX0FERF9QUk9EVUNUU19U'
    'T19DQU1QQUlHThAlEiUKIVNIT1BQSU5HX0ZJWF9ESVNBUFBST1ZFRF9QUk9EVUNUUxAmEh4KGl'
    'NIT1BQSU5HX1RBUkdFVF9BTExfT0ZGRVJTECcSMgouU0hPUFBJTkdfRklYX1NVU1BFTkRFRF9N'
    'RVJDSEFOVF9DRU5URVJfQUNDT1VOVBAoEjsKN1NIT1BQSU5HX0ZJWF9NRVJDSEFOVF9DRU5URV'
    'JfQUNDT1VOVF9TVVNQRU5TSU9OX1dBUk5JTkcQKRJICkRTSE9QUElOR19NSUdSQVRFX1JFR1VM'
    'QVJfU0hPUFBJTkdfQ0FNUEFJR05fT0ZGRVJTX1RPX1BFUkZPUk1BTkNFX01BWBAqEiIKHkRZTk'
    'FNSUNfSU1BR0VfRVhURU5TSU9OX09QVF9JThArEhQKEFJBSVNFX1RBUkdFVF9DUEEQLBIVChFM'
    'T1dFUl9UQVJHRVRfUk9BUxAtEhoKFlBFUkZPUk1BTkNFX01BWF9PUFRfSU4QLhInCiNJTVBST1'
    'ZFX1BFUkZPUk1BTkNFX01BWF9BRF9TVFJFTkdUSBAvEjoKNk1JR1JBVEVfRFlOQU1JQ19TRUFS'
    'Q0hfQURTX0NBTVBBSUdOX1RPX1BFUkZPUk1BTkNFX01BWBAwEh4KGkZPUkVDQVNUSU5HX1NFVF'
    '9UQVJHRVRfQ1BBEDESEgoOU0VUX1RBUkdFVF9DUEEQMhITCg9TRVRfVEFSR0VUX1JPQVMQMxIk'
    'CiBNQVhJTUlaRV9DT05WRVJTSU9OX1ZBTFVFX09QVF9JThA0Eh8KG0lNUFJPVkVfR09PR0xFX1'
    'RBR19DT1ZFUkFHRRA1EiQKIFBFUkZPUk1BTkNFX01BWF9GSU5BTF9VUkxfT1BUX0lOEDYSHwob'
    'UkVGUkVTSF9DVVNUT01FUl9NQVRDSF9MSVNUEDcSGgoWQ1VTVE9NX0FVRElFTkNFX09QVF9JTh'
    'A4EhMKD0xFQURfRk9STV9BU1NFVBA5EiIKHklNUFJPVkVfREVNQU5EX0dFTl9BRF9TVFJFTkdU'
    'SBA6');

