//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v15/errors/ad_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use adErrorEnumDescriptor instead')
const AdErrorEnum$json = {
  '1': 'AdErrorEnum',
  '4': [AdErrorEnum_AdError$json],
};

@$core.Deprecated('Use adErrorEnumDescriptor instead')
const AdErrorEnum_AdError$json = {
  '1': 'AdError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'AD_CUSTOMIZERS_NOT_SUPPORTED_FOR_AD_TYPE', '2': 2},
    {'1': 'APPROXIMATELY_TOO_LONG', '2': 3},
    {'1': 'APPROXIMATELY_TOO_SHORT', '2': 4},
    {'1': 'BAD_SNIPPET', '2': 5},
    {'1': 'CANNOT_MODIFY_AD', '2': 6},
    {'1': 'CANNOT_SET_BUSINESS_NAME_IF_URL_SET', '2': 7},
    {'1': 'CANNOT_SET_FIELD', '2': 8},
    {'1': 'CANNOT_SET_FIELD_WITH_ORIGIN_AD_ID_SET', '2': 9},
    {'1': 'CANNOT_SET_FIELD_WITH_AD_ID_SET_FOR_SHARING', '2': 10},
    {'1': 'CANNOT_SET_ALLOW_FLEXIBLE_COLOR_FALSE', '2': 11},
    {'1': 'CANNOT_SET_COLOR_CONTROL_WHEN_NATIVE_FORMAT_SETTING', '2': 12},
    {'1': 'CANNOT_SET_URL', '2': 13},
    {'1': 'CANNOT_SET_WITHOUT_FINAL_URLS', '2': 14},
    {'1': 'CANNOT_SET_WITH_FINAL_URLS', '2': 15},
    {'1': 'CANNOT_SET_WITH_URL_DATA', '2': 17},
    {'1': 'CANNOT_USE_AD_SUBCLASS_FOR_OPERATOR', '2': 18},
    {'1': 'CUSTOMER_NOT_APPROVED_MOBILEADS', '2': 19},
    {'1': 'CUSTOMER_NOT_APPROVED_THIRDPARTY_ADS', '2': 20},
    {'1': 'CUSTOMER_NOT_APPROVED_THIRDPARTY_REDIRECT_ADS', '2': 21},
    {'1': 'CUSTOMER_NOT_ELIGIBLE', '2': 22},
    {'1': 'CUSTOMER_NOT_ELIGIBLE_FOR_UPDATING_BEACON_URL', '2': 23},
    {'1': 'DIMENSION_ALREADY_IN_UNION', '2': 24},
    {'1': 'DIMENSION_MUST_BE_SET', '2': 25},
    {'1': 'DIMENSION_NOT_IN_UNION', '2': 26},
    {'1': 'DISPLAY_URL_CANNOT_BE_SPECIFIED', '2': 27},
    {'1': 'DOMESTIC_PHONE_NUMBER_FORMAT', '2': 28},
    {'1': 'EMERGENCY_PHONE_NUMBER', '2': 29},
    {'1': 'EMPTY_FIELD', '2': 30},
    {'1': 'FEED_ATTRIBUTE_MUST_HAVE_MAPPING_FOR_TYPE_ID', '2': 31},
    {'1': 'FEED_ATTRIBUTE_MAPPING_TYPE_MISMATCH', '2': 32},
    {'1': 'ILLEGAL_AD_CUSTOMIZER_TAG_USE', '2': 33},
    {'1': 'ILLEGAL_TAG_USE', '2': 34},
    {'1': 'INCONSISTENT_DIMENSIONS', '2': 35},
    {'1': 'INCONSISTENT_STATUS_IN_TEMPLATE_UNION', '2': 36},
    {'1': 'INCORRECT_LENGTH', '2': 37},
    {'1': 'INELIGIBLE_FOR_UPGRADE', '2': 38},
    {'1': 'INVALID_AD_ADDRESS_CAMPAIGN_TARGET', '2': 39},
    {'1': 'INVALID_AD_TYPE', '2': 40},
    {'1': 'INVALID_ATTRIBUTES_FOR_MOBILE_IMAGE', '2': 41},
    {'1': 'INVALID_ATTRIBUTES_FOR_MOBILE_TEXT', '2': 42},
    {'1': 'INVALID_CALL_TO_ACTION_TEXT', '2': 43},
    {'1': 'INVALID_CHARACTER_FOR_URL', '2': 44},
    {'1': 'INVALID_COUNTRY_CODE', '2': 45},
    {'1': 'INVALID_EXPANDED_DYNAMIC_SEARCH_AD_TAG', '2': 47},
    {'1': 'INVALID_INPUT', '2': 48},
    {'1': 'INVALID_MARKUP_LANGUAGE', '2': 49},
    {'1': 'INVALID_MOBILE_CARRIER', '2': 50},
    {'1': 'INVALID_MOBILE_CARRIER_TARGET', '2': 51},
    {'1': 'INVALID_NUMBER_OF_ELEMENTS', '2': 52},
    {'1': 'INVALID_PHONE_NUMBER_FORMAT', '2': 53},
    {'1': 'INVALID_RICH_MEDIA_CERTIFIED_VENDOR_FORMAT_ID', '2': 54},
    {'1': 'INVALID_TEMPLATE_DATA', '2': 55},
    {'1': 'INVALID_TEMPLATE_ELEMENT_FIELD_TYPE', '2': 56},
    {'1': 'INVALID_TEMPLATE_ID', '2': 57},
    {'1': 'LINE_TOO_WIDE', '2': 58},
    {'1': 'MISSING_AD_CUSTOMIZER_MAPPING', '2': 59},
    {'1': 'MISSING_ADDRESS_COMPONENT', '2': 60},
    {'1': 'MISSING_ADVERTISEMENT_NAME', '2': 61},
    {'1': 'MISSING_BUSINESS_NAME', '2': 62},
    {'1': 'MISSING_DESCRIPTION1', '2': 63},
    {'1': 'MISSING_DESCRIPTION2', '2': 64},
    {'1': 'MISSING_DESTINATION_URL_TAG', '2': 65},
    {'1': 'MISSING_LANDING_PAGE_URL_TAG', '2': 66},
    {'1': 'MISSING_DIMENSION', '2': 67},
    {'1': 'MISSING_DISPLAY_URL', '2': 68},
    {'1': 'MISSING_HEADLINE', '2': 69},
    {'1': 'MISSING_HEIGHT', '2': 70},
    {'1': 'MISSING_IMAGE', '2': 71},
    {'1': 'MISSING_MARKETING_IMAGE_OR_PRODUCT_VIDEOS', '2': 72},
    {'1': 'MISSING_MARKUP_LANGUAGES', '2': 73},
    {'1': 'MISSING_MOBILE_CARRIER', '2': 74},
    {'1': 'MISSING_PHONE', '2': 75},
    {'1': 'MISSING_REQUIRED_TEMPLATE_FIELDS', '2': 76},
    {'1': 'MISSING_TEMPLATE_FIELD_VALUE', '2': 77},
    {'1': 'MISSING_TEXT', '2': 78},
    {'1': 'MISSING_VISIBLE_URL', '2': 79},
    {'1': 'MISSING_WIDTH', '2': 80},
    {'1': 'MULTIPLE_DISTINCT_FEEDS_UNSUPPORTED', '2': 81},
    {'1': 'MUST_USE_TEMP_AD_UNION_ID_ON_ADD', '2': 82},
    {'1': 'TOO_LONG', '2': 83},
    {'1': 'TOO_SHORT', '2': 84},
    {'1': 'UNION_DIMENSIONS_CANNOT_CHANGE', '2': 85},
    {'1': 'UNKNOWN_ADDRESS_COMPONENT', '2': 86},
    {'1': 'UNKNOWN_FIELD_NAME', '2': 87},
    {'1': 'UNKNOWN_UNIQUE_NAME', '2': 88},
    {'1': 'UNSUPPORTED_DIMENSIONS', '2': 89},
    {'1': 'URL_INVALID_SCHEME', '2': 90},
    {'1': 'URL_INVALID_TOP_LEVEL_DOMAIN', '2': 91},
    {'1': 'URL_MALFORMED', '2': 92},
    {'1': 'URL_NO_HOST', '2': 93},
    {'1': 'URL_NOT_EQUIVALENT', '2': 94},
    {'1': 'URL_HOST_NAME_TOO_LONG', '2': 95},
    {'1': 'URL_NO_SCHEME', '2': 96},
    {'1': 'URL_NO_TOP_LEVEL_DOMAIN', '2': 97},
    {'1': 'URL_PATH_NOT_ALLOWED', '2': 98},
    {'1': 'URL_PORT_NOT_ALLOWED', '2': 99},
    {'1': 'URL_QUERY_NOT_ALLOWED', '2': 100},
    {'1': 'URL_SCHEME_BEFORE_EXPANDED_DYNAMIC_SEARCH_AD_TAG', '2': 102},
    {'1': 'USER_DOES_NOT_HAVE_ACCESS_TO_TEMPLATE', '2': 103},
    {'1': 'INCONSISTENT_EXPANDABLE_SETTINGS', '2': 104},
    {'1': 'INVALID_FORMAT', '2': 105},
    {'1': 'INVALID_FIELD_TEXT', '2': 106},
    {'1': 'ELEMENT_NOT_PRESENT', '2': 107},
    {'1': 'IMAGE_ERROR', '2': 108},
    {'1': 'VALUE_NOT_IN_RANGE', '2': 109},
    {'1': 'FIELD_NOT_PRESENT', '2': 110},
    {'1': 'ADDRESS_NOT_COMPLETE', '2': 111},
    {'1': 'ADDRESS_INVALID', '2': 112},
    {'1': 'VIDEO_RETRIEVAL_ERROR', '2': 113},
    {'1': 'AUDIO_ERROR', '2': 114},
    {'1': 'INVALID_YOUTUBE_DISPLAY_URL', '2': 115},
    {'1': 'TOO_MANY_PRODUCT_IMAGES', '2': 116},
    {'1': 'TOO_MANY_PRODUCT_VIDEOS', '2': 117},
    {'1': 'INCOMPATIBLE_AD_TYPE_AND_DEVICE_PREFERENCE', '2': 118},
    {'1': 'CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY', '2': 119},
    {'1': 'CARRIER_SPECIFIC_SHORT_NUMBER_NOT_ALLOWED', '2': 120},
    {'1': 'DISALLOWED_NUMBER_TYPE', '2': 121},
    {'1': 'PHONE_NUMBER_NOT_SUPPORTED_FOR_COUNTRY', '2': 122},
    {'1': 'PHONE_NUMBER_NOT_SUPPORTED_WITH_CALLTRACKING_FOR_COUNTRY', '2': 123},
    {'1': 'PREMIUM_RATE_NUMBER_NOT_ALLOWED', '2': 124},
    {'1': 'VANITY_PHONE_NUMBER_NOT_ALLOWED', '2': 125},
    {'1': 'INVALID_CALL_CONVERSION_TYPE_ID', '2': 126},
    {'1': 'CANNOT_DISABLE_CALL_CONVERSION_AND_SET_CONVERSION_TYPE_ID', '2': 127},
    {'1': 'CANNOT_SET_PATH2_WITHOUT_PATH1', '2': 128},
    {'1': 'MISSING_DYNAMIC_SEARCH_ADS_SETTING_DOMAIN_NAME', '2': 129},
    {'1': 'INCOMPATIBLE_WITH_RESTRICTION_TYPE', '2': 130},
    {'1': 'CUSTOMER_CONSENT_FOR_CALL_RECORDING_REQUIRED', '2': 131},
    {'1': 'MISSING_IMAGE_OR_MEDIA_BUNDLE', '2': 132},
    {'1': 'PRODUCT_TYPE_NOT_SUPPORTED_IN_THIS_CAMPAIGN', '2': 133},
    {'1': 'PLACEHOLDER_CANNOT_HAVE_EMPTY_DEFAULT_VALUE', '2': 134},
    {'1': 'PLACEHOLDER_COUNTDOWN_FUNCTION_CANNOT_HAVE_DEFAULT_VALUE', '2': 135},
    {'1': 'PLACEHOLDER_DEFAULT_VALUE_MISSING', '2': 136},
    {'1': 'UNEXPECTED_PLACEHOLDER_DEFAULT_VALUE', '2': 137},
    {'1': 'AD_CUSTOMIZERS_MAY_NOT_BE_ADJACENT', '2': 138},
    {'1': 'UPDATING_AD_WITH_NO_ENABLED_ASSOCIATION', '2': 139},
    {'1': 'CALL_AD_VERIFICATION_URL_FINAL_URL_DOES_NOT_HAVE_SAME_DOMAIN', '2': 140},
    {'1': 'CALL_AD_FINAL_URL_AND_VERIFICATION_URL_CANNOT_BOTH_BE_EMPTY', '2': 154},
    {'1': 'TOO_MANY_AD_CUSTOMIZERS', '2': 141},
    {'1': 'INVALID_AD_CUSTOMIZER_FORMAT', '2': 142},
    {'1': 'NESTED_AD_CUSTOMIZER_SYNTAX', '2': 143},
    {'1': 'UNSUPPORTED_AD_CUSTOMIZER_SYNTAX', '2': 144},
    {'1': 'UNPAIRED_BRACE_IN_AD_CUSTOMIZER_TAG', '2': 145},
    {'1': 'MORE_THAN_ONE_COUNTDOWN_TAG_TYPE_EXISTS', '2': 146},
    {'1': 'DATE_TIME_IN_COUNTDOWN_TAG_IS_INVALID', '2': 147},
    {'1': 'DATE_TIME_IN_COUNTDOWN_TAG_IS_PAST', '2': 148},
    {'1': 'UNRECOGNIZED_AD_CUSTOMIZER_TAG_FOUND', '2': 149},
    {'1': 'CUSTOMIZER_TYPE_FORBIDDEN_FOR_FIELD', '2': 150},
    {'1': 'INVALID_CUSTOMIZER_ATTRIBUTE_NAME', '2': 151},
    {'1': 'STORE_MISMATCH', '2': 152},
    {'1': 'MISSING_REQUIRED_IMAGE_ASPECT_RATIO', '2': 153},
    {'1': 'MISMATCHED_ASPECT_RATIOS', '2': 155},
    {'1': 'DUPLICATE_IMAGE_ACROSS_CAROUSEL_CARDS', '2': 156},
  ],
};

/// Descriptor for `AdErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List adErrorEnumDescriptor = $convert.base64Decode(
    'CgtBZEVycm9yRW51bSK+KAoHQWRFcnJvchIPCgtVTlNQRUNJRklFRBAAEgsKB1VOS05PV04QAR'
    'IsCihBRF9DVVNUT01JWkVSU19OT1RfU1VQUE9SVEVEX0ZPUl9BRF9UWVBFEAISGgoWQVBQUk9Y'
    'SU1BVEVMWV9UT09fTE9ORxADEhsKF0FQUFJPWElNQVRFTFlfVE9PX1NIT1JUEAQSDwoLQkFEX1'
    'NOSVBQRVQQBRIUChBDQU5OT1RfTU9ESUZZX0FEEAYSJwojQ0FOTk9UX1NFVF9CVVNJTkVTU19O'
    'QU1FX0lGX1VSTF9TRVQQBxIUChBDQU5OT1RfU0VUX0ZJRUxEEAgSKgomQ0FOTk9UX1NFVF9GSU'
    'VMRF9XSVRIX09SSUdJTl9BRF9JRF9TRVQQCRIvCitDQU5OT1RfU0VUX0ZJRUxEX1dJVEhfQURf'
    'SURfU0VUX0ZPUl9TSEFSSU5HEAoSKQolQ0FOTk9UX1NFVF9BTExPV19GTEVYSUJMRV9DT0xPUl'
    '9GQUxTRRALEjcKM0NBTk5PVF9TRVRfQ09MT1JfQ09OVFJPTF9XSEVOX05BVElWRV9GT1JNQVRf'
    'U0VUVElORxAMEhIKDkNBTk5PVF9TRVRfVVJMEA0SIQodQ0FOTk9UX1NFVF9XSVRIT1VUX0ZJTk'
    'FMX1VSTFMQDhIeChpDQU5OT1RfU0VUX1dJVEhfRklOQUxfVVJMUxAPEhwKGENBTk5PVF9TRVRf'
    'V0lUSF9VUkxfREFUQRAREicKI0NBTk5PVF9VU0VfQURfU1VCQ0xBU1NfRk9SX09QRVJBVE9SEB'
    'ISIwofQ1VTVE9NRVJfTk9UX0FQUFJPVkVEX01PQklMRUFEUxATEigKJENVU1RPTUVSX05PVF9B'
    'UFBST1ZFRF9USElSRFBBUlRZX0FEUxAUEjEKLUNVU1RPTUVSX05PVF9BUFBST1ZFRF9USElSRF'
    'BBUlRZX1JFRElSRUNUX0FEUxAVEhkKFUNVU1RPTUVSX05PVF9FTElHSUJMRRAWEjEKLUNVU1RP'
    'TUVSX05PVF9FTElHSUJMRV9GT1JfVVBEQVRJTkdfQkVBQ09OX1VSTBAXEh4KGkRJTUVOU0lPTl'
    '9BTFJFQURZX0lOX1VOSU9OEBgSGQoVRElNRU5TSU9OX01VU1RfQkVfU0VUEBkSGgoWRElNRU5T'
    'SU9OX05PVF9JTl9VTklPThAaEiMKH0RJU1BMQVlfVVJMX0NBTk5PVF9CRV9TUEVDSUZJRUQQGx'
    'IgChxET01FU1RJQ19QSE9ORV9OVU1CRVJfRk9STUFUEBwSGgoWRU1FUkdFTkNZX1BIT05FX05V'
    'TUJFUhAdEg8KC0VNUFRZX0ZJRUxEEB4SMAosRkVFRF9BVFRSSUJVVEVfTVVTVF9IQVZFX01BUF'
    'BJTkdfRk9SX1RZUEVfSUQQHxIoCiRGRUVEX0FUVFJJQlVURV9NQVBQSU5HX1RZUEVfTUlTTUFU'
    'Q0gQIBIhCh1JTExFR0FMX0FEX0NVU1RPTUlaRVJfVEFHX1VTRRAhEhMKD0lMTEVHQUxfVEFHX1'
    'VTRRAiEhsKF0lOQ09OU0lTVEVOVF9ESU1FTlNJT05TECMSKQolSU5DT05TSVNURU5UX1NUQVRV'
    'U19JTl9URU1QTEFURV9VTklPThAkEhQKEElOQ09SUkVDVF9MRU5HVEgQJRIaChZJTkVMSUdJQk'
    'xFX0ZPUl9VUEdSQURFECYSJgoiSU5WQUxJRF9BRF9BRERSRVNTX0NBTVBBSUdOX1RBUkdFVBAn'
    'EhMKD0lOVkFMSURfQURfVFlQRRAoEicKI0lOVkFMSURfQVRUUklCVVRFU19GT1JfTU9CSUxFX0'
    'lNQUdFECkSJgoiSU5WQUxJRF9BVFRSSUJVVEVTX0ZPUl9NT0JJTEVfVEVYVBAqEh8KG0lOVkFM'
    'SURfQ0FMTF9UT19BQ1RJT05fVEVYVBArEh0KGUlOVkFMSURfQ0hBUkFDVEVSX0ZPUl9VUkwQLB'
    'IYChRJTlZBTElEX0NPVU5UUllfQ09ERRAtEioKJklOVkFMSURfRVhQQU5ERURfRFlOQU1JQ19T'
    'RUFSQ0hfQURfVEFHEC8SEQoNSU5WQUxJRF9JTlBVVBAwEhsKF0lOVkFMSURfTUFSS1VQX0xBTk'
    'dVQUdFEDESGgoWSU5WQUxJRF9NT0JJTEVfQ0FSUklFUhAyEiEKHUlOVkFMSURfTU9CSUxFX0NB'
    'UlJJRVJfVEFSR0VUEDMSHgoaSU5WQUxJRF9OVU1CRVJfT0ZfRUxFTUVOVFMQNBIfChtJTlZBTE'
    'lEX1BIT05FX05VTUJFUl9GT1JNQVQQNRIxCi1JTlZBTElEX1JJQ0hfTUVESUFfQ0VSVElGSUVE'
    'X1ZFTkRPUl9GT1JNQVRfSUQQNhIZChVJTlZBTElEX1RFTVBMQVRFX0RBVEEQNxInCiNJTlZBTE'
    'lEX1RFTVBMQVRFX0VMRU1FTlRfRklFTERfVFlQRRA4EhcKE0lOVkFMSURfVEVNUExBVEVfSUQQ'
    'ORIRCg1MSU5FX1RPT19XSURFEDoSIQodTUlTU0lOR19BRF9DVVNUT01JWkVSX01BUFBJTkcQOx'
    'IdChlNSVNTSU5HX0FERFJFU1NfQ09NUE9ORU5UEDwSHgoaTUlTU0lOR19BRFZFUlRJU0VNRU5U'
    'X05BTUUQPRIZChVNSVNTSU5HX0JVU0lORVNTX05BTUUQPhIYChRNSVNTSU5HX0RFU0NSSVBUSU'
    '9OMRA/EhgKFE1JU1NJTkdfREVTQ1JJUFRJT04yEEASHwobTUlTU0lOR19ERVNUSU5BVElPTl9V'
    'UkxfVEFHEEESIAocTUlTU0lOR19MQU5ESU5HX1BBR0VfVVJMX1RBRxBCEhUKEU1JU1NJTkdfRE'
    'lNRU5TSU9OEEMSFwoTTUlTU0lOR19ESVNQTEFZX1VSTBBEEhQKEE1JU1NJTkdfSEVBRExJTkUQ'
    'RRISCg5NSVNTSU5HX0hFSUdIVBBGEhEKDU1JU1NJTkdfSU1BR0UQRxItCilNSVNTSU5HX01BUk'
    'tFVElOR19JTUFHRV9PUl9QUk9EVUNUX1ZJREVPUxBIEhwKGE1JU1NJTkdfTUFSS1VQX0xBTkdV'
    'QUdFUxBJEhoKFk1JU1NJTkdfTU9CSUxFX0NBUlJJRVIQShIRCg1NSVNTSU5HX1BIT05FEEsSJA'
    'ogTUlTU0lOR19SRVFVSVJFRF9URU1QTEFURV9GSUVMRFMQTBIgChxNSVNTSU5HX1RFTVBMQVRF'
    'X0ZJRUxEX1ZBTFVFEE0SEAoMTUlTU0lOR19URVhUEE4SFwoTTUlTU0lOR19WSVNJQkxFX1VSTB'
    'BPEhEKDU1JU1NJTkdfV0lEVEgQUBInCiNNVUxUSVBMRV9ESVNUSU5DVF9GRUVEU19VTlNVUFBP'
    'UlRFRBBREiQKIE1VU1RfVVNFX1RFTVBfQURfVU5JT05fSURfT05fQUREEFISDAoIVE9PX0xPTk'
    'cQUxINCglUT09fU0hPUlQQVBIiCh5VTklPTl9ESU1FTlNJT05TX0NBTk5PVF9DSEFOR0UQVRId'
    'ChlVTktOT1dOX0FERFJFU1NfQ09NUE9ORU5UEFYSFgoSVU5LTk9XTl9GSUVMRF9OQU1FEFcSFw'
    'oTVU5LTk9XTl9VTklRVUVfTkFNRRBYEhoKFlVOU1VQUE9SVEVEX0RJTUVOU0lPTlMQWRIWChJV'
    'UkxfSU5WQUxJRF9TQ0hFTUUQWhIgChxVUkxfSU5WQUxJRF9UT1BfTEVWRUxfRE9NQUlOEFsSEQ'
    'oNVVJMX01BTEZPUk1FRBBcEg8KC1VSTF9OT19IT1NUEF0SFgoSVVJMX05PVF9FUVVJVkFMRU5U'
    'EF4SGgoWVVJMX0hPU1RfTkFNRV9UT09fTE9ORxBfEhEKDVVSTF9OT19TQ0hFTUUQYBIbChdVUk'
    'xfTk9fVE9QX0xFVkVMX0RPTUFJThBhEhgKFFVSTF9QQVRIX05PVF9BTExPV0VEEGISGAoUVVJM'
    'X1BPUlRfTk9UX0FMTE9XRUQQYxIZChVVUkxfUVVFUllfTk9UX0FMTE9XRUQQZBI0CjBVUkxfU0'
    'NIRU1FX0JFRk9SRV9FWFBBTkRFRF9EWU5BTUlDX1NFQVJDSF9BRF9UQUcQZhIpCiVVU0VSX0RP'
    'RVNfTk9UX0hBVkVfQUNDRVNTX1RPX1RFTVBMQVRFEGcSJAogSU5DT05TSVNURU5UX0VYUEFORE'
    'FCTEVfU0VUVElOR1MQaBISCg5JTlZBTElEX0ZPUk1BVBBpEhYKEklOVkFMSURfRklFTERfVEVY'
    'VBBqEhcKE0VMRU1FTlRfTk9UX1BSRVNFTlQQaxIPCgtJTUFHRV9FUlJPUhBsEhYKElZBTFVFX0'
    '5PVF9JTl9SQU5HRRBtEhUKEUZJRUxEX05PVF9QUkVTRU5UEG4SGAoUQUREUkVTU19OT1RfQ09N'
    'UExFVEUQbxITCg9BRERSRVNTX0lOVkFMSUQQcBIZChVWSURFT19SRVRSSUVWQUxfRVJST1IQcR'
    'IPCgtBVURJT19FUlJPUhByEh8KG0lOVkFMSURfWU9VVFVCRV9ESVNQTEFZX1VSTBBzEhsKF1RP'
    'T19NQU5ZX1BST0RVQ1RfSU1BR0VTEHQSGwoXVE9PX01BTllfUFJPRFVDVF9WSURFT1MQdRIuCi'
    'pJTkNPTVBBVElCTEVfQURfVFlQRV9BTkRfREVWSUNFX1BSRUZFUkVOQ0UQdhIqCiZDQUxMVFJB'
    'Q0tJTkdfTk9UX1NVUFBPUlRFRF9GT1JfQ09VTlRSWRB3Ei0KKUNBUlJJRVJfU1BFQ0lGSUNfU0'
    'hPUlRfTlVNQkVSX05PVF9BTExPV0VEEHgSGgoWRElTQUxMT1dFRF9OVU1CRVJfVFlQRRB5EioK'
    'JlBIT05FX05VTUJFUl9OT1RfU1VQUE9SVEVEX0ZPUl9DT1VOVFJZEHoSPAo4UEhPTkVfTlVNQk'
    'VSX05PVF9TVVBQT1JURURfV0lUSF9DQUxMVFJBQ0tJTkdfRk9SX0NPVU5UUlkQexIjCh9QUkVN'
    'SVVNX1JBVEVfTlVNQkVSX05PVF9BTExPV0VEEHwSIwofVkFOSVRZX1BIT05FX05VTUJFUl9OT1'
    'RfQUxMT1dFRBB9EiMKH0lOVkFMSURfQ0FMTF9DT05WRVJTSU9OX1RZUEVfSUQQfhI9CjlDQU5O'
    'T1RfRElTQUJMRV9DQUxMX0NPTlZFUlNJT05fQU5EX1NFVF9DT05WRVJTSU9OX1RZUEVfSUQQfx'
    'IjCh5DQU5OT1RfU0VUX1BBVEgyX1dJVEhPVVRfUEFUSDEQgAESMwouTUlTU0lOR19EWU5BTUlD'
    'X1NFQVJDSF9BRFNfU0VUVElOR19ET01BSU5fTkFNRRCBARInCiJJTkNPTVBBVElCTEVfV0lUSF'
    '9SRVNUUklDVElPTl9UWVBFEIIBEjEKLENVU1RPTUVSX0NPTlNFTlRfRk9SX0NBTExfUkVDT1JE'
    'SU5HX1JFUVVJUkVEEIMBEiIKHU1JU1NJTkdfSU1BR0VfT1JfTUVESUFfQlVORExFEIQBEjAKK1'
    'BST0RVQ1RfVFlQRV9OT1RfU1VQUE9SVEVEX0lOX1RISVNfQ0FNUEFJR04QhQESMAorUExBQ0VI'
    'T0xERVJfQ0FOTk9UX0hBVkVfRU1QVFlfREVGQVVMVF9WQUxVRRCGARI9CjhQTEFDRUhPTERFUl'
    '9DT1VOVERPV05fRlVOQ1RJT05fQ0FOTk9UX0hBVkVfREVGQVVMVF9WQUxVRRCHARImCiFQTEFD'
    'RUhPTERFUl9ERUZBVUxUX1ZBTFVFX01JU1NJTkcQiAESKQokVU5FWFBFQ1RFRF9QTEFDRUhPTE'
    'RFUl9ERUZBVUxUX1ZBTFVFEIkBEicKIkFEX0NVU1RPTUlaRVJTX01BWV9OT1RfQkVfQURKQUNF'
    'TlQQigESLAonVVBEQVRJTkdfQURfV0lUSF9OT19FTkFCTEVEX0FTU09DSUFUSU9OEIsBEkEKPE'
    'NBTExfQURfVkVSSUZJQ0FUSU9OX1VSTF9GSU5BTF9VUkxfRE9FU19OT1RfSEFWRV9TQU1FX0RP'
    'TUFJThCMARJACjtDQUxMX0FEX0ZJTkFMX1VSTF9BTkRfVkVSSUZJQ0FUSU9OX1VSTF9DQU5OT1'
    'RfQk9USF9CRV9FTVBUWRCaARIcChdUT09fTUFOWV9BRF9DVVNUT01JWkVSUxCNARIhChxJTlZB'
    'TElEX0FEX0NVU1RPTUlaRVJfRk9STUFUEI4BEiAKG05FU1RFRF9BRF9DVVNUT01JWkVSX1NZTl'
    'RBWBCPARIlCiBVTlNVUFBPUlRFRF9BRF9DVVNUT01JWkVSX1NZTlRBWBCQARIoCiNVTlBBSVJF'
    'RF9CUkFDRV9JTl9BRF9DVVNUT01JWkVSX1RBRxCRARIsCidNT1JFX1RIQU5fT05FX0NPVU5URE'
    '9XTl9UQUdfVFlQRV9FWElTVFMQkgESKgolREFURV9USU1FX0lOX0NPVU5URE9XTl9UQUdfSVNf'
    'SU5WQUxJRBCTARInCiJEQVRFX1RJTUVfSU5fQ09VTlRET1dOX1RBR19JU19QQVNUEJQBEikKJF'
    'VOUkVDT0dOSVpFRF9BRF9DVVNUT01JWkVSX1RBR19GT1VORBCVARIoCiNDVVNUT01JWkVSX1RZ'
    'UEVfRk9SQklEREVOX0ZPUl9GSUVMRBCWARImCiFJTlZBTElEX0NVU1RPTUlaRVJfQVRUUklCVV'
    'RFX05BTUUQlwESEwoOU1RPUkVfTUlTTUFUQ0gQmAESKAojTUlTU0lOR19SRVFVSVJFRF9JTUFH'
    'RV9BU1BFQ1RfUkFUSU8QmQESHQoYTUlTTUFUQ0hFRF9BU1BFQ1RfUkFUSU9TEJsBEioKJURVUE'
    'xJQ0FURV9JTUFHRV9BQ1JPU1NfQ0FST1VTRUxfQ0FSRFMQnAE=');

