//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v15/errors/asset_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use assetErrorEnumDescriptor instead')
const AssetErrorEnum$json = {
  '1': 'AssetErrorEnum',
  '4': [AssetErrorEnum_AssetError$json],
};

@$core.Deprecated('Use assetErrorEnumDescriptor instead')
const AssetErrorEnum_AssetError$json = {
  '1': 'AssetError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'CUSTOMER_NOT_ON_ALLOWLIST_FOR_ASSET_TYPE', '2': 13},
    {'1': 'DUPLICATE_ASSET', '2': 3},
    {'1': 'DUPLICATE_ASSET_NAME', '2': 4},
    {'1': 'ASSET_DATA_IS_MISSING', '2': 5},
    {'1': 'CANNOT_MODIFY_ASSET_NAME', '2': 6},
    {'1': 'FIELD_INCOMPATIBLE_WITH_ASSET_TYPE', '2': 7},
    {'1': 'INVALID_CALL_TO_ACTION_TEXT', '2': 8},
    {'1': 'LEAD_FORM_INVALID_FIELDS_COMBINATION', '2': 9},
    {'1': 'LEAD_FORM_MISSING_AGREEMENT', '2': 10},
    {'1': 'INVALID_ASSET_STATUS', '2': 11},
    {'1': 'FIELD_CANNOT_BE_MODIFIED_FOR_ASSET_TYPE', '2': 12},
    {'1': 'SCHEDULES_CANNOT_OVERLAP', '2': 14},
    {'1': 'PROMOTION_CANNOT_SET_PERCENT_OFF_AND_MONEY_AMOUNT_OFF', '2': 15},
    {'1': 'PROMOTION_CANNOT_SET_PROMOTION_CODE_AND_ORDERS_OVER_AMOUNT', '2': 16},
    {'1': 'TOO_MANY_DECIMAL_PLACES_SPECIFIED', '2': 17},
    {'1': 'DUPLICATE_ASSETS_WITH_DIFFERENT_FIELD_VALUE', '2': 18},
    {'1': 'CALL_CARRIER_SPECIFIC_SHORT_NUMBER_NOT_ALLOWED', '2': 19},
    {'1': 'CALL_CUSTOMER_CONSENT_FOR_CALL_RECORDING_REQUIRED', '2': 20},
    {'1': 'CALL_DISALLOWED_NUMBER_TYPE', '2': 21},
    {'1': 'CALL_INVALID_CONVERSION_ACTION', '2': 22},
    {'1': 'CALL_INVALID_COUNTRY_CODE', '2': 23},
    {'1': 'CALL_INVALID_DOMESTIC_PHONE_NUMBER_FORMAT', '2': 24},
    {'1': 'CALL_INVALID_PHONE_NUMBER', '2': 25},
    {'1': 'CALL_PHONE_NUMBER_NOT_SUPPORTED_FOR_COUNTRY', '2': 26},
    {'1': 'CALL_PREMIUM_RATE_NUMBER_NOT_ALLOWED', '2': 27},
    {'1': 'CALL_VANITY_PHONE_NUMBER_NOT_ALLOWED', '2': 28},
    {'1': 'PRICE_HEADER_SAME_AS_DESCRIPTION', '2': 29},
    {'1': 'MOBILE_APP_INVALID_APP_ID', '2': 30},
    {'1': 'MOBILE_APP_INVALID_FINAL_URL_FOR_APP_DOWNLOAD_URL', '2': 31},
    {'1': 'NAME_REQUIRED_FOR_ASSET_TYPE', '2': 32},
    {'1': 'LEAD_FORM_LEGACY_QUALIFYING_QUESTIONS_DISALLOWED', '2': 33},
    {'1': 'NAME_CONFLICT_FOR_ASSET_TYPE', '2': 34},
    {'1': 'CANNOT_MODIFY_ASSET_SOURCE', '2': 35},
    {'1': 'CANNOT_MODIFY_AUTOMATICALLY_CREATED_ASSET', '2': 36},
    {'1': 'LEAD_FORM_LOCATION_ANSWER_TYPE_DISALLOWED', '2': 37},
    {'1': 'PAGE_FEED_INVALID_LABEL_TEXT', '2': 38},
  ],
};

/// Descriptor for `AssetErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List assetErrorEnumDescriptor = $convert.base64Decode(
    'Cg5Bc3NldEVycm9yRW51bSLECwoKQXNzZXRFcnJvchIPCgtVTlNQRUNJRklFRBAAEgsKB1VOS0'
    '5PV04QARIsCihDVVNUT01FUl9OT1RfT05fQUxMT1dMSVNUX0ZPUl9BU1NFVF9UWVBFEA0SEwoP'
    'RFVQTElDQVRFX0FTU0VUEAMSGAoURFVQTElDQVRFX0FTU0VUX05BTUUQBBIZChVBU1NFVF9EQV'
    'RBX0lTX01JU1NJTkcQBRIcChhDQU5OT1RfTU9ESUZZX0FTU0VUX05BTUUQBhImCiJGSUVMRF9J'
    'TkNPTVBBVElCTEVfV0lUSF9BU1NFVF9UWVBFEAcSHwobSU5WQUxJRF9DQUxMX1RPX0FDVElPTl'
    '9URVhUEAgSKAokTEVBRF9GT1JNX0lOVkFMSURfRklFTERTX0NPTUJJTkFUSU9OEAkSHwobTEVB'
    'RF9GT1JNX01JU1NJTkdfQUdSRUVNRU5UEAoSGAoUSU5WQUxJRF9BU1NFVF9TVEFUVVMQCxIrCi'
    'dGSUVMRF9DQU5OT1RfQkVfTU9ESUZJRURfRk9SX0FTU0VUX1RZUEUQDBIcChhTQ0hFRFVMRVNf'
    'Q0FOTk9UX09WRVJMQVAQDhI5CjVQUk9NT1RJT05fQ0FOTk9UX1NFVF9QRVJDRU5UX09GRl9BTk'
    'RfTU9ORVlfQU1PVU5UX09GRhAPEj4KOlBST01PVElPTl9DQU5OT1RfU0VUX1BST01PVElPTl9D'
    'T0RFX0FORF9PUkRFUlNfT1ZFUl9BTU9VTlQQEBIlCiFUT09fTUFOWV9ERUNJTUFMX1BMQUNFU1'
    '9TUEVDSUZJRUQQERIvCitEVVBMSUNBVEVfQVNTRVRTX1dJVEhfRElGRkVSRU5UX0ZJRUxEX1ZB'
    'TFVFEBISMgouQ0FMTF9DQVJSSUVSX1NQRUNJRklDX1NIT1JUX05VTUJFUl9OT1RfQUxMT1dFRB'
    'ATEjUKMUNBTExfQ1VTVE9NRVJfQ09OU0VOVF9GT1JfQ0FMTF9SRUNPUkRJTkdfUkVRVUlSRUQQ'
    'FBIfChtDQUxMX0RJU0FMTE9XRURfTlVNQkVSX1RZUEUQFRIiCh5DQUxMX0lOVkFMSURfQ09OVk'
    'VSU0lPTl9BQ1RJT04QFhIdChlDQUxMX0lOVkFMSURfQ09VTlRSWV9DT0RFEBcSLQopQ0FMTF9J'
    'TlZBTElEX0RPTUVTVElDX1BIT05FX05VTUJFUl9GT1JNQVQQGBIdChlDQUxMX0lOVkFMSURfUE'
    'hPTkVfTlVNQkVSEBkSLworQ0FMTF9QSE9ORV9OVU1CRVJfTk9UX1NVUFBPUlRFRF9GT1JfQ09V'
    'TlRSWRAaEigKJENBTExfUFJFTUlVTV9SQVRFX05VTUJFUl9OT1RfQUxMT1dFRBAbEigKJENBTE'
    'xfVkFOSVRZX1BIT05FX05VTUJFUl9OT1RfQUxMT1dFRBAcEiQKIFBSSUNFX0hFQURFUl9TQU1F'
    'X0FTX0RFU0NSSVBUSU9OEB0SHQoZTU9CSUxFX0FQUF9JTlZBTElEX0FQUF9JRBAeEjUKMU1PQk'
    'lMRV9BUFBfSU5WQUxJRF9GSU5BTF9VUkxfRk9SX0FQUF9ET1dOTE9BRF9VUkwQHxIgChxOQU1F'
    'X1JFUVVJUkVEX0ZPUl9BU1NFVF9UWVBFECASNAowTEVBRF9GT1JNX0xFR0FDWV9RVUFMSUZZSU'
    '5HX1FVRVNUSU9OU19ESVNBTExPV0VEECESIAocTkFNRV9DT05GTElDVF9GT1JfQVNTRVRfVFlQ'
    'RRAiEh4KGkNBTk5PVF9NT0RJRllfQVNTRVRfU09VUkNFECMSLQopQ0FOTk9UX01PRElGWV9BVV'
    'RPTUFUSUNBTExZX0NSRUFURURfQVNTRVQQJBItCilMRUFEX0ZPUk1fTE9DQVRJT05fQU5TV0VS'
    'X1RZUEVfRElTQUxMT1dFRBAlEiAKHFBBR0VfRkVFRF9JTlZBTElEX0xBQkVMX1RFWFQQJg==');

