//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v15/errors/feed_item_validation_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use feedItemValidationErrorEnumDescriptor instead')
const FeedItemValidationErrorEnum$json = {
  '1': 'FeedItemValidationErrorEnum',
  '4': [FeedItemValidationErrorEnum_FeedItemValidationError$json],
};

@$core.Deprecated('Use feedItemValidationErrorEnumDescriptor instead')
const FeedItemValidationErrorEnum_FeedItemValidationError$json = {
  '1': 'FeedItemValidationError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'STRING_TOO_SHORT', '2': 2},
    {'1': 'STRING_TOO_LONG', '2': 3},
    {'1': 'VALUE_NOT_SPECIFIED', '2': 4},
    {'1': 'INVALID_DOMESTIC_PHONE_NUMBER_FORMAT', '2': 5},
    {'1': 'INVALID_PHONE_NUMBER', '2': 6},
    {'1': 'PHONE_NUMBER_NOT_SUPPORTED_FOR_COUNTRY', '2': 7},
    {'1': 'PREMIUM_RATE_NUMBER_NOT_ALLOWED', '2': 8},
    {'1': 'DISALLOWED_NUMBER_TYPE', '2': 9},
    {'1': 'VALUE_OUT_OF_RANGE', '2': 10},
    {'1': 'CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY', '2': 11},
    {'1': 'CUSTOMER_NOT_IN_ALLOWLIST_FOR_CALLTRACKING', '2': 99},
    {'1': 'INVALID_COUNTRY_CODE', '2': 13},
    {'1': 'INVALID_APP_ID', '2': 14},
    {'1': 'MISSING_ATTRIBUTES_FOR_FIELDS', '2': 15},
    {'1': 'INVALID_TYPE_ID', '2': 16},
    {'1': 'INVALID_EMAIL_ADDRESS', '2': 17},
    {'1': 'INVALID_HTTPS_URL', '2': 18},
    {'1': 'MISSING_DELIVERY_ADDRESS', '2': 19},
    {'1': 'START_DATE_AFTER_END_DATE', '2': 20},
    {'1': 'MISSING_FEED_ITEM_START_TIME', '2': 21},
    {'1': 'MISSING_FEED_ITEM_END_TIME', '2': 22},
    {'1': 'MISSING_FEED_ITEM_ID', '2': 23},
    {'1': 'VANITY_PHONE_NUMBER_NOT_ALLOWED', '2': 24},
    {'1': 'INVALID_REVIEW_EXTENSION_SNIPPET', '2': 25},
    {'1': 'INVALID_NUMBER_FORMAT', '2': 26},
    {'1': 'INVALID_DATE_FORMAT', '2': 27},
    {'1': 'INVALID_PRICE_FORMAT', '2': 28},
    {'1': 'UNKNOWN_PLACEHOLDER_FIELD', '2': 29},
    {'1': 'MISSING_ENHANCED_SITELINK_DESCRIPTION_LINE', '2': 30},
    {'1': 'REVIEW_EXTENSION_SOURCE_INELIGIBLE', '2': 31},
    {'1': 'HYPHENS_IN_REVIEW_EXTENSION_SNIPPET', '2': 32},
    {'1': 'DOUBLE_QUOTES_IN_REVIEW_EXTENSION_SNIPPET', '2': 33},
    {'1': 'QUOTES_IN_REVIEW_EXTENSION_SNIPPET', '2': 34},
    {'1': 'INVALID_FORM_ENCODED_PARAMS', '2': 35},
    {'1': 'INVALID_URL_PARAMETER_NAME', '2': 36},
    {'1': 'NO_GEOCODING_RESULT', '2': 37},
    {'1': 'SOURCE_NAME_IN_REVIEW_EXTENSION_TEXT', '2': 38},
    {'1': 'CARRIER_SPECIFIC_SHORT_NUMBER_NOT_ALLOWED', '2': 39},
    {'1': 'INVALID_PLACEHOLDER_FIELD_ID', '2': 40},
    {'1': 'INVALID_URL_TAG', '2': 41},
    {'1': 'LIST_TOO_LONG', '2': 42},
    {'1': 'INVALID_ATTRIBUTES_COMBINATION', '2': 43},
    {'1': 'DUPLICATE_VALUES', '2': 44},
    {'1': 'INVALID_CALL_CONVERSION_ACTION_ID', '2': 45},
    {'1': 'CANNOT_SET_WITHOUT_FINAL_URLS', '2': 46},
    {'1': 'APP_ID_DOESNT_EXIST_IN_APP_STORE', '2': 47},
    {'1': 'INVALID_FINAL_URL', '2': 48},
    {'1': 'INVALID_TRACKING_URL', '2': 49},
    {'1': 'INVALID_FINAL_URL_FOR_APP_DOWNLOAD_URL', '2': 50},
    {'1': 'LIST_TOO_SHORT', '2': 51},
    {'1': 'INVALID_USER_ACTION', '2': 52},
    {'1': 'INVALID_TYPE_NAME', '2': 53},
    {'1': 'INVALID_EVENT_CHANGE_STATUS', '2': 54},
    {'1': 'INVALID_SNIPPETS_HEADER', '2': 55},
    {'1': 'INVALID_ANDROID_APP_LINK', '2': 56},
    {'1': 'NUMBER_TYPE_WITH_CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY', '2': 57},
    {'1': 'RESERVED_KEYWORD_OTHER', '2': 58},
    {'1': 'DUPLICATE_OPTION_LABELS', '2': 59},
    {'1': 'DUPLICATE_OPTION_PREFILLS', '2': 60},
    {'1': 'UNEQUAL_LIST_LENGTHS', '2': 61},
    {'1': 'INCONSISTENT_CURRENCY_CODES', '2': 62},
    {'1': 'PRICE_EXTENSION_HAS_DUPLICATED_HEADERS', '2': 63},
    {'1': 'ITEM_HAS_DUPLICATED_HEADER_AND_DESCRIPTION', '2': 64},
    {'1': 'PRICE_EXTENSION_HAS_TOO_FEW_ITEMS', '2': 65},
    {'1': 'UNSUPPORTED_VALUE', '2': 66},
    {'1': 'INVALID_FINAL_MOBILE_URL', '2': 67},
    {'1': 'INVALID_KEYWORDLESS_AD_RULE_LABEL', '2': 68},
    {'1': 'VALUE_TRACK_PARAMETER_NOT_SUPPORTED', '2': 69},
    {'1': 'UNSUPPORTED_VALUE_IN_SELECTED_LANGUAGE', '2': 70},
    {'1': 'INVALID_IOS_APP_LINK', '2': 71},
    {'1': 'MISSING_IOS_APP_LINK_OR_IOS_APP_STORE_ID', '2': 72},
    {'1': 'PROMOTION_INVALID_TIME', '2': 73},
    {'1': 'PROMOTION_CANNOT_SET_PERCENT_OFF_AND_MONEY_AMOUNT_OFF', '2': 74},
    {'1': 'PROMOTION_CANNOT_SET_PROMOTION_CODE_AND_ORDERS_OVER_AMOUNT', '2': 75},
    {'1': 'TOO_MANY_DECIMAL_PLACES_SPECIFIED', '2': 76},
    {'1': 'AD_CUSTOMIZERS_NOT_ALLOWED', '2': 77},
    {'1': 'INVALID_LANGUAGE_CODE', '2': 78},
    {'1': 'UNSUPPORTED_LANGUAGE', '2': 79},
    {'1': 'IF_FUNCTION_NOT_ALLOWED', '2': 80},
    {'1': 'INVALID_FINAL_URL_SUFFIX', '2': 81},
    {'1': 'INVALID_TAG_IN_FINAL_URL_SUFFIX', '2': 82},
    {'1': 'INVALID_FINAL_URL_SUFFIX_FORMAT', '2': 83},
    {'1': 'CUSTOMER_CONSENT_FOR_CALL_RECORDING_REQUIRED', '2': 84},
    {'1': 'ONLY_ONE_DELIVERY_OPTION_IS_ALLOWED', '2': 85},
    {'1': 'NO_DELIVERY_OPTION_IS_SET', '2': 86},
    {'1': 'INVALID_CONVERSION_REPORTING_STATE', '2': 87},
    {'1': 'IMAGE_SIZE_WRONG', '2': 88},
    {'1': 'EMAIL_DELIVERY_NOT_AVAILABLE_IN_COUNTRY', '2': 89},
    {'1': 'AUTO_REPLY_NOT_AVAILABLE_IN_COUNTRY', '2': 90},
    {'1': 'INVALID_LATITUDE_VALUE', '2': 91},
    {'1': 'INVALID_LONGITUDE_VALUE', '2': 92},
    {'1': 'TOO_MANY_LABELS', '2': 93},
    {'1': 'INVALID_IMAGE_URL', '2': 94},
    {'1': 'MISSING_LATITUDE_VALUE', '2': 95},
    {'1': 'MISSING_LONGITUDE_VALUE', '2': 96},
    {'1': 'ADDRESS_NOT_FOUND', '2': 97},
    {'1': 'ADDRESS_NOT_TARGETABLE', '2': 98},
    {'1': 'INVALID_ASSET_ID', '2': 100},
    {'1': 'INCOMPATIBLE_ASSET_TYPE', '2': 101},
    {'1': 'IMAGE_ERROR_UNEXPECTED_SIZE', '2': 102},
    {'1': 'IMAGE_ERROR_ASPECT_RATIO_NOT_ALLOWED', '2': 103},
    {'1': 'IMAGE_ERROR_FILE_TOO_LARGE', '2': 104},
    {'1': 'IMAGE_ERROR_FORMAT_NOT_ALLOWED', '2': 105},
    {'1': 'IMAGE_ERROR_CONSTRAINTS_VIOLATED', '2': 106},
    {'1': 'IMAGE_ERROR_SERVER_ERROR', '2': 107},
  ],
};

/// Descriptor for `FeedItemValidationErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List feedItemValidationErrorEnumDescriptor = $convert.base64Decode(
    'ChtGZWVkSXRlbVZhbGlkYXRpb25FcnJvckVudW0izhsKF0ZlZWRJdGVtVmFsaWRhdGlvbkVycm'
    '9yEg8KC1VOU1BFQ0lGSUVEEAASCwoHVU5LTk9XThABEhQKEFNUUklOR19UT09fU0hPUlQQAhIT'
    'Cg9TVFJJTkdfVE9PX0xPTkcQAxIXChNWQUxVRV9OT1RfU1BFQ0lGSUVEEAQSKAokSU5WQUxJRF'
    '9ET01FU1RJQ19QSE9ORV9OVU1CRVJfRk9STUFUEAUSGAoUSU5WQUxJRF9QSE9ORV9OVU1CRVIQ'
    'BhIqCiZQSE9ORV9OVU1CRVJfTk9UX1NVUFBPUlRFRF9GT1JfQ09VTlRSWRAHEiMKH1BSRU1JVU'
    '1fUkFURV9OVU1CRVJfTk9UX0FMTE9XRUQQCBIaChZESVNBTExPV0VEX05VTUJFUl9UWVBFEAkS'
    'FgoSVkFMVUVfT1VUX09GX1JBTkdFEAoSKgomQ0FMTFRSQUNLSU5HX05PVF9TVVBQT1JURURfRk'
    '9SX0NPVU5UUlkQCxIuCipDVVNUT01FUl9OT1RfSU5fQUxMT1dMSVNUX0ZPUl9DQUxMVFJBQ0tJ'
    'TkcQYxIYChRJTlZBTElEX0NPVU5UUllfQ09ERRANEhIKDklOVkFMSURfQVBQX0lEEA4SIQodTU'
    'lTU0lOR19BVFRSSUJVVEVTX0ZPUl9GSUVMRFMQDxITCg9JTlZBTElEX1RZUEVfSUQQEBIZChVJ'
    'TlZBTElEX0VNQUlMX0FERFJFU1MQERIVChFJTlZBTElEX0hUVFBTX1VSTBASEhwKGE1JU1NJTk'
    'dfREVMSVZFUllfQUREUkVTUxATEh0KGVNUQVJUX0RBVEVfQUZURVJfRU5EX0RBVEUQFBIgChxN'
    'SVNTSU5HX0ZFRURfSVRFTV9TVEFSVF9USU1FEBUSHgoaTUlTU0lOR19GRUVEX0lURU1fRU5EX1'
    'RJTUUQFhIYChRNSVNTSU5HX0ZFRURfSVRFTV9JRBAXEiMKH1ZBTklUWV9QSE9ORV9OVU1CRVJf'
    'Tk9UX0FMTE9XRUQQGBIkCiBJTlZBTElEX1JFVklFV19FWFRFTlNJT05fU05JUFBFVBAZEhkKFU'
    'lOVkFMSURfTlVNQkVSX0ZPUk1BVBAaEhcKE0lOVkFMSURfREFURV9GT1JNQVQQGxIYChRJTlZB'
    'TElEX1BSSUNFX0ZPUk1BVBAcEh0KGVVOS05PV05fUExBQ0VIT0xERVJfRklFTEQQHRIuCipNSV'
    'NTSU5HX0VOSEFOQ0VEX1NJVEVMSU5LX0RFU0NSSVBUSU9OX0xJTkUQHhImCiJSRVZJRVdfRVhU'
    'RU5TSU9OX1NPVVJDRV9JTkVMSUdJQkxFEB8SJwojSFlQSEVOU19JTl9SRVZJRVdfRVhURU5TSU'
    '9OX1NOSVBQRVQQIBItCilET1VCTEVfUVVPVEVTX0lOX1JFVklFV19FWFRFTlNJT05fU05JUFBF'
    'VBAhEiYKIlFVT1RFU19JTl9SRVZJRVdfRVhURU5TSU9OX1NOSVBQRVQQIhIfChtJTlZBTElEX0'
    'ZPUk1fRU5DT0RFRF9QQVJBTVMQIxIeChpJTlZBTElEX1VSTF9QQVJBTUVURVJfTkFNRRAkEhcK'
    'E05PX0dFT0NPRElOR19SRVNVTFQQJRIoCiRTT1VSQ0VfTkFNRV9JTl9SRVZJRVdfRVhURU5TSU'
    '9OX1RFWFQQJhItCilDQVJSSUVSX1NQRUNJRklDX1NIT1JUX05VTUJFUl9OT1RfQUxMT1dFRBAn'
    'EiAKHElOVkFMSURfUExBQ0VIT0xERVJfRklFTERfSUQQKBITCg9JTlZBTElEX1VSTF9UQUcQKR'
    'IRCg1MSVNUX1RPT19MT05HECoSIgoeSU5WQUxJRF9BVFRSSUJVVEVTX0NPTUJJTkFUSU9OECsS'
    'FAoQRFVQTElDQVRFX1ZBTFVFUxAsEiUKIUlOVkFMSURfQ0FMTF9DT05WRVJTSU9OX0FDVElPTl'
    '9JRBAtEiEKHUNBTk5PVF9TRVRfV0lUSE9VVF9GSU5BTF9VUkxTEC4SJAogQVBQX0lEX0RPRVNO'
    'VF9FWElTVF9JTl9BUFBfU1RPUkUQLxIVChFJTlZBTElEX0ZJTkFMX1VSTBAwEhgKFElOVkFMSU'
    'RfVFJBQ0tJTkdfVVJMEDESKgomSU5WQUxJRF9GSU5BTF9VUkxfRk9SX0FQUF9ET1dOTE9BRF9V'
    'UkwQMhISCg5MSVNUX1RPT19TSE9SVBAzEhcKE0lOVkFMSURfVVNFUl9BQ1RJT04QNBIVChFJTl'
    'ZBTElEX1RZUEVfTkFNRRA1Eh8KG0lOVkFMSURfRVZFTlRfQ0hBTkdFX1NUQVRVUxA2EhsKF0lO'
    'VkFMSURfU05JUFBFVFNfSEVBREVSEDcSHAoYSU5WQUxJRF9BTkRST0lEX0FQUF9MSU5LEDgSOw'
    'o3TlVNQkVSX1RZUEVfV0lUSF9DQUxMVFJBQ0tJTkdfTk9UX1NVUFBPUlRFRF9GT1JfQ09VTlRS'
    'WRA5EhoKFlJFU0VSVkVEX0tFWVdPUkRfT1RIRVIQOhIbChdEVVBMSUNBVEVfT1BUSU9OX0xBQk'
    'VMUxA7Eh0KGURVUExJQ0FURV9PUFRJT05fUFJFRklMTFMQPBIYChRVTkVRVUFMX0xJU1RfTEVO'
    'R1RIUxA9Eh8KG0lOQ09OU0lTVEVOVF9DVVJSRU5DWV9DT0RFUxA+EioKJlBSSUNFX0VYVEVOU0'
    'lPTl9IQVNfRFVQTElDQVRFRF9IRUFERVJTED8SLgoqSVRFTV9IQVNfRFVQTElDQVRFRF9IRUFE'
    'RVJfQU5EX0RFU0NSSVBUSU9OEEASJQohUFJJQ0VfRVhURU5TSU9OX0hBU19UT09fRkVXX0lURU'
    '1TEEESFQoRVU5TVVBQT1JURURfVkFMVUUQQhIcChhJTlZBTElEX0ZJTkFMX01PQklMRV9VUkwQ'
    'QxIlCiFJTlZBTElEX0tFWVdPUkRMRVNTX0FEX1JVTEVfTEFCRUwQRBInCiNWQUxVRV9UUkFDS1'
    '9QQVJBTUVURVJfTk9UX1NVUFBPUlRFRBBFEioKJlVOU1VQUE9SVEVEX1ZBTFVFX0lOX1NFTEVD'
    'VEVEX0xBTkdVQUdFEEYSGAoUSU5WQUxJRF9JT1NfQVBQX0xJTksQRxIsCihNSVNTSU5HX0lPU1'
    '9BUFBfTElOS19PUl9JT1NfQVBQX1NUT1JFX0lEEEgSGgoWUFJPTU9USU9OX0lOVkFMSURfVElN'
    'RRBJEjkKNVBST01PVElPTl9DQU5OT1RfU0VUX1BFUkNFTlRfT0ZGX0FORF9NT05FWV9BTU9VTl'
    'RfT0ZGEEoSPgo6UFJPTU9USU9OX0NBTk5PVF9TRVRfUFJPTU9USU9OX0NPREVfQU5EX09SREVS'
    'U19PVkVSX0FNT1VOVBBLEiUKIVRPT19NQU5ZX0RFQ0lNQUxfUExBQ0VTX1NQRUNJRklFRBBMEh'
    '4KGkFEX0NVU1RPTUlaRVJTX05PVF9BTExPV0VEEE0SGQoVSU5WQUxJRF9MQU5HVUFHRV9DT0RF'
    'EE4SGAoUVU5TVVBQT1JURURfTEFOR1VBR0UQTxIbChdJRl9GVU5DVElPTl9OT1RfQUxMT1dFRB'
    'BQEhwKGElOVkFMSURfRklOQUxfVVJMX1NVRkZJWBBREiMKH0lOVkFMSURfVEFHX0lOX0ZJTkFM'
    'X1VSTF9TVUZGSVgQUhIjCh9JTlZBTElEX0ZJTkFMX1VSTF9TVUZGSVhfRk9STUFUEFMSMAosQ1'
    'VTVE9NRVJfQ09OU0VOVF9GT1JfQ0FMTF9SRUNPUkRJTkdfUkVRVUlSRUQQVBInCiNPTkxZX09O'
    'RV9ERUxJVkVSWV9PUFRJT05fSVNfQUxMT1dFRBBVEh0KGU5PX0RFTElWRVJZX09QVElPTl9JU1'
    '9TRVQQVhImCiJJTlZBTElEX0NPTlZFUlNJT05fUkVQT1JUSU5HX1NUQVRFEFcSFAoQSU1BR0Vf'
    'U0laRV9XUk9ORxBYEisKJ0VNQUlMX0RFTElWRVJZX05PVF9BVkFJTEFCTEVfSU5fQ09VTlRSWR'
    'BZEicKI0FVVE9fUkVQTFlfTk9UX0FWQUlMQUJMRV9JTl9DT1VOVFJZEFoSGgoWSU5WQUxJRF9M'
    'QVRJVFVERV9WQUxVRRBbEhsKF0lOVkFMSURfTE9OR0lUVURFX1ZBTFVFEFwSEwoPVE9PX01BTl'
    'lfTEFCRUxTEF0SFQoRSU5WQUxJRF9JTUFHRV9VUkwQXhIaChZNSVNTSU5HX0xBVElUVURFX1ZB'
    'TFVFEF8SGwoXTUlTU0lOR19MT05HSVRVREVfVkFMVUUQYBIVChFBRERSRVNTX05PVF9GT1VORB'
    'BhEhoKFkFERFJFU1NfTk9UX1RBUkdFVEFCTEUQYhIUChBJTlZBTElEX0FTU0VUX0lEEGQSGwoX'
    'SU5DT01QQVRJQkxFX0FTU0VUX1RZUEUQZRIfChtJTUFHRV9FUlJPUl9VTkVYUEVDVEVEX1NJWk'
    'UQZhIoCiRJTUFHRV9FUlJPUl9BU1BFQ1RfUkFUSU9fTk9UX0FMTE9XRUQQZxIeChpJTUFHRV9F'
    'UlJPUl9GSUxFX1RPT19MQVJHRRBoEiIKHklNQUdFX0VSUk9SX0ZPUk1BVF9OT1RfQUxMT1dFRB'
    'BpEiQKIElNQUdFX0VSUk9SX0NPTlNUUkFJTlRTX1ZJT0xBVEVEEGoSHAoYSU1BR0VfRVJST1Jf'
    'U0VSVkVSX0VSUk9SEGs=');

