//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v15/errors/offline_user_data_job_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use offlineUserDataJobErrorEnumDescriptor instead')
const OfflineUserDataJobErrorEnum$json = {
  '1': 'OfflineUserDataJobErrorEnum',
  '4': [OfflineUserDataJobErrorEnum_OfflineUserDataJobError$json],
};

@$core.Deprecated('Use offlineUserDataJobErrorEnumDescriptor instead')
const OfflineUserDataJobErrorEnum_OfflineUserDataJobError$json = {
  '1': 'OfflineUserDataJobError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'INVALID_USER_LIST_ID', '2': 3},
    {'1': 'INVALID_USER_LIST_TYPE', '2': 4},
    {'1': 'NOT_ON_ALLOWLIST_FOR_USER_ID', '2': 33},
    {'1': 'INCOMPATIBLE_UPLOAD_KEY_TYPE', '2': 6},
    {'1': 'MISSING_USER_IDENTIFIER', '2': 7},
    {'1': 'INVALID_MOBILE_ID_FORMAT', '2': 8},
    {'1': 'TOO_MANY_USER_IDENTIFIERS', '2': 9},
    {'1': 'NOT_ON_ALLOWLIST_FOR_STORE_SALES_DIRECT', '2': 31},
    {'1': 'NOT_ON_ALLOWLIST_FOR_UNIFIED_STORE_SALES', '2': 32},
    {'1': 'INVALID_PARTNER_ID', '2': 11},
    {'1': 'INVALID_ENCODING', '2': 12},
    {'1': 'INVALID_COUNTRY_CODE', '2': 13},
    {'1': 'INCOMPATIBLE_USER_IDENTIFIER', '2': 14},
    {'1': 'FUTURE_TRANSACTION_TIME', '2': 15},
    {'1': 'INVALID_CONVERSION_ACTION', '2': 16},
    {'1': 'MOBILE_ID_NOT_SUPPORTED', '2': 17},
    {'1': 'INVALID_OPERATION_ORDER', '2': 18},
    {'1': 'CONFLICTING_OPERATION', '2': 19},
    {'1': 'EXTERNAL_UPDATE_ID_ALREADY_EXISTS', '2': 21},
    {'1': 'JOB_ALREADY_STARTED', '2': 22},
    {'1': 'REMOVE_NOT_SUPPORTED', '2': 23},
    {'1': 'REMOVE_ALL_NOT_SUPPORTED', '2': 24},
    {'1': 'INVALID_SHA256_FORMAT', '2': 25},
    {'1': 'CUSTOM_KEY_DISABLED', '2': 26},
    {'1': 'CUSTOM_KEY_NOT_PREDEFINED', '2': 27},
    {'1': 'CUSTOM_KEY_NOT_SET', '2': 29},
    {'1': 'CUSTOMER_NOT_ACCEPTED_CUSTOMER_DATA_TERMS', '2': 30},
    {'1': 'ATTRIBUTES_NOT_APPLICABLE_FOR_CUSTOMER_MATCH_USER_LIST', '2': 34},
    {'1': 'LIFETIME_VALUE_BUCKET_NOT_IN_RANGE', '2': 35},
    {'1': 'INCOMPATIBLE_USER_IDENTIFIER_FOR_ATTRIBUTES', '2': 36},
    {'1': 'FUTURE_TIME_NOT_ALLOWED', '2': 37},
    {'1': 'LAST_PURCHASE_TIME_LESS_THAN_ACQUISITION_TIME', '2': 38},
    {'1': 'CUSTOMER_IDENTIFIER_NOT_ALLOWED', '2': 39},
    {'1': 'INVALID_ITEM_ID', '2': 40},
    {'1': 'FIRST_PURCHASE_TIME_GREATER_THAN_LAST_PURCHASE_TIME', '2': 42},
    {'1': 'INVALID_LIFECYCLE_STAGE', '2': 43},
    {'1': 'INVALID_EVENT_VALUE', '2': 44},
    {'1': 'EVENT_ATTRIBUTE_ALL_FIELDS_ARE_REQUIRED', '2': 45},
  ],
};

/// Descriptor for `OfflineUserDataJobErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List offlineUserDataJobErrorEnumDescriptor = $convert.base64Decode(
    'ChtPZmZsaW5lVXNlckRhdGFKb2JFcnJvckVudW0irgoKF09mZmxpbmVVc2VyRGF0YUpvYkVycm'
    '9yEg8KC1VOU1BFQ0lGSUVEEAASCwoHVU5LTk9XThABEhgKFElOVkFMSURfVVNFUl9MSVNUX0lE'
    'EAMSGgoWSU5WQUxJRF9VU0VSX0xJU1RfVFlQRRAEEiAKHE5PVF9PTl9BTExPV0xJU1RfRk9SX1'
    'VTRVJfSUQQIRIgChxJTkNPTVBBVElCTEVfVVBMT0FEX0tFWV9UWVBFEAYSGwoXTUlTU0lOR19V'
    'U0VSX0lERU5USUZJRVIQBxIcChhJTlZBTElEX01PQklMRV9JRF9GT1JNQVQQCBIdChlUT09fTU'
    'FOWV9VU0VSX0lERU5USUZJRVJTEAkSKwonTk9UX09OX0FMTE9XTElTVF9GT1JfU1RPUkVfU0FM'
    'RVNfRElSRUNUEB8SLAooTk9UX09OX0FMTE9XTElTVF9GT1JfVU5JRklFRF9TVE9SRV9TQUxFUx'
    'AgEhYKEklOVkFMSURfUEFSVE5FUl9JRBALEhQKEElOVkFMSURfRU5DT0RJTkcQDBIYChRJTlZB'
    'TElEX0NPVU5UUllfQ09ERRANEiAKHElOQ09NUEFUSUJMRV9VU0VSX0lERU5USUZJRVIQDhIbCh'
    'dGVVRVUkVfVFJBTlNBQ1RJT05fVElNRRAPEh0KGUlOVkFMSURfQ09OVkVSU0lPTl9BQ1RJT04Q'
    'EBIbChdNT0JJTEVfSURfTk9UX1NVUFBPUlRFRBAREhsKF0lOVkFMSURfT1BFUkFUSU9OX09SRE'
    'VSEBISGQoVQ09ORkxJQ1RJTkdfT1BFUkFUSU9OEBMSJQohRVhURVJOQUxfVVBEQVRFX0lEX0FM'
    'UkVBRFlfRVhJU1RTEBUSFwoTSk9CX0FMUkVBRFlfU1RBUlRFRBAWEhgKFFJFTU9WRV9OT1RfU1'
    'VQUE9SVEVEEBcSHAoYUkVNT1ZFX0FMTF9OT1RfU1VQUE9SVEVEEBgSGQoVSU5WQUxJRF9TSEEy'
    'NTZfRk9STUFUEBkSFwoTQ1VTVE9NX0tFWV9ESVNBQkxFRBAaEh0KGUNVU1RPTV9LRVlfTk9UX1'
    'BSRURFRklORUQQGxIWChJDVVNUT01fS0VZX05PVF9TRVQQHRItCilDVVNUT01FUl9OT1RfQUND'
    'RVBURURfQ1VTVE9NRVJfREFUQV9URVJNUxAeEjoKNkFUVFJJQlVURVNfTk9UX0FQUExJQ0FCTE'
    'VfRk9SX0NVU1RPTUVSX01BVENIX1VTRVJfTElTVBAiEiYKIkxJRkVUSU1FX1ZBTFVFX0JVQ0tF'
    'VF9OT1RfSU5fUkFOR0UQIxIvCitJTkNPTVBBVElCTEVfVVNFUl9JREVOVElGSUVSX0ZPUl9BVF'
    'RSSUJVVEVTECQSGwoXRlVUVVJFX1RJTUVfTk9UX0FMTE9XRUQQJRIxCi1MQVNUX1BVUkNIQVNF'
    'X1RJTUVfTEVTU19USEFOX0FDUVVJU0lUSU9OX1RJTUUQJhIjCh9DVVNUT01FUl9JREVOVElGSU'
    'VSX05PVF9BTExPV0VEECcSEwoPSU5WQUxJRF9JVEVNX0lEECgSNwozRklSU1RfUFVSQ0hBU0Vf'
    'VElNRV9HUkVBVEVSX1RIQU5fTEFTVF9QVVJDSEFTRV9USU1FECoSGwoXSU5WQUxJRF9MSUZFQ1'
    'lDTEVfU1RBR0UQKxIXChNJTlZBTElEX0VWRU5UX1ZBTFVFECwSKwonRVZFTlRfQVRUUklCVVRF'
    'X0FMTF9GSUVMRFNfQVJFX1JFUVVJUkVEEC0=');

