//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v15/errors/setting_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use settingErrorEnumDescriptor instead')
const SettingErrorEnum$json = {
  '1': 'SettingErrorEnum',
  '4': [SettingErrorEnum_SettingError$json],
};

@$core.Deprecated('Use settingErrorEnumDescriptor instead')
const SettingErrorEnum_SettingError$json = {
  '1': 'SettingError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'SETTING_TYPE_IS_NOT_AVAILABLE', '2': 3},
    {'1': 'SETTING_TYPE_IS_NOT_COMPATIBLE_WITH_CAMPAIGN', '2': 4},
    {'1': 'TARGETING_SETTING_CONTAINS_INVALID_CRITERION_TYPE_GROUP', '2': 5},
    {'1': 'TARGETING_SETTING_DEMOGRAPHIC_CRITERION_TYPE_GROUPS_MUST_BE_SET_TO_TARGET_ALL', '2': 6},
    {'1': 'TARGETING_SETTING_CANNOT_CHANGE_TARGET_ALL_TO_FALSE_FOR_DEMOGRAPHIC_CRITERION_TYPE_GROUP', '2': 7},
    {'1': 'DYNAMIC_SEARCH_ADS_SETTING_AT_LEAST_ONE_FEED_ID_MUST_BE_PRESENT', '2': 8},
    {'1': 'DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_INVALID_DOMAIN_NAME', '2': 9},
    {'1': 'DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_SUBDOMAIN_NAME', '2': 10},
    {'1': 'DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_INVALID_LANGUAGE_CODE', '2': 11},
    {'1': 'TARGET_ALL_IS_NOT_ALLOWED_FOR_PLACEMENT_IN_SEARCH_CAMPAIGN', '2': 12},
    {'1': 'SETTING_VALUE_NOT_COMPATIBLE_WITH_CAMPAIGN', '2': 20},
    {'1': 'BID_ONLY_IS_NOT_ALLOWED_TO_BE_MODIFIED_WITH_CUSTOMER_MATCH_TARGETING', '2': 21},
  ],
};

/// Descriptor for `SettingErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List settingErrorEnumDescriptor = $convert.base64Decode(
    'ChBTZXR0aW5nRXJyb3JFbnVtIqIGCgxTZXR0aW5nRXJyb3ISDwoLVU5TUEVDSUZJRUQQABILCg'
    'dVTktOT1dOEAESIQodU0VUVElOR19UWVBFX0lTX05PVF9BVkFJTEFCTEUQAxIwCixTRVRUSU5H'
    'X1RZUEVfSVNfTk9UX0NPTVBBVElCTEVfV0lUSF9DQU1QQUlHThAEEjsKN1RBUkdFVElOR19TRV'
    'RUSU5HX0NPTlRBSU5TX0lOVkFMSURfQ1JJVEVSSU9OX1RZUEVfR1JPVVAQBRJRCk1UQVJHRVRJ'
    'TkdfU0VUVElOR19ERU1PR1JBUEhJQ19DUklURVJJT05fVFlQRV9HUk9VUFNfTVVTVF9CRV9TRV'
    'RfVE9fVEFSR0VUX0FMTBAGElwKWFRBUkdFVElOR19TRVRUSU5HX0NBTk5PVF9DSEFOR0VfVEFS'
    'R0VUX0FMTF9UT19GQUxTRV9GT1JfREVNT0dSQVBISUNfQ1JJVEVSSU9OX1RZUEVfR1JPVVAQBx'
    'JDCj9EWU5BTUlDX1NFQVJDSF9BRFNfU0VUVElOR19BVF9MRUFTVF9PTkVfRkVFRF9JRF9NVVNU'
    'X0JFX1BSRVNFTlQQCBI7CjdEWU5BTUlDX1NFQVJDSF9BRFNfU0VUVElOR19DT05UQUlOU19JTl'
    'ZBTElEX0RPTUFJTl9OQU1FEAkSNgoyRFlOQU1JQ19TRUFSQ0hfQURTX1NFVFRJTkdfQ09OVEFJ'
    'TlNfU1VCRE9NQUlOX05BTUUQChI9CjlEWU5BTUlDX1NFQVJDSF9BRFNfU0VUVElOR19DT05UQU'
    'lOU19JTlZBTElEX0xBTkdVQUdFX0NPREUQCxI+CjpUQVJHRVRfQUxMX0lTX05PVF9BTExPV0VE'
    'X0ZPUl9QTEFDRU1FTlRfSU5fU0VBUkNIX0NBTVBBSUdOEAwSLgoqU0VUVElOR19WQUxVRV9OT1'
    'RfQ09NUEFUSUJMRV9XSVRIX0NBTVBBSUdOEBQSSApEQklEX09OTFlfSVNfTk9UX0FMTE9XRURf'
    'VE9fQkVfTU9ESUZJRURfV0lUSF9DVVNUT01FUl9NQVRDSF9UQVJHRVRJTkcQFQ==');

