//
//  Generated code. Do not modify.
//  source: google/cloud/websecurityscanner/v1beta/scan_config_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use scanConfigErrorDescriptor instead')
const ScanConfigError$json = {
  '1': 'ScanConfigError',
  '2': [
    {'1': 'code', '3': 1, '4': 1, '5': 14, '6': '.google.cloud.websecurityscanner.v1beta.ScanConfigError.Code', '10': 'code'},
    {'1': 'field_name', '3': 2, '4': 1, '5': 9, '10': 'fieldName'},
  ],
  '4': [ScanConfigError_Code$json],
};

@$core.Deprecated('Use scanConfigErrorDescriptor instead')
const ScanConfigError_Code$json = {
  '1': 'Code',
  '2': [
    {'1': 'CODE_UNSPECIFIED', '2': 0},
    {'1': 'OK', '2': 0},
    {'1': 'INTERNAL_ERROR', '2': 1},
    {'1': 'APPENGINE_API_BACKEND_ERROR', '2': 2},
    {'1': 'APPENGINE_API_NOT_ACCESSIBLE', '2': 3},
    {'1': 'APPENGINE_DEFAULT_HOST_MISSING', '2': 4},
    {'1': 'CANNOT_USE_GOOGLE_COM_ACCOUNT', '2': 6},
    {'1': 'CANNOT_USE_OWNER_ACCOUNT', '2': 7},
    {'1': 'COMPUTE_API_BACKEND_ERROR', '2': 8},
    {'1': 'COMPUTE_API_NOT_ACCESSIBLE', '2': 9},
    {'1': 'CUSTOM_LOGIN_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT', '2': 10},
    {'1': 'CUSTOM_LOGIN_URL_MALFORMED', '2': 11},
    {'1': 'CUSTOM_LOGIN_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS', '2': 12},
    {'1': 'CUSTOM_LOGIN_URL_MAPPED_TO_UNRESERVED_ADDRESS', '2': 13},
    {'1': 'CUSTOM_LOGIN_URL_HAS_NON_ROUTABLE_IP_ADDRESS', '2': 14},
    {'1': 'CUSTOM_LOGIN_URL_HAS_UNRESERVED_IP_ADDRESS', '2': 15},
    {'1': 'DUPLICATE_SCAN_NAME', '2': 16},
    {'1': 'INVALID_FIELD_VALUE', '2': 18},
    {'1': 'FAILED_TO_AUTHENTICATE_TO_TARGET', '2': 19},
    {'1': 'FINDING_TYPE_UNSPECIFIED', '2': 20},
    {'1': 'FORBIDDEN_TO_SCAN_COMPUTE', '2': 21},
    {'1': 'FORBIDDEN_UPDATE_TO_MANAGED_SCAN', '2': 43},
    {'1': 'MALFORMED_FILTER', '2': 22},
    {'1': 'MALFORMED_RESOURCE_NAME', '2': 23},
    {'1': 'PROJECT_INACTIVE', '2': 24},
    {'1': 'REQUIRED_FIELD', '2': 25},
    {'1': 'RESOURCE_NAME_INCONSISTENT', '2': 26},
    {'1': 'SCAN_ALREADY_RUNNING', '2': 27},
    {'1': 'SCAN_NOT_RUNNING', '2': 28},
    {'1': 'SEED_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT', '2': 29},
    {'1': 'SEED_URL_MALFORMED', '2': 30},
    {'1': 'SEED_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS', '2': 31},
    {'1': 'SEED_URL_MAPPED_TO_UNRESERVED_ADDRESS', '2': 32},
    {'1': 'SEED_URL_HAS_NON_ROUTABLE_IP_ADDRESS', '2': 33},
    {'1': 'SEED_URL_HAS_UNRESERVED_IP_ADDRESS', '2': 35},
    {'1': 'SERVICE_ACCOUNT_NOT_CONFIGURED', '2': 36},
    {'1': 'TOO_MANY_SCANS', '2': 37},
    {'1': 'UNABLE_TO_RESOLVE_PROJECT_INFO', '2': 38},
    {'1': 'UNSUPPORTED_BLACKLIST_PATTERN_FORMAT', '2': 39},
    {'1': 'UNSUPPORTED_FILTER', '2': 40},
    {'1': 'UNSUPPORTED_FINDING_TYPE', '2': 41},
    {'1': 'UNSUPPORTED_URL_SCHEME', '2': 42},
  ],
  '3': {'2': true},
};

/// Descriptor for `ScanConfigError`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List scanConfigErrorDescriptor = $convert.base64Decode(
    'Cg9TY2FuQ29uZmlnRXJyb3ISUAoEY29kZRgBIAEoDjI8Lmdvb2dsZS5jbG91ZC53ZWJzZWN1cm'
    'l0eXNjYW5uZXIudjFiZXRhLlNjYW5Db25maWdFcnJvci5Db2RlUgRjb2RlEh0KCmZpZWxkX25h'
    'bWUYAiABKAlSCWZpZWxkTmFtZSL5CgoEQ29kZRIUChBDT0RFX1VOU1BFQ0lGSUVEEAASBgoCT0'
    'sQABISCg5JTlRFUk5BTF9FUlJPUhABEh8KG0FQUEVOR0lORV9BUElfQkFDS0VORF9FUlJPUhAC'
    'EiAKHEFQUEVOR0lORV9BUElfTk9UX0FDQ0VTU0lCTEUQAxIiCh5BUFBFTkdJTkVfREVGQVVMVF'
    '9IT1NUX01JU1NJTkcQBBIhCh1DQU5OT1RfVVNFX0dPT0dMRV9DT01fQUNDT1VOVBAGEhwKGENB'
    'Tk5PVF9VU0VfT1dORVJfQUNDT1VOVBAHEh0KGUNPTVBVVEVfQVBJX0JBQ0tFTkRfRVJST1IQCB'
    'IeChpDT01QVVRFX0FQSV9OT1RfQUNDRVNTSUJMRRAJEjcKM0NVU1RPTV9MT0dJTl9VUkxfRE9F'
    'U19OT1RfQkVMT05HX1RPX0NVUlJFTlRfUFJPSkVDVBAKEh4KGkNVU1RPTV9MT0dJTl9VUkxfTU'
    'FMRk9STUVEEAsSMwovQ1VTVE9NX0xPR0lOX1VSTF9NQVBQRURfVE9fTk9OX1JPVVRBQkxFX0FE'
    'RFJFU1MQDBIxCi1DVVNUT01fTE9HSU5fVVJMX01BUFBFRF9UT19VTlJFU0VSVkVEX0FERFJFU1'
    'MQDRIwCixDVVNUT01fTE9HSU5fVVJMX0hBU19OT05fUk9VVEFCTEVfSVBfQUREUkVTUxAOEi4K'
    'KkNVU1RPTV9MT0dJTl9VUkxfSEFTX1VOUkVTRVJWRURfSVBfQUREUkVTUxAPEhcKE0RVUExJQ0'
    'FURV9TQ0FOX05BTUUQEBIXChNJTlZBTElEX0ZJRUxEX1ZBTFVFEBISJAogRkFJTEVEX1RPX0FV'
    'VEhFTlRJQ0FURV9UT19UQVJHRVQQExIcChhGSU5ESU5HX1RZUEVfVU5TUEVDSUZJRUQQFBIdCh'
    'lGT1JCSURERU5fVE9fU0NBTl9DT01QVVRFEBUSJAogRk9SQklEREVOX1VQREFURV9UT19NQU5B'
    'R0VEX1NDQU4QKxIUChBNQUxGT1JNRURfRklMVEVSEBYSGwoXTUFMRk9STUVEX1JFU09VUkNFX0'
    '5BTUUQFxIUChBQUk9KRUNUX0lOQUNUSVZFEBgSEgoOUkVRVUlSRURfRklFTEQQGRIeChpSRVNP'
    'VVJDRV9OQU1FX0lOQ09OU0lTVEVOVBAaEhgKFFNDQU5fQUxSRUFEWV9SVU5OSU5HEBsSFAoQU0'
    'NBTl9OT1RfUlVOTklORxAcEi8KK1NFRURfVVJMX0RPRVNfTk9UX0JFTE9OR19UT19DVVJSRU5U'
    'X1BST0pFQ1QQHRIWChJTRUVEX1VSTF9NQUxGT1JNRUQQHhIrCidTRUVEX1VSTF9NQVBQRURfVE'
    '9fTk9OX1JPVVRBQkxFX0FERFJFU1MQHxIpCiVTRUVEX1VSTF9NQVBQRURfVE9fVU5SRVNFUlZF'
    'RF9BRERSRVNTECASKAokU0VFRF9VUkxfSEFTX05PTl9ST1VUQUJMRV9JUF9BRERSRVNTECESJg'
    'oiU0VFRF9VUkxfSEFTX1VOUkVTRVJWRURfSVBfQUREUkVTUxAjEiIKHlNFUlZJQ0VfQUNDT1VO'
    'VF9OT1RfQ09ORklHVVJFRBAkEhIKDlRPT19NQU5ZX1NDQU5TECUSIgoeVU5BQkxFX1RPX1JFU0'
    '9MVkVfUFJPSkVDVF9JTkZPECYSKAokVU5TVVBQT1JURURfQkxBQ0tMSVNUX1BBVFRFUk5fRk9S'
    'TUFUECcSFgoSVU5TVVBQT1JURURfRklMVEVSECgSHAoYVU5TVVBQT1JURURfRklORElOR19UWV'
    'BFECkSGgoWVU5TVVBQT1JURURfVVJMX1NDSEVNRRAqGgIQAQ==');

