//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v16/errors/criterion_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use criterionErrorEnumDescriptor instead')
const CriterionErrorEnum$json = {
  '1': 'CriterionErrorEnum',
  '4': [CriterionErrorEnum_CriterionError$json],
};

@$core.Deprecated('Use criterionErrorEnumDescriptor instead')
const CriterionErrorEnum_CriterionError$json = {
  '1': 'CriterionError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'CONCRETE_TYPE_REQUIRED', '2': 2},
    {'1': 'INVALID_EXCLUDED_CATEGORY', '2': 3},
    {'1': 'INVALID_KEYWORD_TEXT', '2': 4},
    {'1': 'KEYWORD_TEXT_TOO_LONG', '2': 5},
    {'1': 'KEYWORD_HAS_TOO_MANY_WORDS', '2': 6},
    {'1': 'KEYWORD_HAS_INVALID_CHARS', '2': 7},
    {'1': 'INVALID_PLACEMENT_URL', '2': 8},
    {'1': 'INVALID_USER_LIST', '2': 9},
    {'1': 'INVALID_USER_INTEREST', '2': 10},
    {'1': 'INVALID_FORMAT_FOR_PLACEMENT_URL', '2': 11},
    {'1': 'PLACEMENT_URL_IS_TOO_LONG', '2': 12},
    {'1': 'PLACEMENT_URL_HAS_ILLEGAL_CHAR', '2': 13},
    {'1': 'PLACEMENT_URL_HAS_MULTIPLE_SITES_IN_LINE', '2': 14},
    {'1': 'PLACEMENT_IS_NOT_AVAILABLE_FOR_TARGETING_OR_EXCLUSION', '2': 15},
    {'1': 'INVALID_TOPIC_PATH', '2': 16},
    {'1': 'INVALID_YOUTUBE_CHANNEL_ID', '2': 17},
    {'1': 'INVALID_YOUTUBE_VIDEO_ID', '2': 18},
    {'1': 'YOUTUBE_VERTICAL_CHANNEL_DEPRECATED', '2': 19},
    {'1': 'YOUTUBE_DEMOGRAPHIC_CHANNEL_DEPRECATED', '2': 20},
    {'1': 'YOUTUBE_URL_UNSUPPORTED', '2': 21},
    {'1': 'CANNOT_EXCLUDE_CRITERIA_TYPE', '2': 22},
    {'1': 'CANNOT_ADD_CRITERIA_TYPE', '2': 23},
    {'1': 'CANNOT_EXCLUDE_SIMILAR_USER_LIST', '2': 26},
    {'1': 'CANNOT_ADD_CLOSED_USER_LIST', '2': 27},
    {'1': 'CANNOT_ADD_DISPLAY_ONLY_LISTS_TO_SEARCH_ONLY_CAMPAIGNS', '2': 28},
    {'1': 'CANNOT_ADD_DISPLAY_ONLY_LISTS_TO_SEARCH_CAMPAIGNS', '2': 29},
    {'1': 'CANNOT_ADD_DISPLAY_ONLY_LISTS_TO_SHOPPING_CAMPAIGNS', '2': 30},
    {'1': 'CANNOT_ADD_USER_INTERESTS_TO_SEARCH_CAMPAIGNS', '2': 31},
    {'1': 'CANNOT_SET_BIDS_ON_CRITERION_TYPE_IN_SEARCH_CAMPAIGNS', '2': 32},
    {'1': 'CANNOT_ADD_URLS_TO_CRITERION_TYPE_FOR_CAMPAIGN_TYPE', '2': 33},
    {'1': 'INVALID_COMBINED_AUDIENCE', '2': 122},
    {'1': 'INVALID_CUSTOM_AFFINITY', '2': 96},
    {'1': 'INVALID_CUSTOM_INTENT', '2': 97},
    {'1': 'INVALID_CUSTOM_AUDIENCE', '2': 121},
    {'1': 'INVALID_IP_ADDRESS', '2': 34},
    {'1': 'INVALID_IP_FORMAT', '2': 35},
    {'1': 'INVALID_MOBILE_APP', '2': 36},
    {'1': 'INVALID_MOBILE_APP_CATEGORY', '2': 37},
    {'1': 'INVALID_CRITERION_ID', '2': 38},
    {'1': 'CANNOT_TARGET_CRITERION', '2': 39},
    {'1': 'CANNOT_TARGET_OBSOLETE_CRITERION', '2': 40},
    {'1': 'CRITERION_ID_AND_TYPE_MISMATCH', '2': 41},
    {'1': 'INVALID_PROXIMITY_RADIUS', '2': 42},
    {'1': 'INVALID_PROXIMITY_RADIUS_UNITS', '2': 43},
    {'1': 'INVALID_STREETADDRESS_LENGTH', '2': 44},
    {'1': 'INVALID_CITYNAME_LENGTH', '2': 45},
    {'1': 'INVALID_REGIONCODE_LENGTH', '2': 46},
    {'1': 'INVALID_REGIONNAME_LENGTH', '2': 47},
    {'1': 'INVALID_POSTALCODE_LENGTH', '2': 48},
    {'1': 'INVALID_COUNTRY_CODE', '2': 49},
    {'1': 'INVALID_LATITUDE', '2': 50},
    {'1': 'INVALID_LONGITUDE', '2': 51},
    {'1': 'PROXIMITY_GEOPOINT_AND_ADDRESS_BOTH_CANNOT_BE_NULL', '2': 52},
    {'1': 'INVALID_PROXIMITY_ADDRESS', '2': 53},
    {'1': 'INVALID_USER_DOMAIN_NAME', '2': 54},
    {'1': 'CRITERION_PARAMETER_TOO_LONG', '2': 55},
    {'1': 'AD_SCHEDULE_TIME_INTERVALS_OVERLAP', '2': 56},
    {'1': 'AD_SCHEDULE_INTERVAL_CANNOT_SPAN_MULTIPLE_DAYS', '2': 57},
    {'1': 'AD_SCHEDULE_INVALID_TIME_INTERVAL', '2': 58},
    {'1': 'AD_SCHEDULE_EXCEEDED_INTERVALS_PER_DAY_LIMIT', '2': 59},
    {'1': 'AD_SCHEDULE_CRITERION_ID_MISMATCHING_FIELDS', '2': 60},
    {'1': 'CANNOT_BID_MODIFY_CRITERION_TYPE', '2': 61},
    {'1': 'CANNOT_BID_MODIFY_CRITERION_CAMPAIGN_OPTED_OUT', '2': 62},
    {'1': 'CANNOT_BID_MODIFY_NEGATIVE_CRITERION', '2': 63},
    {'1': 'BID_MODIFIER_ALREADY_EXISTS', '2': 64},
    {'1': 'FEED_ID_NOT_ALLOWED', '2': 65},
    {'1': 'ACCOUNT_INELIGIBLE_FOR_CRITERIA_TYPE', '2': 66},
    {'1': 'CRITERIA_TYPE_INVALID_FOR_BIDDING_STRATEGY', '2': 67},
    {'1': 'CANNOT_EXCLUDE_CRITERION', '2': 68},
    {'1': 'CANNOT_REMOVE_CRITERION', '2': 69},
    {'1': 'INVALID_PRODUCT_BIDDING_CATEGORY', '2': 76},
    {'1': 'MISSING_SHOPPING_SETTING', '2': 77},
    {'1': 'INVALID_MATCHING_FUNCTION', '2': 78},
    {'1': 'LOCATION_FILTER_NOT_ALLOWED', '2': 79},
    {'1': 'INVALID_FEED_FOR_LOCATION_FILTER', '2': 98},
    {'1': 'LOCATION_FILTER_INVALID', '2': 80},
    {'1': 'CANNOT_SET_GEO_TARGET_CONSTANTS_WITH_FEED_ITEM_SETS', '2': 123},
    {'1': 'CANNOT_SET_BOTH_ASSET_SET_AND_FEED', '2': 140},
    {'1': 'CANNOT_SET_FEED_OR_FEED_ITEM_SETS_FOR_CUSTOMER', '2': 142},
    {'1': 'CANNOT_SET_ASSET_SET_FIELD_FOR_CUSTOMER', '2': 150},
    {'1': 'CANNOT_SET_GEO_TARGET_CONSTANTS_WITH_ASSET_SETS', '2': 143},
    {'1': 'CANNOT_SET_ASSET_SETS_WITH_FEED_ITEM_SETS', '2': 144},
    {'1': 'INVALID_LOCATION_GROUP_ASSET_SET', '2': 141},
    {'1': 'INVALID_LOCATION_GROUP_RADIUS', '2': 124},
    {'1': 'INVALID_LOCATION_GROUP_RADIUS_UNIT', '2': 125},
    {'1': 'CANNOT_ATTACH_CRITERIA_AT_CAMPAIGN_AND_ADGROUP', '2': 81},
    {'1': 'HOTEL_LENGTH_OF_STAY_OVERLAPS_WITH_EXISTING_CRITERION', '2': 82},
    {'1': 'HOTEL_ADVANCE_BOOKING_WINDOW_OVERLAPS_WITH_EXISTING_CRITERION', '2': 83},
    {'1': 'FIELD_INCOMPATIBLE_WITH_NEGATIVE_TARGETING', '2': 84},
    {'1': 'INVALID_WEBPAGE_CONDITION', '2': 85},
    {'1': 'INVALID_WEBPAGE_CONDITION_URL', '2': 86},
    {'1': 'WEBPAGE_CONDITION_URL_CANNOT_BE_EMPTY', '2': 87},
    {'1': 'WEBPAGE_CONDITION_URL_UNSUPPORTED_PROTOCOL', '2': 88},
    {'1': 'WEBPAGE_CONDITION_URL_CANNOT_BE_IP_ADDRESS', '2': 89},
    {'1': 'WEBPAGE_CONDITION_URL_DOMAIN_NOT_CONSISTENT_WITH_CAMPAIGN_SETTING', '2': 90},
    {'1': 'WEBPAGE_CONDITION_URL_CANNOT_BE_PUBLIC_SUFFIX', '2': 91},
    {'1': 'WEBPAGE_CONDITION_URL_INVALID_PUBLIC_SUFFIX', '2': 92},
    {'1': 'WEBPAGE_CONDITION_URL_VALUE_TRACK_VALUE_NOT_SUPPORTED', '2': 93},
    {'1': 'WEBPAGE_CRITERION_URL_EQUALS_CAN_HAVE_ONLY_ONE_CONDITION', '2': 94},
    {'1': 'WEBPAGE_CRITERION_NOT_SUPPORTED_ON_NON_DSA_AD_GROUP', '2': 95},
    {'1': 'CANNOT_TARGET_USER_LIST_FOR_SMART_DISPLAY_CAMPAIGNS', '2': 99},
    {'1': 'CANNOT_TARGET_PLACEMENTS_FOR_SEARCH_CAMPAIGNS', '2': 126},
    {'1': 'LISTING_SCOPE_TOO_MANY_DIMENSION_TYPES', '2': 100},
    {'1': 'LISTING_SCOPE_TOO_MANY_IN_OPERATORS', '2': 101},
    {'1': 'LISTING_SCOPE_IN_OPERATOR_NOT_SUPPORTED', '2': 102},
    {'1': 'DUPLICATE_LISTING_DIMENSION_TYPE', '2': 103},
    {'1': 'DUPLICATE_LISTING_DIMENSION_VALUE', '2': 104},
    {'1': 'CANNOT_SET_BIDS_ON_LISTING_GROUP_SUBDIVISION', '2': 105},
    {'1': 'INVALID_LISTING_GROUP_HIERARCHY', '2': 106},
    {'1': 'LISTING_GROUP_UNIT_CANNOT_HAVE_CHILDREN', '2': 107},
    {'1': 'LISTING_GROUP_SUBDIVISION_REQUIRES_OTHERS_CASE', '2': 108},
    {'1': 'LISTING_GROUP_REQUIRES_SAME_DIMENSION_TYPE_AS_SIBLINGS', '2': 109},
    {'1': 'LISTING_GROUP_ALREADY_EXISTS', '2': 110},
    {'1': 'LISTING_GROUP_DOES_NOT_EXIST', '2': 111},
    {'1': 'LISTING_GROUP_CANNOT_BE_REMOVED', '2': 112},
    {'1': 'INVALID_LISTING_GROUP_TYPE', '2': 113},
    {'1': 'LISTING_GROUP_ADD_MAY_ONLY_USE_TEMP_ID', '2': 114},
    {'1': 'LISTING_SCOPE_TOO_LONG', '2': 115},
    {'1': 'LISTING_SCOPE_TOO_MANY_DIMENSIONS', '2': 116},
    {'1': 'LISTING_GROUP_TOO_LONG', '2': 117},
    {'1': 'LISTING_GROUP_TREE_TOO_DEEP', '2': 118},
    {'1': 'INVALID_LISTING_DIMENSION', '2': 119},
    {'1': 'INVALID_LISTING_DIMENSION_TYPE', '2': 120},
    {'1': 'ADVERTISER_NOT_ON_ALLOWLIST_FOR_COMBINED_AUDIENCE_ON_DISPLAY', '2': 127},
    {'1': 'CANNOT_TARGET_REMOVED_COMBINED_AUDIENCE', '2': 128},
    {'1': 'INVALID_COMBINED_AUDIENCE_ID', '2': 129},
    {'1': 'CANNOT_TARGET_REMOVED_CUSTOM_AUDIENCE', '2': 130},
    {'1': 'HOTEL_CHECK_IN_DATE_RANGE_OVERLAPS_WITH_EXISTING_CRITERION', '2': 131},
    {'1': 'HOTEL_CHECK_IN_DATE_RANGE_START_DATE_TOO_EARLY', '2': 132},
    {'1': 'HOTEL_CHECK_IN_DATE_RANGE_END_DATE_TOO_LATE', '2': 133},
    {'1': 'HOTEL_CHECK_IN_DATE_RANGE_REVERSED', '2': 134},
    {'1': 'BROAD_MATCH_MODIFIER_KEYWORD_NOT_ALLOWED', '2': 135},
    {'1': 'ONE_AUDIENCE_ALLOWED_PER_ASSET_GROUP', '2': 136},
    {'1': 'AUDIENCE_NOT_ELIGIBLE_FOR_CAMPAIGN_TYPE', '2': 137},
    {'1': 'AUDIENCE_NOT_ALLOWED_TO_ATTACH_WHEN_AUDIENCE_GROUPED_SET_TO_FALSE', '2': 138},
    {'1': 'CANNOT_TARGET_CUSTOMER_MATCH_USER_LIST', '2': 139},
    {'1': 'NEGATIVE_KEYWORD_SHARED_SET_DOES_NOT_EXIST', '2': 145},
    {'1': 'CANNOT_ADD_REMOVED_NEGATIVE_KEYWORD_SHARED_SET', '2': 146},
    {'1': 'CANNOT_HAVE_MULTIPLE_NEGATIVE_KEYWORD_LIST_PER_ACCOUNT', '2': 147},
    {'1': 'CUSTOMER_CANNOT_ADD_CRITERION_OF_THIS_TYPE', '2': 149},
    {'1': 'CANNOT_TARGET_SIMILAR_USER_LIST', '2': 151},
    {'1': 'CANNOT_ADD_AUDIENCE_SEGMENT_CRITERION_WHEN_AUDIENCE_GROUPED_IS_SET', '2': 152},
    {'1': 'ONE_AUDIENCE_ALLOWED_PER_AD_GROUP', '2': 153},
    {'1': 'INVALID_DETAILED_DEMOGRAPHIC', '2': 154},
    {'1': 'CANNOT_RECOGNIZE_BRAND', '2': 155},
    {'1': 'BRAND_SHARED_SET_DOES_NOT_EXIST', '2': 156},
    {'1': 'CANNOT_ADD_REMOVED_BRAND_SHARED_SET', '2': 157},
    {'1': 'ONLY_EXCLUSION_BRAND_LIST_ALLOWED_FOR_CAMPAIGN_TYPE', '2': 158},
  ],
};

/// Descriptor for `CriterionErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List criterionErrorEnumDescriptor = $convert.base64Decode(
    'ChJDcml0ZXJpb25FcnJvckVudW0iyS8KDkNyaXRlcmlvbkVycm9yEg8KC1VOU1BFQ0lGSUVEEA'
    'ASCwoHVU5LTk9XThABEhoKFkNPTkNSRVRFX1RZUEVfUkVRVUlSRUQQAhIdChlJTlZBTElEX0VY'
    'Q0xVREVEX0NBVEVHT1JZEAMSGAoUSU5WQUxJRF9LRVlXT1JEX1RFWFQQBBIZChVLRVlXT1JEX1'
    'RFWFRfVE9PX0xPTkcQBRIeChpLRVlXT1JEX0hBU19UT09fTUFOWV9XT1JEUxAGEh0KGUtFWVdP'
    'UkRfSEFTX0lOVkFMSURfQ0hBUlMQBxIZChVJTlZBTElEX1BMQUNFTUVOVF9VUkwQCBIVChFJTl'
    'ZBTElEX1VTRVJfTElTVBAJEhkKFUlOVkFMSURfVVNFUl9JTlRFUkVTVBAKEiQKIElOVkFMSURf'
    'Rk9STUFUX0ZPUl9QTEFDRU1FTlRfVVJMEAsSHQoZUExBQ0VNRU5UX1VSTF9JU19UT09fTE9ORx'
    'AMEiIKHlBMQUNFTUVOVF9VUkxfSEFTX0lMTEVHQUxfQ0hBUhANEiwKKFBMQUNFTUVOVF9VUkxf'
    'SEFTX01VTFRJUExFX1NJVEVTX0lOX0xJTkUQDhI5CjVQTEFDRU1FTlRfSVNfTk9UX0FWQUlMQU'
    'JMRV9GT1JfVEFSR0VUSU5HX09SX0VYQ0xVU0lPThAPEhYKEklOVkFMSURfVE9QSUNfUEFUSBAQ'
    'Eh4KGklOVkFMSURfWU9VVFVCRV9DSEFOTkVMX0lEEBESHAoYSU5WQUxJRF9ZT1VUVUJFX1ZJRE'
    'VPX0lEEBISJwojWU9VVFVCRV9WRVJUSUNBTF9DSEFOTkVMX0RFUFJFQ0FURUQQExIqCiZZT1VU'
    'VUJFX0RFTU9HUkFQSElDX0NIQU5ORUxfREVQUkVDQVRFRBAUEhsKF1lPVVRVQkVfVVJMX1VOU1'
    'VQUE9SVEVEEBUSIAocQ0FOTk9UX0VYQ0xVREVfQ1JJVEVSSUFfVFlQRRAWEhwKGENBTk5PVF9B'
    'RERfQ1JJVEVSSUFfVFlQRRAXEiQKIENBTk5PVF9FWENMVURFX1NJTUlMQVJfVVNFUl9MSVNUEB'
    'oSHwobQ0FOTk9UX0FERF9DTE9TRURfVVNFUl9MSVNUEBsSOgo2Q0FOTk9UX0FERF9ESVNQTEFZ'
    'X09OTFlfTElTVFNfVE9fU0VBUkNIX09OTFlfQ0FNUEFJR05TEBwSNQoxQ0FOTk9UX0FERF9ESV'
    'NQTEFZX09OTFlfTElTVFNfVE9fU0VBUkNIX0NBTVBBSUdOUxAdEjcKM0NBTk5PVF9BRERfRElT'
    'UExBWV9PTkxZX0xJU1RTX1RPX1NIT1BQSU5HX0NBTVBBSUdOUxAeEjEKLUNBTk5PVF9BRERfVV'
    'NFUl9JTlRFUkVTVFNfVE9fU0VBUkNIX0NBTVBBSUdOUxAfEjkKNUNBTk5PVF9TRVRfQklEU19P'
    'Tl9DUklURVJJT05fVFlQRV9JTl9TRUFSQ0hfQ0FNUEFJR05TECASNwozQ0FOTk9UX0FERF9VUk'
    'xTX1RPX0NSSVRFUklPTl9UWVBFX0ZPUl9DQU1QQUlHTl9UWVBFECESHQoZSU5WQUxJRF9DT01C'
    'SU5FRF9BVURJRU5DRRB6EhsKF0lOVkFMSURfQ1VTVE9NX0FGRklOSVRZEGASGQoVSU5WQUxJRF'
    '9DVVNUT01fSU5URU5UEGESGwoXSU5WQUxJRF9DVVNUT01fQVVESUVOQ0UQeRIWChJJTlZBTElE'
    'X0lQX0FERFJFU1MQIhIVChFJTlZBTElEX0lQX0ZPUk1BVBAjEhYKEklOVkFMSURfTU9CSUxFX0'
    'FQUBAkEh8KG0lOVkFMSURfTU9CSUxFX0FQUF9DQVRFR09SWRAlEhgKFElOVkFMSURfQ1JJVEVS'
    'SU9OX0lEECYSGwoXQ0FOTk9UX1RBUkdFVF9DUklURVJJT04QJxIkCiBDQU5OT1RfVEFSR0VUX0'
    '9CU09MRVRFX0NSSVRFUklPThAoEiIKHkNSSVRFUklPTl9JRF9BTkRfVFlQRV9NSVNNQVRDSBAp'
    'EhwKGElOVkFMSURfUFJPWElNSVRZX1JBRElVUxAqEiIKHklOVkFMSURfUFJPWElNSVRZX1JBRE'
    'lVU19VTklUUxArEiAKHElOVkFMSURfU1RSRUVUQUREUkVTU19MRU5HVEgQLBIbChdJTlZBTElE'
    'X0NJVFlOQU1FX0xFTkdUSBAtEh0KGUlOVkFMSURfUkVHSU9OQ09ERV9MRU5HVEgQLhIdChlJTl'
    'ZBTElEX1JFR0lPTk5BTUVfTEVOR1RIEC8SHQoZSU5WQUxJRF9QT1NUQUxDT0RFX0xFTkdUSBAw'
    'EhgKFElOVkFMSURfQ09VTlRSWV9DT0RFEDESFAoQSU5WQUxJRF9MQVRJVFVERRAyEhUKEUlOVk'
    'FMSURfTE9OR0lUVURFEDMSNgoyUFJPWElNSVRZX0dFT1BPSU5UX0FORF9BRERSRVNTX0JPVEhf'
    'Q0FOTk9UX0JFX05VTEwQNBIdChlJTlZBTElEX1BST1hJTUlUWV9BRERSRVNTEDUSHAoYSU5WQU'
    'xJRF9VU0VSX0RPTUFJTl9OQU1FEDYSIAocQ1JJVEVSSU9OX1BBUkFNRVRFUl9UT09fTE9ORxA3'
    'EiYKIkFEX1NDSEVEVUxFX1RJTUVfSU5URVJWQUxTX09WRVJMQVAQOBIyCi5BRF9TQ0hFRFVMRV'
    '9JTlRFUlZBTF9DQU5OT1RfU1BBTl9NVUxUSVBMRV9EQVlTEDkSJQohQURfU0NIRURVTEVfSU5W'
    'QUxJRF9USU1FX0lOVEVSVkFMEDoSMAosQURfU0NIRURVTEVfRVhDRUVERURfSU5URVJWQUxTX1'
    'BFUl9EQVlfTElNSVQQOxIvCitBRF9TQ0hFRFVMRV9DUklURVJJT05fSURfTUlTTUFUQ0hJTkdf'
    'RklFTERTEDwSJAogQ0FOTk9UX0JJRF9NT0RJRllfQ1JJVEVSSU9OX1RZUEUQPRIyCi5DQU5OT1'
    'RfQklEX01PRElGWV9DUklURVJJT05fQ0FNUEFJR05fT1BURURfT1VUED4SKAokQ0FOTk9UX0JJ'
    'RF9NT0RJRllfTkVHQVRJVkVfQ1JJVEVSSU9OED8SHwobQklEX01PRElGSUVSX0FMUkVBRFlfRV'
    'hJU1RTEEASFwoTRkVFRF9JRF9OT1RfQUxMT1dFRBBBEigKJEFDQ09VTlRfSU5FTElHSUJMRV9G'
    'T1JfQ1JJVEVSSUFfVFlQRRBCEi4KKkNSSVRFUklBX1RZUEVfSU5WQUxJRF9GT1JfQklERElOR1'
    '9TVFJBVEVHWRBDEhwKGENBTk5PVF9FWENMVURFX0NSSVRFUklPThBEEhsKF0NBTk5PVF9SRU1P'
    'VkVfQ1JJVEVSSU9OEEUSJAogSU5WQUxJRF9QUk9EVUNUX0JJRERJTkdfQ0FURUdPUlkQTBIcCh'
    'hNSVNTSU5HX1NIT1BQSU5HX1NFVFRJTkcQTRIdChlJTlZBTElEX01BVENISU5HX0ZVTkNUSU9O'
    'EE4SHwobTE9DQVRJT05fRklMVEVSX05PVF9BTExPV0VEEE8SJAogSU5WQUxJRF9GRUVEX0ZPUl'
    '9MT0NBVElPTl9GSUxURVIQYhIbChdMT0NBVElPTl9GSUxURVJfSU5WQUxJRBBQEjcKM0NBTk5P'
    'VF9TRVRfR0VPX1RBUkdFVF9DT05TVEFOVFNfV0lUSF9GRUVEX0lURU1fU0VUUxB7EicKIkNBTk'
    '5PVF9TRVRfQk9USF9BU1NFVF9TRVRfQU5EX0ZFRUQQjAESMwouQ0FOTk9UX1NFVF9GRUVEX09S'
    'X0ZFRURfSVRFTV9TRVRTX0ZPUl9DVVNUT01FUhCOARIsCidDQU5OT1RfU0VUX0FTU0VUX1NFVF'
    '9GSUVMRF9GT1JfQ1VTVE9NRVIQlgESNAovQ0FOTk9UX1NFVF9HRU9fVEFSR0VUX0NPTlNUQU5U'
    'U19XSVRIX0FTU0VUX1NFVFMQjwESLgopQ0FOTk9UX1NFVF9BU1NFVF9TRVRTX1dJVEhfRkVFRF'
    '9JVEVNX1NFVFMQkAESJQogSU5WQUxJRF9MT0NBVElPTl9HUk9VUF9BU1NFVF9TRVQQjQESIQod'
    'SU5WQUxJRF9MT0NBVElPTl9HUk9VUF9SQURJVVMQfBImCiJJTlZBTElEX0xPQ0FUSU9OX0dST1'
    'VQX1JBRElVU19VTklUEH0SMgouQ0FOTk9UX0FUVEFDSF9DUklURVJJQV9BVF9DQU1QQUlHTl9B'
    'TkRfQURHUk9VUBBREjkKNUhPVEVMX0xFTkdUSF9PRl9TVEFZX09WRVJMQVBTX1dJVEhfRVhJU1'
    'RJTkdfQ1JJVEVSSU9OEFISQQo9SE9URUxfQURWQU5DRV9CT09LSU5HX1dJTkRPV19PVkVSTEFQ'
    'U19XSVRIX0VYSVNUSU5HX0NSSVRFUklPThBTEi4KKkZJRUxEX0lOQ09NUEFUSUJMRV9XSVRIX0'
    '5FR0FUSVZFX1RBUkdFVElORxBUEh0KGUlOVkFMSURfV0VCUEFHRV9DT05ESVRJT04QVRIhCh1J'
    'TlZBTElEX1dFQlBBR0VfQ09ORElUSU9OX1VSTBBWEikKJVdFQlBBR0VfQ09ORElUSU9OX1VSTF'
    '9DQU5OT1RfQkVfRU1QVFkQVxIuCipXRUJQQUdFX0NPTkRJVElPTl9VUkxfVU5TVVBQT1JURURf'
    'UFJPVE9DT0wQWBIuCipXRUJQQUdFX0NPTkRJVElPTl9VUkxfQ0FOTk9UX0JFX0lQX0FERFJFU1'
    'MQWRJFCkFXRUJQQUdFX0NPTkRJVElPTl9VUkxfRE9NQUlOX05PVF9DT05TSVNURU5UX1dJVEhf'
    'Q0FNUEFJR05fU0VUVElORxBaEjEKLVdFQlBBR0VfQ09ORElUSU9OX1VSTF9DQU5OT1RfQkVfUF'
    'VCTElDX1NVRkZJWBBbEi8KK1dFQlBBR0VfQ09ORElUSU9OX1VSTF9JTlZBTElEX1BVQkxJQ19T'
    'VUZGSVgQXBI5CjVXRUJQQUdFX0NPTkRJVElPTl9VUkxfVkFMVUVfVFJBQ0tfVkFMVUVfTk9UX1'
    'NVUFBPUlRFRBBdEjwKOFdFQlBBR0VfQ1JJVEVSSU9OX1VSTF9FUVVBTFNfQ0FOX0hBVkVfT05M'
    'WV9PTkVfQ09ORElUSU9OEF4SNwozV0VCUEFHRV9DUklURVJJT05fTk9UX1NVUFBPUlRFRF9PTl'
    '9OT05fRFNBX0FEX0dST1VQEF8SNwozQ0FOTk9UX1RBUkdFVF9VU0VSX0xJU1RfRk9SX1NNQVJU'
    'X0RJU1BMQVlfQ0FNUEFJR05TEGMSMQotQ0FOTk9UX1RBUkdFVF9QTEFDRU1FTlRTX0ZPUl9TRU'
    'FSQ0hfQ0FNUEFJR05TEH4SKgomTElTVElOR19TQ09QRV9UT09fTUFOWV9ESU1FTlNJT05fVFlQ'
    'RVMQZBInCiNMSVNUSU5HX1NDT1BFX1RPT19NQU5ZX0lOX09QRVJBVE9SUxBlEisKJ0xJU1RJTk'
    'dfU0NPUEVfSU5fT1BFUkFUT1JfTk9UX1NVUFBPUlRFRBBmEiQKIERVUExJQ0FURV9MSVNUSU5H'
    'X0RJTUVOU0lPTl9UWVBFEGcSJQohRFVQTElDQVRFX0xJU1RJTkdfRElNRU5TSU9OX1ZBTFVFEG'
    'gSMAosQ0FOTk9UX1NFVF9CSURTX09OX0xJU1RJTkdfR1JPVVBfU1VCRElWSVNJT04QaRIjCh9J'
    'TlZBTElEX0xJU1RJTkdfR1JPVVBfSElFUkFSQ0hZEGoSKwonTElTVElOR19HUk9VUF9VTklUX0'
    'NBTk5PVF9IQVZFX0NISUxEUkVOEGsSMgouTElTVElOR19HUk9VUF9TVUJESVZJU0lPTl9SRVFV'
    'SVJFU19PVEhFUlNfQ0FTRRBsEjoKNkxJU1RJTkdfR1JPVVBfUkVRVUlSRVNfU0FNRV9ESU1FTl'
    'NJT05fVFlQRV9BU19TSUJMSU5HUxBtEiAKHExJU1RJTkdfR1JPVVBfQUxSRUFEWV9FWElTVFMQ'
    'bhIgChxMSVNUSU5HX0dST1VQX0RPRVNfTk9UX0VYSVNUEG8SIwofTElTVElOR19HUk9VUF9DQU'
    '5OT1RfQkVfUkVNT1ZFRBBwEh4KGklOVkFMSURfTElTVElOR19HUk9VUF9UWVBFEHESKgomTElT'
    'VElOR19HUk9VUF9BRERfTUFZX09OTFlfVVNFX1RFTVBfSUQQchIaChZMSVNUSU5HX1NDT1BFX1'
    'RPT19MT05HEHMSJQohTElTVElOR19TQ09QRV9UT09fTUFOWV9ESU1FTlNJT05TEHQSGgoWTElT'
    'VElOR19HUk9VUF9UT09fTE9ORxB1Eh8KG0xJU1RJTkdfR1JPVVBfVFJFRV9UT09fREVFUBB2Eh'
    '0KGUlOVkFMSURfTElTVElOR19ESU1FTlNJT04QdxIiCh5JTlZBTElEX0xJU1RJTkdfRElNRU5T'
    'SU9OX1RZUEUQeBJACjxBRFZFUlRJU0VSX05PVF9PTl9BTExPV0xJU1RfRk9SX0NPTUJJTkVEX0'
    'FVRElFTkNFX09OX0RJU1BMQVkQfxIsCidDQU5OT1RfVEFSR0VUX1JFTU9WRURfQ09NQklORURf'
    'QVVESUVOQ0UQgAESIQocSU5WQUxJRF9DT01CSU5FRF9BVURJRU5DRV9JRBCBARIqCiVDQU5OT1'
    'RfVEFSR0VUX1JFTU9WRURfQ1VTVE9NX0FVRElFTkNFEIIBEj8KOkhPVEVMX0NIRUNLX0lOX0RB'
    'VEVfUkFOR0VfT1ZFUkxBUFNfV0lUSF9FWElTVElOR19DUklURVJJT04QgwESMwouSE9URUxfQ0'
    'hFQ0tfSU5fREFURV9SQU5HRV9TVEFSVF9EQVRFX1RPT19FQVJMWRCEARIwCitIT1RFTF9DSEVD'
    'S19JTl9EQVRFX1JBTkdFX0VORF9EQVRFX1RPT19MQVRFEIUBEicKIkhPVEVMX0NIRUNLX0lOX0'
    'RBVEVfUkFOR0VfUkVWRVJTRUQQhgESLQooQlJPQURfTUFUQ0hfTU9ESUZJRVJfS0VZV09SRF9O'
    'T1RfQUxMT1dFRBCHARIpCiRPTkVfQVVESUVOQ0VfQUxMT1dFRF9QRVJfQVNTRVRfR1JPVVAQiA'
    'ESLAonQVVESUVOQ0VfTk9UX0VMSUdJQkxFX0ZPUl9DQU1QQUlHTl9UWVBFEIkBEkYKQUFVRElF'
    'TkNFX05PVF9BTExPV0VEX1RPX0FUVEFDSF9XSEVOX0FVRElFTkNFX0dST1VQRURfU0VUX1RPX0'
    'ZBTFNFEIoBEisKJkNBTk5PVF9UQVJHRVRfQ1VTVE9NRVJfTUFUQ0hfVVNFUl9MSVNUEIsBEi8K'
    'Kk5FR0FUSVZFX0tFWVdPUkRfU0hBUkVEX1NFVF9ET0VTX05PVF9FWElTVBCRARIzCi5DQU5OT1'
    'RfQUREX1JFTU9WRURfTkVHQVRJVkVfS0VZV09SRF9TSEFSRURfU0VUEJIBEjsKNkNBTk5PVF9I'
    'QVZFX01VTFRJUExFX05FR0FUSVZFX0tFWVdPUkRfTElTVF9QRVJfQUNDT1VOVBCTARIvCipDVV'
    'NUT01FUl9DQU5OT1RfQUREX0NSSVRFUklPTl9PRl9USElTX1RZUEUQlQESJAofQ0FOTk9UX1RB'
    'UkdFVF9TSU1JTEFSX1VTRVJfTElTVBCXARJHCkJDQU5OT1RfQUREX0FVRElFTkNFX1NFR01FTl'
    'RfQ1JJVEVSSU9OX1dIRU5fQVVESUVOQ0VfR1JPVVBFRF9JU19TRVQQmAESJgohT05FX0FVRElF'
    'TkNFX0FMTE9XRURfUEVSX0FEX0dST1VQEJkBEiEKHElOVkFMSURfREVUQUlMRURfREVNT0dSQV'
    'BISUMQmgESGwoWQ0FOTk9UX1JFQ09HTklaRV9CUkFORBCbARIkCh9CUkFORF9TSEFSRURfU0VU'
    'X0RPRVNfTk9UX0VYSVNUEJwBEigKI0NBTk5PVF9BRERfUkVNT1ZFRF9CUkFORF9TSEFSRURfU0'
    'VUEJ0BEjgKM09OTFlfRVhDTFVTSU9OX0JSQU5EX0xJU1RfQUxMT1dFRF9GT1JfQ0FNUEFJR05f'
    'VFlQRRCeAQ==');

