//
//  Generated code. Do not modify.
//  source: google/ads/googleads/v16/errors/extension_feed_item_error.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use extensionFeedItemErrorEnumDescriptor instead')
const ExtensionFeedItemErrorEnum$json = {
  '1': 'ExtensionFeedItemErrorEnum',
  '4': [ExtensionFeedItemErrorEnum_ExtensionFeedItemError$json],
};

@$core.Deprecated('Use extensionFeedItemErrorEnumDescriptor instead')
const ExtensionFeedItemErrorEnum_ExtensionFeedItemError$json = {
  '1': 'ExtensionFeedItemError',
  '2': [
    {'1': 'UNSPECIFIED', '2': 0},
    {'1': 'UNKNOWN', '2': 1},
    {'1': 'VALUE_OUT_OF_RANGE', '2': 2},
    {'1': 'URL_LIST_TOO_LONG', '2': 3},
    {'1': 'CANNOT_HAVE_RESTRICTION_ON_EMPTY_GEO_TARGETING', '2': 4},
    {'1': 'CANNOT_SET_WITH_FINAL_URLS', '2': 5},
    {'1': 'CANNOT_SET_WITHOUT_FINAL_URLS', '2': 6},
    {'1': 'INVALID_PHONE_NUMBER', '2': 7},
    {'1': 'PHONE_NUMBER_NOT_SUPPORTED_FOR_COUNTRY', '2': 8},
    {'1': 'CARRIER_SPECIFIC_SHORT_NUMBER_NOT_ALLOWED', '2': 9},
    {'1': 'PREMIUM_RATE_NUMBER_NOT_ALLOWED', '2': 10},
    {'1': 'DISALLOWED_NUMBER_TYPE', '2': 11},
    {'1': 'INVALID_DOMESTIC_PHONE_NUMBER_FORMAT', '2': 12},
    {'1': 'VANITY_PHONE_NUMBER_NOT_ALLOWED', '2': 13},
    {'1': 'INVALID_CALL_CONVERSION_ACTION', '2': 14},
    {'1': 'CUSTOMER_NOT_ON_ALLOWLIST_FOR_CALLTRACKING', '2': 47},
    {'1': 'CALLTRACKING_NOT_SUPPORTED_FOR_COUNTRY', '2': 16},
    {'1': 'CUSTOMER_CONSENT_FOR_CALL_RECORDING_REQUIRED', '2': 17},
    {'1': 'INVALID_APP_ID', '2': 18},
    {'1': 'QUOTES_IN_REVIEW_EXTENSION_SNIPPET', '2': 19},
    {'1': 'HYPHENS_IN_REVIEW_EXTENSION_SNIPPET', '2': 20},
    {'1': 'REVIEW_EXTENSION_SOURCE_INELIGIBLE', '2': 21},
    {'1': 'SOURCE_NAME_IN_REVIEW_EXTENSION_TEXT', '2': 22},
    {'1': 'INCONSISTENT_CURRENCY_CODES', '2': 23},
    {'1': 'PRICE_EXTENSION_HAS_DUPLICATED_HEADERS', '2': 24},
    {'1': 'PRICE_ITEM_HAS_DUPLICATED_HEADER_AND_DESCRIPTION', '2': 25},
    {'1': 'PRICE_EXTENSION_HAS_TOO_FEW_ITEMS', '2': 26},
    {'1': 'PRICE_EXTENSION_HAS_TOO_MANY_ITEMS', '2': 27},
    {'1': 'UNSUPPORTED_VALUE', '2': 28},
    {'1': 'UNSUPPORTED_VALUE_IN_SELECTED_LANGUAGE', '2': 29},
    {'1': 'INVALID_DEVICE_PREFERENCE', '2': 30},
    {'1': 'INVALID_SCHEDULE_END', '2': 31},
    {'1': 'DATE_TIME_MUST_BE_IN_ACCOUNT_TIME_ZONE', '2': 32},
    {'1': 'INVALID_SNIPPETS_HEADER', '2': 33},
    {'1': 'CANNOT_OPERATE_ON_REMOVED_FEED_ITEM', '2': 34},
    {'1': 'PHONE_NUMBER_NOT_SUPPORTED_WITH_CALLTRACKING_FOR_COUNTRY', '2': 35},
    {'1': 'CONFLICTING_CALL_CONVERSION_SETTINGS', '2': 36},
    {'1': 'EXTENSION_TYPE_MISMATCH', '2': 37},
    {'1': 'EXTENSION_SUBTYPE_REQUIRED', '2': 38},
    {'1': 'EXTENSION_TYPE_UNSUPPORTED', '2': 39},
    {'1': 'CANNOT_OPERATE_ON_FEED_WITH_MULTIPLE_MAPPINGS', '2': 40},
    {'1': 'CANNOT_OPERATE_ON_FEED_WITH_KEY_ATTRIBUTES', '2': 41},
    {'1': 'INVALID_PRICE_FORMAT', '2': 42},
    {'1': 'PROMOTION_INVALID_TIME', '2': 43},
    {'1': 'TOO_MANY_DECIMAL_PLACES_SPECIFIED', '2': 44},
    {'1': 'CONCRETE_EXTENSION_TYPE_REQUIRED', '2': 45},
    {'1': 'SCHEDULE_END_NOT_AFTER_START', '2': 46},
  ],
};

/// Descriptor for `ExtensionFeedItemErrorEnum`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List extensionFeedItemErrorEnumDescriptor = $convert.base64Decode(
    'ChpFeHRlbnNpb25GZWVkSXRlbUVycm9yRW51bSLXDQoWRXh0ZW5zaW9uRmVlZEl0ZW1FcnJvch'
    'IPCgtVTlNQRUNJRklFRBAAEgsKB1VOS05PV04QARIWChJWQUxVRV9PVVRfT0ZfUkFOR0UQAhIV'
    'ChFVUkxfTElTVF9UT09fTE9ORxADEjIKLkNBTk5PVF9IQVZFX1JFU1RSSUNUSU9OX09OX0VNUF'
    'RZX0dFT19UQVJHRVRJTkcQBBIeChpDQU5OT1RfU0VUX1dJVEhfRklOQUxfVVJMUxAFEiEKHUNB'
    'Tk5PVF9TRVRfV0lUSE9VVF9GSU5BTF9VUkxTEAYSGAoUSU5WQUxJRF9QSE9ORV9OVU1CRVIQBx'
    'IqCiZQSE9ORV9OVU1CRVJfTk9UX1NVUFBPUlRFRF9GT1JfQ09VTlRSWRAIEi0KKUNBUlJJRVJf'
    'U1BFQ0lGSUNfU0hPUlRfTlVNQkVSX05PVF9BTExPV0VEEAkSIwofUFJFTUlVTV9SQVRFX05VTU'
    'JFUl9OT1RfQUxMT1dFRBAKEhoKFkRJU0FMTE9XRURfTlVNQkVSX1RZUEUQCxIoCiRJTlZBTElE'
    'X0RPTUVTVElDX1BIT05FX05VTUJFUl9GT1JNQVQQDBIjCh9WQU5JVFlfUEhPTkVfTlVNQkVSX0'
    '5PVF9BTExPV0VEEA0SIgoeSU5WQUxJRF9DQUxMX0NPTlZFUlNJT05fQUNUSU9OEA4SLgoqQ1VT'
    'VE9NRVJfTk9UX09OX0FMTE9XTElTVF9GT1JfQ0FMTFRSQUNLSU5HEC8SKgomQ0FMTFRSQUNLSU'
    '5HX05PVF9TVVBQT1JURURfRk9SX0NPVU5UUlkQEBIwCixDVVNUT01FUl9DT05TRU5UX0ZPUl9D'
    'QUxMX1JFQ09SRElOR19SRVFVSVJFRBAREhIKDklOVkFMSURfQVBQX0lEEBISJgoiUVVPVEVTX0'
    'lOX1JFVklFV19FWFRFTlNJT05fU05JUFBFVBATEicKI0hZUEhFTlNfSU5fUkVWSUVXX0VYVEVO'
    'U0lPTl9TTklQUEVUEBQSJgoiUkVWSUVXX0VYVEVOU0lPTl9TT1VSQ0VfSU5FTElHSUJMRRAVEi'
    'gKJFNPVVJDRV9OQU1FX0lOX1JFVklFV19FWFRFTlNJT05fVEVYVBAWEh8KG0lOQ09OU0lTVEVO'
    'VF9DVVJSRU5DWV9DT0RFUxAXEioKJlBSSUNFX0VYVEVOU0lPTl9IQVNfRFVQTElDQVRFRF9IRU'
    'FERVJTEBgSNAowUFJJQ0VfSVRFTV9IQVNfRFVQTElDQVRFRF9IRUFERVJfQU5EX0RFU0NSSVBU'
    'SU9OEBkSJQohUFJJQ0VfRVhURU5TSU9OX0hBU19UT09fRkVXX0lURU1TEBoSJgoiUFJJQ0VfRV'
    'hURU5TSU9OX0hBU19UT09fTUFOWV9JVEVNUxAbEhUKEVVOU1VQUE9SVEVEX1ZBTFVFEBwSKgom'
    'VU5TVVBQT1JURURfVkFMVUVfSU5fU0VMRUNURURfTEFOR1VBR0UQHRIdChlJTlZBTElEX0RFVk'
    'lDRV9QUkVGRVJFTkNFEB4SGAoUSU5WQUxJRF9TQ0hFRFVMRV9FTkQQHxIqCiZEQVRFX1RJTUVf'
    'TVVTVF9CRV9JTl9BQ0NPVU5UX1RJTUVfWk9ORRAgEhsKF0lOVkFMSURfU05JUFBFVFNfSEVBRE'
    'VSECESJwojQ0FOTk9UX09QRVJBVEVfT05fUkVNT1ZFRF9GRUVEX0lURU0QIhI8CjhQSE9ORV9O'
    'VU1CRVJfTk9UX1NVUFBPUlRFRF9XSVRIX0NBTExUUkFDS0lOR19GT1JfQ09VTlRSWRAjEigKJE'
    'NPTkZMSUNUSU5HX0NBTExfQ09OVkVSU0lPTl9TRVRUSU5HUxAkEhsKF0VYVEVOU0lPTl9UWVBF'
    'X01JU01BVENIECUSHgoaRVhURU5TSU9OX1NVQlRZUEVfUkVRVUlSRUQQJhIeChpFWFRFTlNJT0'
    '5fVFlQRV9VTlNVUFBPUlRFRBAnEjEKLUNBTk5PVF9PUEVSQVRFX09OX0ZFRURfV0lUSF9NVUxU'
    'SVBMRV9NQVBQSU5HUxAoEi4KKkNBTk5PVF9PUEVSQVRFX09OX0ZFRURfV0lUSF9LRVlfQVRUUk'
    'lCVVRFUxApEhgKFElOVkFMSURfUFJJQ0VfRk9STUFUECoSGgoWUFJPTU9USU9OX0lOVkFMSURf'
    'VElNRRArEiUKIVRPT19NQU5ZX0RFQ0lNQUxfUExBQ0VTX1NQRUNJRklFRBAsEiQKIENPTkNSRV'
    'RFX0VYVEVOU0lPTl9UWVBFX1JFUVVJUkVEEC0SIAocU0NIRURVTEVfRU5EX05PVF9BRlRFUl9T'
    'VEFSVBAu');

